### ISSUE TITLE
Use easyrtc client as RequireJS module.

### ISSUE THREAD

**Issue by PSyton** [priologic/easyrtc#100]
It will be nice if easyrtc support AMD.

**Comment by jolo70** [comment]
Hi @EricDavies, any update? Much appreciated - just getting into easyRTC and come from RequireJS world.  I come in peace! :P

**Comment by EricDavies** [comment]
As Mike Anderson pointed out, with a little bit of shellscripting you can wrap up the script yourself for the RequireJS. My perspective is that I'd rather not do it in our code because it would make easyrtc.js dependent on another module.

**Comment by jolo70** [comment]
Thanks.  I was able to get it working.

**Comment by hthetiot** [comment]
@jolo70 Will will do a better packing and module work on release 1.0.17

**Comment by hthetiot** [comment]
@jolo70 @PSyton 

https://gist.github.com/hthetiot/0faac27c16429c904ec8
