### ISSUE TITLE
Hello, what settings to easyRTC run remotely on a web server and not locally.

### ISSUE THREAD

**Issue by Mercocoin** [priologic/easyrtc#114]
Hello, what settings to easyRTC run remotely on a web server and not locally.

**Comment by EricDavies** [comment]
If you mean, how do I use a traditional webserver with easyrtc, see http://easyrtc.com/docs/guides/easyrtc_with_other_servers.php
note: you'll still require nodejs running for the socket server. Easyrtc is dependent on nodejs

Other than that, there isn't anything above what you'd need to do with any server.

**Comment by Mercocoin** [comment]
Ok, thank you! I will look.

**Comment by Mercocoin** [comment]
it is possible to use the EasyRTC in android with cordova?
