### ISSUE TITLE
FF warning: addIceCandidate called without success/failure callbacks.

### ISSUE THREAD

**Issue by fbernhard** [priologic/easyrtc#118]
Firefox 35 throws a warning because RTCPeerConnection.addIceCandidate() is called without success and failure callbacks. See spec here:

https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection#addIceCandidate()

The warning message states that this will be an error in the future:

``addIceCandidate called without success/failure callbacks. This is deprecated, and will be an error in the future.``

**Comment by EricDavies** [comment]
Hi Fabian,

Thank you for pointing it out. I've just patched the beta branch. Also caught a few places where setRemoteDescription wasn't getting success/failure callbacks.
