### ISSUE TITLE
Is there any method to join without camera?

### ISSUE THREAD

**Issue by prospdragon** [priologic/easyrtc#119]
A user without webcams cannot join the room. 
Is it possible to join in easyRTC ?

**Comment by EricDavies** [comment]
Rooms are a discovery mechanism. If you try the "instant messaging + 
rooms" demo, you'll see
that there is no media stream requested at all.

When you "call" another party, you can prevent a media stream from being 
sent by specifying an empty list [] for the list of stream names in the 
call. Similar trick in your accept function. These are documented in the 
docs that come with the distribution but aren't on the website.


      call(otherUser, callSuccessCB, callFailureCB, wasAcceptedCB,
      streamNames)

    Initiates a call to another user. If it succeeds, the streamAcceptor
    callback will be called.


              Parameters:

    Name 	Type 	Description
    |otherUser| 	String 	the easyrtcid of the peer being called.
    |callSuccessCB| 	function 	(otherCaller, mediaType) - is called when
    the datachannel is established or the MediaStream is established.
    mediaType will have a value of "audiovideo" or "datachannel"
    |callFailureCB| 	function 	(errorCode, errMessage) - is called if
    there was a system error interfering with the call.
    |wasAcceptedCB| 	function 	(wasAccepted:boolean,otherUser:string) -
    is called when a call is accepted or rejected by another party. It
    can be left null.
    |streamNames| 	Array 	optional array of streamNames.


      setAcceptChecker(acceptCheck)

    Sets the callback used to decide whether to accept or reject an
    incoming call.


              Parameters:

    Name 	Type 	Description
    |acceptCheck| 	function 	takes the arguments (callerEasyrtcid,
    acceptor). The acceptCheck callback is passed an easyrtcid and an
    aceptor function. The acceptor function should be called with either
    a true value (accept the call) or false value( reject the call) as
    it's first argument, and optionally, an array of local media
    streamNames as a second argument.


              Example

    |easyrtc.setAcceptChecker( function(easyrtcid, acceptor){
          if( easyrtc.idToName(easyrtcid) === 'Fred' ){
             acceptor(true);
          }
          else if( easyrtc.idToName(easyrtcid) === 'Barney' ){
             setTimeout( function(){
    acceptor(true, ['myOtherCam']); // myOtherCam presumed to a streamName
    }, 10000);
          }
          else{
             acceptor(false);
          }
    });|


The client without a camera can also use:


      setAutoInitUserMedia(flag)

    Controls whether a default local media stream should be acquired
    automatically during calls and accepts if a list of streamNames is
    not supplied. The default is true, which mimicks the behaviour of
    earlier releases that didn't support multiple streams. This function
    should be called before easyrtc.call or before entering an accept
    callback.


              Parameters:

    Name 	Type 	Description
    |flag| 	Boolean 	true to allocate a default local media stream.

**Comment by prospdragon** [comment]
Is it possible in Firefox ?

**Comment by EricDavies** [comment]
Yes, though it hasn't always in the past.
You can try the different options yourself with http://demo.easyrtc.com/demos/demo_audio_video.html
