### ISSUE TITLE
SetVideoBandWidth problem

### ISSUE THREAD

**Issue by GrahamLinagora** [priologic/easyrtc#120]
Hello, 

I have been trying to use setVideoBandwidth function in my app like described in the tutorial : https://github.com/priologic/easyrtc/blob/master/docs/easyrtc_client_tutorial.md#setting-the-video-bandwidth

But the function is deprecated in the code : 
https://github.com/priologic/easyrtc/blob/master/api/easyrtc.js#L2223
```javascript
  this.setVideoBandwidth = function(kbitsPerSecond) {
        self.showError("easyrtc.setVideoBandwidth is deprecated, it no longer has an effect.");
    };
```

Should I issue a PR to update the tutorial doc ? Or maybe you are going to add this feature back again soon ?

**Comment by hthetiot** [comment]
@GrahamLinagora do PR or I will do later, you decide.

**Comment by hthetiot** [comment]
@GrahamLinagora Removed cause non supported.
