### ISSUE TITLE
chrome 43 offer/answer objects can't be json'ed

### ISSUE THREAD

**Issue by EricDavies** [priologic/easyrtc#125]
As of Chrome 43, the session description objects created by pc.createOffer and p.createAnswer are no longer simple javascript maps, but full fledged objects with constructors. This screwed up JSON.stringify. The fix is to pick out the two fields of interest (sdp and type) and only send those.

**Comment by swhansen** [comment]
Eric, Thanks for the quick fix. Thought I was losing  is when things fel apart for me with Chrome 43. Took a while for me to consider the browser changing under me

**Comment by EricDavies** [comment]
According to posts on discuss-webrtc, the problem was that they 
neglected to provide "serializers" and they are fixing it on their side 
as well.
So it was a premature fix :-).

Eric.
