### ISSUE TITLE
Use SignalR for / IIS as Server Backend?

### ISSUE THREAD

**Issue by coommark** [priologic/easyrtc#126]
Is it possible to use SignalR as the backend instead of NodeJS and Socket.io? Has anyone tried it? I have an app in production using SignalR for real-time stuff like monitoring user presence, chat, etc (with angularjs frontend). I am hoping I can use this for video and audio, since it won't make sence to reimplement authentication etc on a different platform. Plus I will like to store things on a database like missed calls, received calls, etc.

Thanks.

**Comment by EricDavies** [comment]
Unlikely.

That said, there probably isn't any reason that a nodejs backend 
couldn't communicate with your .net backend through a pipe. Nothing 
we've tried. You could try asking on the easyrtc discussion group to see 
if any other users are doing that.

Eric.

**Comment by coommark** [comment]
Thank you Eric! My initial assumption was that the back-end simply needed to transer json to the clients until a peer-to-peer connection is established.

In that case why can't signalr be used?

**Comment by EricDavies** [comment]
There is nothing to stop you from rewriting the backend in signalr.
It's just effort that nobody has done for you yet :-).
