### ISSUE TITLE
How to maintain unique EasyRTC id for unique session

### ISSUE THREAD

**Issue by deepak-manwal** [priologic/easyrtc#135]
I am developing chat application with EasyRTC and Nodejs. 

Once user logs in it redirects to the `welcome.jade`. I am using following **Javascript** code for connecting user:

    function connect() { //calling this function on body onload
        easyrtc.setUsername($('#username').text()); //setting username
        easyrtc.setPeerListener(addToConversation);
        easyrtc.setRoomOccupantListener(convertListToButtons);
        easyrtc.connect("easyrtc.instantMessaging", loginSuccess, loginFailure);
    }
    function loginSuccess(easyrtcid) {  //callback function
        selfEasyrtcid = easyrtcid;
        console.log("I am " + easyrtcid);
    }

Suppose i logged in with user `xyz@gmail.com` then a unique `easyrtcid` generated. But if i open this application in new tab, then another `easyrtcid` generated for same user `xyz@gmail.com`.

**How can I prevent this happening?? How can i create this `easyrtcid` once and use it across the application? Is this possible?**

**Comment by ziaius** [comment]
I solved this by storing identity of users on a signalling server using session cookies. I store their identity in object which I associate with their cookie. I later retrieve that object, using jQuery.getJSON before connecting to easyrtc from the clients side. May not be ideal, but it works.

**Comment by dryswabbie** [comment]
Sorry for the long delay, but questions in our issue tracker often don't get looked at. If you are still having problems, the best place for help is in our forums.
