### ISSUE TITLE
Firefox receiving call is broken due deprecated constraints

### ISSUE THREAD

**Issue by hthetiot** [priologic/easyrtc#138]
I noticed following issue today with using Firefox calling Chrome:
> Mandatory/optional in createOffer options is deprecated! Use {"offerToReceiveAudio":true,"offerToReceiveVideo":true} instead (note the case difference)!

To reproduce:
1. Create room with Firefox
2. User with Firefox call user with Chrome
3. Call fail
    Chrome: display blank video/audio stream
    Firefox: Display following message in the console: 
> Mandatory/optional in createOffer options is deprecated! 
> Use {"offerToReceiveAudio":true,"offerToReceiveVideo":true} instead (note the case difference)!

I tried to change following on easyrtc/api/easyrtc.js
``` 
     var receivedMediaContraints = {
-        'mandatory': {
-            'OfferToReceiveAudio': true,
-            'OfferToReceiveVideo': true
-        }
+        'offerToReceiveAudio': true,
+        'offerToReceiveVideo': true
     };
     /**
      * Control whether the client requests audio from a peer during a call.
@@ -444,7 +442,7 @@ var Easyrtc = function() {
      * @param value - true to receive audio, false otherwise. The default is true.
      */
     this.enableAudioReceive = function(value) {
-        receivedMediaContraints.mandatory.OfferToReceiveAudio = value;
+        receivedMediaContraints.offerToReceiveAudio = value;
     };
     /**
      * Control whether the client requests video from a peer during a call.
@@ -452,7 +450,7 @@ var Easyrtc = function() {
      * @param value - true to receive video, false otherwise. The default is true.
      */
     this.enableVideoReceive = function(value) {
-        receivedMediaContraints.mandatory.OfferToReceiveVideo = value;
+        receivedMediaContraints.offerToReceiveVideo = value;
     };
``` 

But it break Chrome with following:
> Uncaught TypeError: Failed to execute 'createAnswer' on 'RTCPeerConnection': Malformed constraints object.invokeCreateAnswer @ easyrtc.js:3932

Yeah they just broken WebRTC on the FF Call Chrome.
Otherwise Chrome call FF is ok for me.

I will try some other solution and commit a patch if i found a solution.

**Comment by EricDavies** [comment]
Hi Harold,

It's something that's been reported on to us. The problem seems to be that
firefox threw out the old spec before google implemented the new.  As gross
as it sounds, I think the solution is going to be a conditional block of
code (if chrome, do this, otherwise do that) or try the new way but fall
back to the old way if it fails. We're at a trade show at the moment, but
I'll try to come up with a solution in the next few day if time permits, or
failing that, After May 8 (when we get back).

Eric.

**Comment by hthetiot** [comment]
Thanks for good feedback.
Will work on a push to draft at least, if you dont merge.

P.S
If you need a good third party demo for your show about easyrtc.
Sylaps.com is using easyrtc.

**Comment by hthetiot** [comment]
Firefox 37.0.2 and Chrome 42.0.2311.135 (64-bit)
Well done Mozilla. "Dont Break the WebRTC"

**Comment by hthetiot** [comment]
last spec reference
http://w3c.github.io/webrtc-pc/#widl-RTCOfferOptions-offerToReceiveVideo

**Comment by fbernhard** [comment]
Any update on this?

**Comment by EricDavies** [comment]
I played with this on Friday, and just now to confirm. It appears that
Firefox has changed it's mind. I'm running Firefox 38 (on a Mac but that
shouldn't make any difference), and our demos are grabbing the local media
stream without any problem, no error messages showing up.

**Comment by hthetiot** [comment]
Close it pls, Can you give me the right to close my own issues also ?

**Comment by EricDavies** [comment]
It shows up as closed by you already, so I assume that means that you
already have that ability.

**Comment by sergiomeneses** [comment]
Hi i am testing over FireFox 43.0 (on a Mac) and the error messages is showing up.

**Comment by vyshakhbabji** [comment]
Trying out on Firefox 44.0.2 - error msg showing up
