### ISSUE TITLE
How to listen for room API field changes on the client?

### ISSUE THREAD

**Issue by kay-is** [priologic/easyrtc#142]
They seem to be published in the debug output.

But the only event is for the room occupants and this isn't fired on a field change.

**Comment by EricDavies** [comment]
If you set a room occupant listener in one client, you'll see it fired when another client sets an api field for the same room. The easy demonstration of this is using the instant messaging with rooms client: set up two instances (ie, each in a different window), have both both join room1, and connect. Then set a breakpoint on the occupantListener function in one, and then add an api field for room 1 in the other. It won't tell you which api field changed, but it does get fired.
