### ISSUE TITLE
How to integrate easyrtc application on HTTPS server(Apache Tomcat)??

### ISSUE THREAD

**Issue by sanketm221** [priologic/easyrtc#144]
Hi, 
 i am integarting my easyrtc application on https server(Apache tomcat),i am facing some problem.

I have configured apache tomcat with https.I am running esayrtc application on tomcat ,it work fine when use without https.

Apache tomcat works fine when used HTTPS with other application

I have created keystore file and localhost SSL certificate

I followed the steps given on Easyrtc website 
"http://easyrtc.com/docs/guides/easyrtc_server_ssl.php"
 
I have replcaed my server.js with following

........................................................................
// Load required modules
var https   = require("https");     // https server core module
var fs      = require("fs");        // file system core module
var express = require("express");   // web framework external module
var io      = require("socket.io"); // web socket external module
var easyrtc = require("easyrtc");   // EasyRTC external module

// Setup and configure Express http server. Expect a subfolder called "static" to be the web root.
var httpApp = express();
httpApp.use(express.static(__dirname + "/static/"));

// Start Express https server on port 8443
var webServer = https.createServer(
{
    key:  fs.readFileSync("C:/Users/san/.keystore"),  //(I have created Keystore file)
    cert: fs.readFileSync("C:/Users/san/Desktop/certificate/localhost.cer")    //(I have created Locahost certificate file)
},
httpApp).listen(8443);

// Start Socket.io so it attaches itself to Express server
var socketServer = io.listen(webServer, {"log level":1});

// Start EasyRTC server
var rtc = easyrtc.listen(httpApp, socketServer);

.......................................................................

after running node server.js following errror occured 

D:\easyrtc>node server.js
_tls_common.js:108
        c.context.setKey(options.key);
                  ^
Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
    at Error (native)
    at Object.createSecureContext (_tls_common.js:108:19)
    at Server (_tls_wrap.js:598:25)
    at new Server (https.js:36:14)
    at Object.exports.createServer (https.js:56:10)
    at Object.<anonymous> (D:\Sathe sir shared easy rtc\easyrtc\server.js:13:23)

    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

Please help regarding this.

**Comment by dryswabbie** [comment]
Sorry for the long delay, but questions in our issue tracker often don't get looked at. If you are still having problems, the best place for help is in our forums.

**Comment by arjayx** [comment]
hi your issues is to ssl certificate key and cert. You must fix this

**Comment by EricDavies** [comment]
Roberto,

It would probably be useful to be explicit in who you are addressing 
your comment to, particularly given the age of the post.
