### ISSUE TITLE
Socket IO version used

### ISSUE THREAD

**Issue by zapur1** [priologic/easyrtc#146]
Hi

Is it just me or should the package.json file in /server_example not be using Socket IO version 1.x ??? I had a look around (Google groups thread and GitHub Issues) and have also kind of tested it and it appears that Socket IO version 1 should be working with EasyRTC happily????

Just wanting a bit of a confirmation

Thanks,
Zac

**Comment by EricDavies** [comment]
I've tried both. There were some differences on the client side, but I
believe those are taken into account. You might want to ask on the easyrtc
google groups where you can get a larger response.
