### ISSUE TITLE
Allow logging of message contents

### ISSUE THREAD

**Issue by dryswabbie** [priologic/easyrtc#149]
Developers need a way to view the actual incoming and outgoing messages from the server during development.

In Socket.io versions > v1.0 they changed the logging system to the 'debug' module which is opinionated and harder to interact with. Plus Socket.io has never permitted logging of 'returned' messages.

**Comment by hthetiot** [comment]
@dryswabbie Logging of messages content on the console need to be enable/disable by config, for privacy pls.

**Comment by hthetiot** [comment]
@dryswabbie My bad just saw "pub.getOption("logMessagesEnable")"
