### ISSUE TITLE
FileTransfer support on IE10

### ISSUE THREAD

**Issue by hthetiot** [priologic/easyrtc#155]
IE does not support Reader.readAsBinaryString cause it's deprecated.
We need to use readAsArrayBuffer instead.

p.s
sry, for duplicates this time I pushed in beta branch.

**Comment by EricDavies** [comment]
Hi Harold,

I applied to your changes to the beta branch.
https://github.com/priologic/easyrtc/commit/f468bbf843e5966550021246e53850bee868d699

Eric.

**Comment by dryswabbie** [comment]
Is this issue good to close than?

**Comment by EricDavies** [comment]
yes
