### ISSUE TITLE
Dockerfile and easyrtc

### ISSUE THREAD

**Issue by UnknownHero** [priologic/easyrtc#156]
Hi!
I find your Docker repository with demo - https://hub.docker.com/r/priologic/easyrtc-demo/
Can you provide Dockerfile or create autobuild with GitHub & Dockerfile on docker hub ?
Thanks.

**Comment by dryswabbie** [comment]
The creation of a Dockerfile should be done at the Node application level, not the Node module level (which is where EasyRTC lies). The environment depicted in our public Docker container is just one of many that EasyRTC can run in. While you are free to utilize our public Docker, it isn't officially supported or kept up-to-date. I would recommend also looking at the official Node docker for instructions on Dockerizing a Node.js app.
 
https://hub.docker.com/_/node/
