### ISSUE TITLE
Chrome - FF interop issue

### ISSUE THREAD

**Issue by fbernhard** [priologic/easyrtc#157]
Hi all,

I post this issue here even though it is not easyrtc related. We have tested this issue with apprtc and other services with the same results. I wanted to discuss this issue here in order to provide a fix to easyrtc later. I hope you can share some insights and thoughts.

Scenario: 
https://demo.easyrtc.com/demos/demo_audio_video.html
1 users joins with Google Chrome and shares/expects audio and video
1 user joins with Firefox and shares audio only, expects both video and audio

Result:
Google Chrome user doesn't play the audio received from FF.

What we have discovered so far:
Even though we request FF to send audio only we also receive a video media track.  In "setStreamAcceptor" both media tracks (audio and video) have the property "muted" set to "false". About 3 seconds later the video track will have the "muted" property changed to "true".  When we manually remove the muted video track and reattach the media stream we hear sound in Chrome. This means that audio is sent from FF.

How can we make FF to not send an empty video track?

**Comment by hthetiot** [comment]
Did not have any kind of issue like that if both have audio/video like you describe for a while.
See possible #138 duplicate.

**Comment by fbernhard** [comment]
We still have the issue with the following configuration:

```
	easyrtc.enableAudio(true);
	easyrtc.enableAudioReceive(true);
	easyrtc.enableVideo(false);
	easyrtc.enableVideoReceive(true);
```

The use case is an "audio only" call that will allow screen sharing during the call. Everyone in the call should be able to receive video once someone shares the screen. 

If Chrome joins after Firefox it works, if Firefox joins as a second participant it fails.

**Comment by hthetiot** [comment]
@fbernhard Will look at it, I may had a support request from that issue.

**Comment by fbernhard** [comment]
@hthetiot Let me know if I can help debugging.

**Comment by hthetiot** [comment]
Tested version 1.0.16 with Firefox 45 and Chrome 48.
