### ISSUE TITLE
Implement ORTC prototype

### ISSUE THREAD

**Issue by hthetiot** [priologic/easyrtc#161]
We have a prototype in development of ORTC using easyrtc.
I will make a push request once we have something.

Meanwhile feel free to be the first to push in this issue.

I will update the issue with doc and link later on.
Let make easyrtc have ortc support quickly :)

**Comment by hthetiot** [comment]
Ms will provide a update on adapter.js
https://dev.modern.ie/testdrive/demos/simplewebrtc/

Note:
- would be nice to no have regression like the chrome regexp issue on iOS

**Comment by dryswabbie** [comment]
I've been keeping an eye out for progress on the ORTC Working group's shim repo, but no work has progressed there yet. It has been mentioned in the ORTC meetings and mailing list that work would be progressing on that front soon.

 - https://github.com/openpeer/ortc-js-shim

Microsoft seems to be using the 'bundle-edge/js' from a feature branch in SimpleWebrtc (not a shim, support is baked in):

 - https://github.com/andyet/SimpleWebRTC/blob/localstorage-fix/bundle-edge.js

Though the progress has been slow, I am quite interested in the improved processes and interfaces the ORTC group are trying to bring to WebRTC.

**Comment by hthetiot** [comment]
@dryswabbie Not real interest anymore feel free to close.
