### ISSUE TITLE
Create Room event not being fired

### ISSUE THREAD

**Issue by dryswabbie** [priologic/easyrtc#162]
As referenced by Hugo St-Onge in the following EasyRTC forum post, the Create Room event isn't properly firing.

 - https://groups.google.com/forum/#!topic/easyrtc/WTQzHaDFYXo

I've verified this. It appears the event was created but not properly implemented. This should be a quick fix.

**Comment by dryswabbie** [comment]
Should be fixed and tested with a few scenarios. Report back any problems!

Fix is written so event is fired in four possible circumstances:

1. Event fires during application init and if 'roomDefaultEnable' option is true.
2. During client authentication, a list of initial rooms may be requested. Event fires If any requested rooms are not present. Requires 'roomAutoCreateEnable' option to be true.
3. During client initiated 'roomJoin' procedure. and if room is not present. Requires 'roomAutoCreateEnable' option to be true.
4. Application writer explicitly emits the event in server side code using easyrtc.events.emit("roomCreate", ...)

To create a room explicitly without firing the event, the appObj.createRoom() method is the way to go.

**Comment by hstonge** [comment]
Sorry for the delay, back from the week-end ! I'll test it right away!

**Comment by hstonge** [comment]
I've tested for the specific case that concerns me (point 2) and it's all looking good in the _beta_ branch.

Thanks @dryswabbie !

**Comment by dryswabbie** [comment]
Good to hear its working.

As for the ETA on getting it into a release... generally we let the changes bake in the beta for a bit and try to release every few months (unless there's a P1 bug). It does look like we're due soon though.
