### ISSUE TITLE
Patch for depreciated MediaStream APIs

### ISSUE THREAD

**Issue by fbernhard** [priologic/easyrtc#165]
Hi all,

Some MediaStream APIs are depreciated in Chrome and will be removed in M47 and will fail starting from November:

https://developers.google.com/web/updates/2015/07/mediastream-deprecations

Below a patch (against current beta) to replace the old APIs with the new ones. May be a good idea to push it to master too?

```
1714,1719c1714,1723
<             try {
<                 namedLocalMediaStreams[streamName].stop();
<             } catch (err) {
<                 // not worth reporting an error at this location
<                 // since we didn't want the media stream anyhow.
<             }
---
>             var tracks = namedLocalMediaStreams[streamName].getTracks();
> 			  tracks.forEach(function(track) {
> 				try {
> 					track.stop();
> 				}
> 				catch (err) {
> 					// not worth reporting an error at this location
> 					// since we didn't want the media stream anyhow.
> 				}
> 			  });
3263c3267
<                     if( !remoteStreams[i].ended ) {
---
>                 	  if ( remoteStreams[i].active ) {
4167,4170c4171,4178
<                         try {
<                             remoteStreams[i].stop();
<                         } catch (err) {
<                         }
---
>                         var tracks = remoteStreams[i].getTracks();
> 						  tracks.forEach(function(track) {
> 							try {
> 								track.stop();
> 							}
> 							catch (err) {
> 							}
> 						  });
```

**Comment by fbernhard** [comment]
Oops, reported in #163 already ...

**Comment by EricDavies** [comment]
Just pushed your changes. Let me know if you see any problems with it.

**Comment by hthetiot** [comment]
@EricDavies I also had to fix some bug since Chrome M47 where MediaStream.hasOwnProperty("id") return false now, also noticed that before on Firefox.

It may can be also caused by easyrtc creating or changing the property on the object making hasOwnProperty return false has expected.
I did not experimented the issue using the default stream but named multistream only and not auto iniMedia.

Here is the quick patch for reference.
https://github.com/hthetiot/easyrtc/commit/d7022955d216e1ce6c019742fedc00591caf7398

**Comment by EricDavies** [comment]
sorry Harold, you are quite right. I didn't read your message closely
enough and assumed it was something else. I've push applied your fix to
beta. Rod and I will push beta to master in the near future.
Weird how the mediastreams object can have an hasOwnProperty method that
doesn't recognize the id property. I think that counts as a chrome bug.

**Comment by hthetiot** [comment]
Yeah I noticed that on Firefox long time ago.

Here is a simple test to confirm

> window.navigator.webkitGetUserMedia(
         {
            video:true,
            audio:false
         },
         function(stream) { console.log(stream.hasOwnProperty('id'),
stream.id); },
         function(error) { /* do something */ }
      );

On 14 October 2015 at 10:54, Eric Davies <notifications@github.com> wrote:

> sorry Harold, you are quite right. I didn't read your message closely
> enough and assumed it was something else. I've push applied your fix to
> beta. Rod and I will push beta to master in the near future.
> Weird how the mediastreams object can have an hasOwnProperty method that
> doesn't recognize the id property. I think that counts as a chrome bug.
>
> On Wed, Oct 14, 2015 at 12:30 AM, Harold Thétiot <notifications@github.com
> >
> wrote:
>
> > @EricDavies <https://github.com/EricDavies> I also had to fix some bug
> > since Chrome M47 where MediaStream.hasOwnProperty("id") return false now,
> > also noticed that before on Firefox.
> >
> > It may can be also caused by easyrtc creating or changing the property on
> > the object making hasOwnProperty return false has expected.
> > I did not experimented the issue using the default stream but named
> > multistream only and not auto iniMedia.
> >
> > Here is the quick patch for reference.
> > hthetiot@d702295
> > <
> https://github.com/hthetiot/easyrtc/commit/d7022955d216e1ce6c019742fedc00591caf7398
> >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/priologic/easyrtc/issues/165#issuecomment-147962007
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/priologic/easyrtc/issues/165#issuecomment-148135260>.
>



-- 
Harold Thétiot.
