### ISSUE TITLE
loss of options due to passing null to socket.io connect()

### ISSUE THREAD

**Issue by rretter** [priologic/easyrtc#166]
Line 4464 of easyrtc,js (in routine <code>connectToWSServer()</code> in case your version doesn't match line numbers exactly) is:
<code>              self.webSocket = io.connect(serverPath, connectionOptions);</code>

And when run, the value of <code>serverPath</code> is often <code>null</code> (since user app probably hasn't called easyrtc's <code>setSocketUrl()</code> routine).  But if you actually step into the socket.io code, you'll find yourself in their <code>lookup(uri, opts)</code> routine, which tries to accommodate having been passed only a single parameter.  It then interprets that "single" parameter as being the options object.  Unfortunately, the way they detect a single param is arguably wrong.  They test <code>typeof uri == 'object'</code> <i>which is <b>true</b> for null in JavaScript</i>.

The upshot is, when you pass the uri as <code>null</code>, that <code>null</code> gets used as the value for the connection options.  So even when the connection succeeds, it does so without the options you intended.

I recognize this is arguably a bug in socket.io, and perhaps not in easyrtc.  But I believe you're better off rewriting your call to <code>io.connect()</code> so it just doesn't pass the <code>null</code> value.  The JavaScript <code>undefined</code> value is a better choice, and it won't provoke the "bug" in socket.io.

**Comment by hthetiot** [comment]
@rretter I will investigate your report soon.

**Comment by hthetiot** [comment]
@rretter Still alive ? Have you tried new master 1.0.17 or beta yet ?
