### ISSUE TITLE
JSHint on easyrtc_int.js

### ISSUE THREAD

**Issue by hthetiot** [priologic/easyrtc#169]
Checking the JS logs in prod I found a couples of undefined vars in easyrtc.js, most of them in error cases.

So instead of fixing only one, I just made a JSHint pass fixed some others and added globals from Adapter.js and WebRTC for better insights on integration with requirejs using easyrtc_int.js with deps adapter.js, io.js and easyrtc_lang_en.js.

I will also do it on easyrtc_ft.js in a separate push.

**Comment by hthetiot** [comment]
@EricDavies I Added comment "Undefined var" on commit for "easyrtc.js" 5 in totals.
Let me know if i should rebuild when i do push or not ?

**Comment by EricDavies** [comment]
I just looked at them. The undefined vars are definitely worth pushing, but
I'll accept the rest with them. It will need to be applied to the beta
branch of course.
Thank you.

**Comment by hthetiot** [comment]
@EricDavies So many new duplicate issue and push request could be resolved only from this one, only,
If you FXXKING MERGE! What are you waiting for guys exactly to process your github contributor to FIX real proven issues.
