### ISSUE TITLE
socket.io connecting to wrong port

### ISSUE THREAD

**Issue by WolfieZero** [priologic/easyrtc#170]
Tried setting up a demo conference using the [tutorial given](https://github.com/priologic/easyrtc/blob/master/docs/easyrtc_client_tutorial.md#video-conferencing---easy-side-up) but I'm running into issue where as I'm running the server on one port (`9000`) and the front-end on another (`8080`), the request to socket.io is going to the wrong port (this case `http://localhost:8080/socket.io/1/` where it should his `http://localhost:9000/socket.io/1/`).

Reporting it here as I'm not sure who is responsible for checking the port number, easyrtc or socket.io, but as this is the first port-of-call as it where I thought I'll try here.

Thanks.

**Comment by EricDavies** [comment]
Handled. See https://easyrtc.com/docs/guides/easyrtc_with_other_servers.php
