### ISSUE TITLE
Firefox and previous WebRTC impl does not call emitOnStreamClosed

### ISSUE THREAD

**Issue by hthetiot** [priologic/easyrtc#173]
On Firefox 44.0a2 (2015-11-07) calling easyrtc.hangup if not calling emitOnStreamClosed cause firefox is still using MediaStream.ended instead of MediaStream.active.  I created a wrapper isStreamActive() that test the both like we had for stopStream() and also added to stopStream() MediaStream.stop freature detection and call.

**Comment by hthetiot** [comment]
@EricDavies "Dont Break the Web", If adaper.js does cover that we will have to. There will be instance of WebRTC with MediaStream.ended for a while I think not to mention plugin or ios ;)

**Comment by EricDavies** [comment]
Just pushed in to beta branch. Thank you.
