### ISSUE TITLE
RoomJoin with parameters may fail with autoCreateRoom

### ISSUE THREAD

**Issue by dryswabbie** [priologic/easyrtc#174]
As reported in our forum, a problem can occur during the following circumstance:

1. Server must have roomAutoCreateEnable option set as true (this is the default)
2. Application must be utilizing custom roomParameters
3. Client must attempt to join a non-existing room
4. Room Join command must be made after authentication (room joined at the same time as authentication are handled differently)

The roomJoin will fail for the given user and an error will be logged:

    2015-11-03T18:28:22.547Z - error   - EasyRTC: Error setting option. Unrecognised option name 'user'.

There is some more history within the following forum thread:

 - https://easyrtc.com/forums/viewthread/14/

**Comment by hthetiot** [comment]
Already on master in previous release.
Will close then, feel free to reopen if I'm wrong.
