### ISSUE TITLE
Error in connecting from Android Chrome Client

### ISSUE THREAD

**Issue by nhanndt** [priologic/easyrtc#175]
Hi everyone,
I tried to download easyRTC source code from
https://easyrtc.com/download/
and follow the instruction to install and make a testing page for the case Simple Video+Audio in the link:
http://175.209.8.238:8080/demos/demo_audio_video_simple.html
After running the server, I try to connect as a client from different desktop web browsers. Everything works fine. But when i tried to connect from Chrome in Android via LTE network, we got unexpected result in which user cannot watch camera video each other.
However, when i used the same android phone to connect to easyRTC demo page: 
https://demo.easyrtc.com/demos/demo_audio_video_simple.html
everything goes well.
What is the different between my server and easyRTC demo page server?

**Comment by EricDavies** [comment]
Http versus https, most likely, and maybe the version of chrome.

As a recent security feature, chrome doesn't share the camera unless the
page is coming from https or localhost.

**Comment by nhanndt** [comment]
Hi EriDavies! Thank you for your answer. I'm gonna change into https soon to test it again. It sounds reasonable. i wonder if there is anything wrong in my server settings? I did the configuration like this: 
option.appIceServers = [      
    {url: "stun:stun.l.google.com:19302"},
    {url: "stun:stun.sipgate.net"},
    {url: "stun:217.10.68.152"},
    {url: "stun:stun.sipgate.net:10000"},
    {url: "stun:217.10.68.152:10000"}
];
Do you have any idea?

**Comment by EricDavies** [comment]
Your ice server settings look fine to me.

**Comment by hthetiot** [comment]
@nhanndt If you get black screen that generally a TURN or STUN issue or if you are an Android depend the Webview/Browser that you are using.
