### ISSUE TITLE
I got given error (uncaughtException: pub.httpApp.get is not a function) on node version 4.0.0 for easyrtc.

### ISSUE THREAD

**Issue by Raju-Kshirsagar** [priologic/easyrtc#180]
> 2015-12-07T09:32:04.905Z - error: uncaughtException: pub.httpApp.get is not a function date=Mon Dec 07 2015 15:02:04 GMT+0530 (IST), pid=6722, uid=1001, gid=1001,
> rss=181133312, heapTotal=101284352, heapUsed=76021416, loadavg=[1.16162109375, 1.1572265625, 1.146484375], uptime=19359, trace=[column=29, file=/usr/local/lib/node_modules/easyrtc/lib/easyrtc_default_event_listeners.js, function=null, line=1509, method=null, native=false, column=34, file=/usr/local/lib/node_modules/easyrtc/node_modules/async/lib/async.js, function=fn, line=582, method=null, native=false, column=34, file=/usr/local/lib/node_modules/easyrtc/node_modules/async/lib/async.js, function=Immediate._onImmediate, line=498, method=_onImmediate, native=false, column=17, file=timers.js, function=processImmediate [as _immediateCallback], line=371, method=null, native=false], stack=[TypeError: pub.httpApp.get is not a function,     at /usr/local/lib/node_modules/easyrtc/lib/easyrtc_default_event_listeners.js:1509:29,     at fn (/usr/local/lib/node_modules/easyrtc/node_modules/async/lib/async.js:582:34),     at Immediate._onImmediate (/usr/local/lib/node_modules/easyrtc/node_modules/async/lib/async.js:498:34),     at processImmediate [as _immediateCallback](timers.js:371:17)]

**Comment by wess** [comment]
:+1:

**Comment by hthetiot** [comment]
@Raju-Kshirsagar @wess What would be the path for fix ?

**Comment by hthetiot** [comment]
"pub.httpApp" is first arg of "easyrtc.listen" could be an issue with express 4 if not properly setup but should not be an issue from the lib itself.

**Comment by hthetiot** [comment]
https://github.com/priologic/easyrtc/blob/master/server_example/package.json#L14
