### ISSUE TITLE
ERROR: Required modules are not installed. Run 'npm install' from command line.

### ISSUE THREAD

**Issue by webstudiopro** [priologic/easyrtc#181]
After I run sudo npm install in easyrtc/server_example and running the server I got
ERROR: Missing module 'async'
ERROR: Missing module 'colors'
ERROR: Missing module 'underscore'
ERROR: Required modules are not installed. Run 'npm install' from command line.

I tried to install the packages seperate but without success. Even with -g flag, --save, --save-dev ...
Problem rise on Ubuntu 14LTS and windows 10
Node v0.12.7
npm 2.11.3

Please help !
thx
Fret Benny
http://www.webstudiopro.be

**Comment by EricDavies** [comment]
1) did it actually install the apparently missing modules? Ie, what do you
see if you do a  "ls -l node_modules"
2) did you use a sudo to run the server?

**Comment by yzk0281** [comment]
same  problem， and I ran 'ls -l node_modules':
drwxr-xr-x 4 500 root 4096 Dec 29 15:26 async
drwxr-xr-x 5 500 root 4096 Dec 29 15:26 colors
drwxr-xr-x 9 500 root 4096 Dec 29 15:26 easyrtc
drwxr-xr-x 4 500 root 4096 Dec 29 15:26 express
drwxr-xr-x 5 500 root 4096 Dec 29 15:26 socket.io
drwxr-xr-x 2 500 root 4096 Dec 29 15:27 underscore

but when I try to ran 'node server.js',  still the same problem.

**Comment by EricDavies** [comment]
this is probably a stupid question, but just to rule out the really inane:
  what directory do you have the server.js and node_modules directory in,
  what is your current directory when you run "node server.js"

**Comment by yzk0281** [comment]
all  in  'server_example'

**Comment by yzk0281** [comment]
oops, 'npm install' should be ran at the top director also.

**Comment by jbnunn** [comment]
Same problem as OP, fix (from @yzk0281) is to run `npm install` in top level folder.

**Comment by hthetiot** [comment]
That normal behavior.
1. Lib require only it's own modules deps.
2. Sample require express and other modules deps.

May be better docs can help to avoid this recurrent issue.

**Comment by hthetiot** [comment]
> Installation In A Nutshell
--------------------------
 1. Install [Node.js](http://nodejs.org)
 2. Download files from [server_example/](./server_example/) and place them in a local folder of your choice.
    - [package.json](./server_example/package.json)
    - [server.js](./server_example/server.js)
    - OR [download and extract this .zip](http://easyrtc.com/files/easyrtc_server_example.zip)
 3. Run `npm install` from the installation folder to install dependent packages (including EasyRTC)
 4. Start EasyRTC by running `node server.js`
 5. Browse the examples using a WebRTC enabled browser. *(defaults to port `8080`)*

**Comment by finetype** [comment]
There goes an hour of my life. Please let's update the docs...

**Comment by hthetiot** [comment]
@finetype Can you make a proposal for something ?

**Comment by suculent** [comment]
Add a 'cd server_example' step between 3 and 4 and you're good to go.

**Comment by serj-by** [comment]
It's quite unclear from documentation that you should run "npm install" from root of the project but "node server.js" from server_example folder. I think it should be stated more clear since as I see not only me running "npm install" from server_example folder. Just my penny.

**Comment by macbroadcast** [comment]
2018 still not fixed in the doc, but great that google found this thread  👍
