### ISSUE TITLE
Bug in the funccion setOnStreamClosed when calling idToName

### ISSUE THREAD

**Issue by seis6seis** [priologic/easyrtc#182]
If within setOnStreamClosed need to check the idToName , this is completely different from the ID you use to create , in other works proper activation functions except this .

**Comment by EricDavies** [comment]
You'll need to provide explanation on how to reproduce this error.
To try this out, I modified the demo_audio_video.js file with the following changes (in bold)
function connect() {
  **easyrtc.setUsername("user" + new Date().getTime() % 1000);**
  easyrtc.enableAudio(document.getElementById("shareAudio").checked);
  easyrtc.enableVideo(document.getElementById("shareVideo").checked);
  easyrtc.enableDataChannels(true);
  easyrtc.setRoomOccupantListener( convertListToButtons);
  easyrtc.connect("easyrtc.audioVideo", loginSuccess, loginFailure);             
}

easyrtc.setOnStreamClosed( function (easyrtcid) {
   ** var name = easyrtc.idToName(easyrtcid);
    console.log("name is " + name);**
    easyrtc.setVideoObjectSrc(document.getElementById('callerVideo'), "");
    disable("hangupButton");
});

The name appeared when I closed the connection on the remote peer.

**Comment by hthetiot** [comment]
@seis6seis We cannot fix if we cannot repro, will leave open for now.
