### ISSUE TITLE
Separate EasyrtcID From Socket.io

### ISSUE THREAD

**Issue by dryswabbie** [priologic/easyrtc#185]
The latest versions of socket.io changed their socket id naming convention to include several additional characters (including #, and /). This broke the regex for expected EasyRTC ID's.

Rather than change the regex, which could break existing apps, I'd like to generate our own EasyRTC ID's. This will also ease a future transition for allowing alternate transports.

This issue was discussed in our forum at:

 - https://easyrtc.com/forums/viewthread/60/

**Comment by hthetiot** [comment]
@dryswabbie Really nice. 
Reviewed and did not see particular issue.

**Comment by hthetiot** [comment]
@dryswabbie did you try that yet using socket.io 1.4.5 ? Do you want me to setup a test branch for that feature or you think it can be merge. 

It would be a major milestone.

**Comment by dryswabbie** [comment]
I updated out demo.easyrtc.com server to use the beta branch alongside the latest production versions of express and socket.io. So far the fix seems to work well, and I think it's good to go.

**Comment by ben-pr-p** [comment]
👍

Having to use the 0.19.16/7 version of the socket.io server and client is annoying.

**Comment by hthetiot** [comment]
@ben-pr-p master branch should support socket.io ^1.3.7

I will merge @dryswabbie work into the up-comming release. See roadmap.

- https://github.com/priologic/easyrtc/blob/master/server_example/package.json

**Comment by ben-pr-p** [comment]
Is the current master branch the one published on npm?

**Comment by hthetiot** [comment]
The npmjs.org package is linked to @dryswabbie.
I just sent him a request to link it on this repo instead.

Meanwhile you can install that version that is this official one via:

> npm install git+https://github.com/priologic/easyrtc

**Comment by hthetiot** [comment]
Tested socket 1.5 with success, I will do a separate push for deps update.
