### ISSUE TITLE
wrong condition expression in buildLocalMediaStream 

### ISSUE THREAD

**Issue by omochi** [priologic/easyrtc#189]
I might found a bug at
https://github.com/priologic/easyrtc/blob/6e01d41fc2d885a10d9d2933ddb8720780c03398/api/easyrtc.js#L1910

Current code is this.

```
                 if( remoteStreams && remoteStreams.length > 1 ) {
```

I think that this is correct.

```
                 if( remoteStreams && remoteStreams.length > 0 ) {
```

**Comment by hthetiot** [comment]
@omochi That weird that it works before... Will keep an eye on regression for that one.
