### ISSUE TITLE
Possible undefined getUserMedia

### ISSUE THREAD

**Issue by hthetiot** [priologic/easyrtc#194]
When packing/minifying easyrtc I got an having it into a closure "(function (){ ... }())" because the polyfill is doing "var getUserMedia" but only define "window.getUserMedia" and later "supportsGetUserMedia" only use "getUserMedia" but not "window.getUserMedia".

**Comment by hthetiot** [comment]
should not append in beta branch due new adaper.js from @EricDavies

**Comment by hthetiot** [comment]
@omochi What do you think we should do for "getUserMedia" vs "AMD" vs "window.navigator.getUserMedia" in easyrtc_int.js ?

Me, I think, now we should do "window.navigator.getUserMedia" and let polyfill with Adapter for people that don't want to have to deal with that.

cc @EricDavies

**Comment by omochi** [comment]
@hthetiot 

Embedding other library into some library is generally bad idea.
It makes hard to keep tracking latest and stable version.
It causes conflition between same libraries included in other libraries.

`webrtc/adapter` is updating actively, and
Webbrowsers webrtc supporting status is also dynamically chainging recently.
So we need to keep using version as much as later.

Using other library without standard way sometime causes troubles.
This issue too.

This change have some impact to existing code,
But do correct thing early is better than lately.

It is also known that this is technically possible by this work.
https://github.com/priologic/easyrtc/pull/115

Necessity removing extension methods such like `easyApp()` 
is not exists for almost user.

The only need is keep code clean to be easy to understand that 
they are extension.

So I approve these.

- Splitting adapter.js and easyrtc body
- Combine easyrtc.js and easyrtc_int.js into one.
- Adaptting AMD and common-js dual style packaging. 

Sorry If I write unrelated something.
I am not familier with english.
And, I dont understand about `easyrtc_ft.js` .

**Comment by hthetiot** [comment]
Ok let do that for next release 1.0.17 and do simple stuff for 1.0.16.

**Comment by hthetiot** [comment]
@omochi We should be good with dirty getUserMedia in easyrt.js from adapter.js until next release.
If you are no ok with that re-open the issue.

cc @EricDavies
