### ISSUE TITLE
Using undefined variable `callFailureCB` in onChannelCmd

### ISSUE THREAD

**Issue by omochi** [priologic/easyrtc#197]
A variable here is not defined in this scope.

https://github.com/priologic/easyrtc/blob/6e01d41fc2d885a10d9d2933ddb8720780c03398/api/easyrtc.js#L4480

This line may be copied from here.

https://github.com/priologic/easyrtc/blob/6e01d41fc2d885a10d9d2933ddb8720780c03398/api/easyrtc.js#L3163

**Comment by hthetiot** [comment]
fixed but not merged by @EricDavies 
- b90625329f8ac02e2421b2c5a73fba718b81e573
- See JSLINT #169

@omochi Please review and push for merge.

**Comment by omochi** [comment]
@hthetiot Wao! Your works looks great. I will review after returning home.
