### ISSUE TITLE
wrong property access of message object for type "error" in onChannelCmd

### ISSUE THREAD

**Issue by omochi** [priologic/easyrtc#199]
Current Code is 

```
case "error":
  self.showError(msg.errorCode, msg.errorText);
```

at https://github.com/priologic/easyrtc/blob/6e01d41fc2d885a10d9d2933ddb8720780c03398/api/easyrtc.js#L4647

It may be wrong .

Correct code may be

```
case "error":
  self.showError(msgData.errorCode, msgData.errorText);
```

I am not sure.
Because I could not find sender code of this message type `error`.

**Comment by hthetiot** [comment]
Let try your fix and see, I will do QA anyway on push before merge.
