### ISSUE TITLE
bug for `deleted` in `findDeltas`

### ISSUE THREAD

**Issue by omochi** [priologic/easyrtc#201]
Current code is here.

```
deleted = oldVersion[i];
```

https://github.com/priologic/easyrtc/blob/6e01d41fc2d885a10d9d2933ddb8720780c03398/api/easyrtc.js#L4804

I think this is mistake of this.

```
deleted[i] = oldVersion[i];
```

**Comment by hthetiot** [comment]
@omochi you want me to do separate pull request or you are fine if I fix and continue to push  same pull request and review like that?

P.S Thanks for great reporting.

**Comment by omochi** [comment]
@hthetiot I am ok both. Please take which is easy for you.

**Comment by hthetiot** [comment]
Ok let push on the same for all the client api issue you found.
Will update push request with issues refs.

**Comment by omochi** [comment]
@hthetiot okey
