### ISSUE TITLE
undefined socket.io method `close`

### ISSUE THREAD

**Issue by omochi** [priologic/easyrtc#209]
socket.close() is called at 
https://github.com/priologic/easyrtc/blob/master/api/easyrtc.js#L2709

but close is not defined in v0.9.17
https://github.com/socketio/socket.io/blob/0.9.17/lib/socket.js#L290

According to this issue 
https://github.com/priologic/easyrtc/issues/184
I referred 0.9.17

v1.4.5 does not have this too.
https://github.com/socketio/socket.io/blob/1.4.5/lib/socket.js

Do I overlook something?

**Comment by omochi** [comment]
sorry I looked server side one.

Client side v0.9.17 does not have `close` too.
https://github.com/socketio/socket.io-client/blob/0.9.17/lib/socket.js#L339

v1.4.15 have `close`
https://github.com/socketio/socket.io-client/blob/1.4.5/lib/socket.js#L383

**Comment by hthetiot** [comment]
@omochi  Me I'm using socket.io 1.3.7:
- https://github.com/socketio/socket.io-client/blob/1.3.7/lib/socket.js#L370

May be we should update package.json socket.io dep version.

**Comment by hthetiot** [comment]
@omochi tell me what you think about that fix

**Comment by omochi** [comment]
@hthetiot 
oh... I see.
Of course v1.3.7 is better than v0.9.7.
v0 series are too old. There is no needs to support it.
