### ISSUE TITLE
Moar Jslint

### ISSUE THREAD

**Issue by hthetiot** [priologic/easyrtc#210]
Can you review @omochi  Full jslint no logic change

d974b0fd62fc67bc028ccf4ec23e93a5454e246c
88908aee55e66f503cd2e0b9d00a3a802496bd49

Unfortunately github do not show the full diff.

Now
> 0 error

Before

> api/adapter.js: line 1159, col 34, Empty block.
api/adapter.js: line 1702, col 10, 'requestUserMedia' was used before it was defined.
api/adapter.js: line 928, col 35, 'RTCSessionDescription' is not defined.
api/adapter.js: line 932, col 36, 'RTCSessionDescription' is not defined.
api/adapter.js: line 1572, col 22, 'RTCSessionDescription' is not defined.
api/adapter.js: line 1602, col 22, 'RTCSessionDescription' is not defined.

> api/easy_app.js: line 338, col 10, Unnecessary semicolon.
api/easy_app.js: line 9, col 5, 'easyrtc' is not defined.
api/easy_app.js: line 80, col 13, 'easyrtc' is not defined.
api/easy_app.js: line 87, col 13, 'easyrtc' is not defined.
api/easy_app.js: line 99, col 9, 'easyrtc' is not defined.
api/easy_app.js: line 105, col 22, 'easyrtc' is not defined.
api/easy_app.js: line 125, col 9, 'easyrtc' is not defined.
api/easy_app.js: line 141, col 9, 'easyrtc' is not defined.
api/easy_app.js: line 145, col 9, 'easyrtc' is not defined.
api/easy_app.js: line 153, col 9, 'easyrtc' is not defined.
api/easy_app.js: line 156, col 21, 'easyrtc' is not defined.
api/easy_app.js: line 163, col 9, 'easyrtc' is not defined.
api/easy_app.js: line 181, col 9, 'easyrtc' is not defined.
api/easy_app.js: line 193, col 9, 'easyrtc' is not defined.
api/easy_app.js: line 195, col 17, 'easyrtc' is not defined.
api/easy_app.js: line 196, col 17, 'easyrtc' is not defined.
api/easy_app.js: line 228, col 17, 'easyrtc' is not defined.
api/easy_app.js: line 248, col 25, 'easyrtc' is not defined.
api/easy_app.js: line 262, col 13, 'easyrtc' is not defined.
api/easy_app.js: line 294, col 5, 'easyrtc' is not defined.
api/easy_app.js: line 301, col 9, 'easyrtc' is not defined.
api/easy_app.js: line 308, col 9, 'easyrtc' is not defined.
api/easy_app.js: line 310, col 20, 'easyrtc' is not defined.
api/easy_app.js: line 310, col 64, 'easyrtc' is not defined.
api/easy_app.js: line 311, col 21, 'easyrtc' is not defined.
api/easy_app.js: line 329, col 9, 'easyrtc' is not defined.
api/easy_app.js: line 337, col 21, 'easyrtc' is not defined.
api/easy_app.js: line 345, col 17, 'easyrtc' is not defined.
api/easy_app.js: line 345, col 84, 'easyrtc' is not defined.
api/easy_app.js: line 352, col 31, 'easyrtc' is not defined.
api/easy_app.js: line 355, col 21, 'easyrtc' is not defined.
api/easy_app.js: line 355, col 39, 'easyrtc' is not defined.
api/easy_app.js: line 359, col 13, 'easyrtc' is not defined.
api/easy_app.js: line 362, col 22, 'easyrtc' is not defined.
api/easy_app.js: line 367, col 13, 'easyrtc' is not defined.
api/easy_app.js: line 374, col 39, 'easyrtc' is not defined.
api/easy_app.js: line 377, col 29, 'easyrtc' is not defined.
api/easy_app.js: line 377, col 47, 'easyrtc' is not defined.
api/easy_app.js: line 39, col 17, 'self' is not defined.
api/easy_app.js: line 39, col 32, 'self' is not defined.
api/easy_app.js: line 49, col 21, 'self' is not defined.
api/easy_app.js: line 49, col 36, 'self' is not defined.

> api/easyrtc_ft.js: line 66, col 13, Expected '{' and instead saw 'e'.
api/easyrtc_ft.js: line 86, col 9, 'dropCueClass' was used before it was defined.
api/easyrtc_ft.js: line 130, col 14, 'addClass' was used before it was defined.
api/easyrtc_ft.js: line 145, col 14, 'removeClass' was used before it was defined.
api/easyrtc_ft.js: line 223, col 13, Expected '{' and instead saw 'return'.
api/easyrtc_ft.js: line 234, col 13, Expected '{' and instead saw 'return'.
api/easyrtc_ft.js: line 271, col 14, 'sendChunk' was used before it was defined.
api/easyrtc_ft.js: line 359, col 14, 'sendFilesWaiting' was used before it was defined.
api/easyrtc_ft.js: line 370, col 14, 'sendFilesOffer' was used before it was defined.
api/easyrtc_ft.js: line 426, col 14, Creating global 'for' variable. Should be 'for (var destUser ...'.
api/easyrtc_ft.js: line 426, col 9, The body of a for in should be wrapped in an if statement to filter unwanted properties from the prototype.
api/easyrtc_ft.js: line 565, col 13, Bad line breaking before '||'.
api/easyrtc_ft.js: line 566, col 13, Bad line breaking before '||'.
api/easyrtc_ft.js: line 571, col 17, Comma warnings can be turned off with 'laxcomma'.
api/easyrtc_ft.js: line 569, col 28, Bad line breaking before ','.
api/easyrtc_ft.js: line 573, col 9, Bad line breaking before ','.
api/easyrtc_ft.js: line 574, col 47, Bad line breaking before ','.
api/easyrtc_ft.js: line 575, col 86, Bad line breaking before ','.
api/easyrtc_ft.js: line 576, col 75, Bad line breaking before ','.
api/easyrtc_ft.js: line 580, col 61, Bad line breaking before ','.
api/easyrtc_ft.js: line 584, col 9, Bad line breaking before ','.
api/easyrtc_ft.js: line 585, col 32, Bad line breaking before ','.
api/easyrtc_ft.js: line 586, col 76, Bad line breaking before ','.
api/easyrtc_ft.js: line 591, col 9, Bad line breaking before ','.
api/easyrtc_ft.js: line 592, col 33, Bad line breaking before ','.
api/easyrtc_ft.js: line 593, col 33, Bad line breaking before ','.
api/easyrtc_ft.js: line 594, col 37, Bad line breaking before ','.
api/easyrtc_ft.js: line 606, col 9, Bad line breaking before ','.
api/easyrtc_ft.js: line 620, col 9, Bad line breaking before ','.
api/easyrtc_ft.js: line 624, col 33, Bad line breaking before ','.
api/easyrtc_ft.js: line 625, col 35, Bad line breaking before ','.
api/easyrtc_ft.js: line 626, col 38, Bad line breaking before ','.
api/easyrtc_ft.js: line 627, col 23, Bad line breaking before ','.
api/easyrtc_ft.js: line 628, col 23, Bad line breaking before ','.
api/easyrtc_ft.js: line 633, col 13, Bad line breaking before ','.
api/easyrtc_ft.js: line 636, col 13, Bad line breaking before ','.
api/easyrtc_ft.js: line 650, col 13, Bad line breaking before ','.
api/easyrtc_ft.js: line 660, col 13, Bad line breaking before ','.
api/easyrtc_ft.js: line 661, col 68, Bad line breaking before ','.
api/easyrtc_ft.js: line 741, col 9, Bad line breaking before ','.
api/easyrtc_ft.js: line 742, col 32, Bad line breaking before ','.
api/easyrtc_ft.js: line 211, col 13, 'easyrtc' is not defined.
api/easyrtc_ft.js: line 217, col 5, 'easyrtc' is not defined.
api/easyrtc_ft.js: line 263, col 5, 'easyrtc' is not defined.
api/easyrtc_ft.js: line 264, col 5, 'easyrtc' is not defined.
api/easyrtc_ft.js: line 265, col 5, 'easyrtc' is not defined.
api/easyrtc_ft.js: line 266, col 5, 'easyrtc' is not defined.
api/easyrtc_ft.js: line 275, col 17, 'easyrtc' is not defined.
api/easyrtc_ft.js: line 287, col 17, 'easyrtc' is not defined.
api/easyrtc_ft.js: line 296, col 13, 'easyrtc' is not defined.
api/easyrtc_ft.js: line 330, col 21, 'easyrtc' is not defined.
api/easyrtc_ft.js: line 334, col 21, 'easyrtc' is not defined.
api/easyrtc_ft.js: line 384, col 13, 'easyrtc' is not defined.
api/easyrtc_ft.js: line 434, col 17, 'easyrtc' is not defined.
api/easyrtc_ft.js: line 440, col 5, 'easyrtc' is not defined.
api/easyrtc_ft.js: line 462, col 17, 'easyrtc' is not defined.
api/easyrtc_ft.js: line 465, col 17, 'easyrtc' is not defined.
api/easyrtc_ft.js: line 532, col 17, 'easyrtc' is not defined.
api/easyrtc_ft.js: line 540, col 5, 'easyrtc' is not defined.
api/easyrtc_ft.js: line 541, col 5, 'easyrtc' is not defined.
api/easyrtc_ft.js: line 426, col 14, 'destUser' is not defined.
api/easyrtc_ft.js: line 429, col 41, 'destUser' is not defined.
api/easyrtc_ft.js: line 435, col 26, 'destUser' is not defined.
api/easyrtc_ft.js: line 436, col 36, 'destUser' is not defined.

> api/easyrtc_int.js: line 156, col 6, Missing semicolon.
api/easyrtc_int.js: line 1261, col 14, '_enqueueSendRoomApi' was used before it was defined.
api/easyrtc_int.js: line 1279, col 14, '_sendRoomApiFields' was used before it was defined.
api/easyrtc_int.js: line 1840, col 13, The body of a for in should be wrapped in an if statement to filter unwanted properties from the prototype.
api/easyrtc_int.js: line 2693, col 14, 'sendSignalling' was used before it was defined.
api/easyrtc_int.js: line 3146, col 14, 'callBody' was used before it was defined.
api/easyrtc_int.js: line 3198, col 15, 'isStreamActive' is already defined.
api/easyrtc_int.js: line 3459, col 14, 'onRemoveStreamHelper' was used before it was defined.
api/easyrtc_int.js: line 3475, col 9, The body of a for in should be wrapped in an if statement to filter unwanted properties from the prototype.
api/easyrtc_int.js: line 3493, col 9, 'buildPeerConnection' was used before it was defined.
api/easyrtc_int.js: line 3932, col 29, Empty block.
api/easyrtc_int.js: line 3979, col 9, 'doAnswer' was used before it was defined.
api/easyrtc_int.js: line 4009, col 9, 'doAnswerBody' was used before it was defined.
api/easyrtc_int.js: line 4099, col 14, 'emitOnStreamClosed' was used before it was defined.
api/easyrtc_int.js: line 4163, col 9, 'clearQueuedMessages' was used before it was defined.
api/easyrtc_int.js: line 4310, col 14, 'sendQueuedCandidates' was used before it was defined.
api/easyrtc_int.js: line 4800, col 14, 'updateConfiguration' was used before it was defined.
api/easyrtc_int.js: line 4869, col 14, 'processSessionData' was used before it was defined.
api/easyrtc_int.js: line 4881, col 14, 'processRoomData' was used before it was defined.
api/easyrtc_int.js: line 4999, col 14, 'processIceConfig' was used before it was defined.
api/easyrtc_int.js: line 5017, col 71, Expected '===' and instead saw '=='.
api/easyrtc_int.js: line 5024, col 17, 'item' is already defined.
api/easyrtc_int.js: line 5094, col 14, 'sendAuthenticate' was used before it was defined.
api/easyrtc_int.js: line 5201, col 9, 'preallocatedSocketIo' was used before it was defined.
api/easyrtc_int.js: line 408, col 16, 'webrtcUtils' is not defined.
api/easyrtc_int.js: line 762, col 17, 'webrtcUtils' is not defined.
api/easyrtc_int.js: line 1010, col 25, 'webrtcUtils' is not defined.
api/easyrtc_int.js: line 2070, col 13, 'webrtcUtils' is not defined.
api/easyrtc_int.js: line 2085, col 17, 'webrtcUtils' is not defined.
api/easyrtc_int.js: line 2109, col 17, 'webrtcUtils' is not defined.
api/easyrtc_int.js: line 2278, col 13, 'webrtcUtils' is not defined.
api/easyrtc_int.js: line 2802, col 17, 'webrtcUtils' is not defined.
api/easyrtc_int.js: line 3341, col 13, 'webrtcUtils' is not defined.
api/easyrtc_int.js: line 3344, col 13, 'webrtcUtils' is not defined.
api/easyrtc_int.js: line 3417, col 17, 'webrtcUtils' is not defined.
api/easyrtc_int.js: line 3476, col 13, 'webrtcUtils' is not defined.
api/easyrtc_int.js: line 3488, col 13, 'webrtcUtils' is not defined.
api/easyrtc_int.js: line 3533, col 25, 'webrtcUtils' is not defined.
api/easyrtc_int.js: line 3746, col 21, 'webrtcUtils' is not defined.
api/easyrtc_int.js: line 3796, col 37, 'webrtcUtils' is not defined.
api/easyrtc_int.js: line 3800, col 37, 'webrtcUtils' is not defined.
api/easyrtc_int.js: line 3804, col 37, 'webrtcUtils' is not defined.
api/easyrtc_int.js: line 3808, col 37, 'webrtcUtils' is not defined.
api/easyrtc_int.js: line 3821, col 37, 'webrtcUtils' is not defined.
api/easyrtc_int.js: line 3825, col 37, 'webrtcUtils' is not defined.
api/easyrtc_int.js: line 3829, col 37, 'webrtcUtils' is not defined.
api/easyrtc_int.js: line 3836, col 41, 'webrtcUtils' is not defined.
api/easyrtc_int.js: line 3842, col 33, 'webrtcUtils' is not defined.
api/easyrtc_int.js: line 3952, col 21, 'webrtcUtils' is not defined.
api/easyrtc_int.js: line 4088, col 13, 'webrtcUtils' is not defined.
api/easyrtc_int.js: line 4346, col 17, 'webrtcUtils' is not defined.
api/easyrtc_int.js: line 4538, col 22, 'webrtcUtils' is not defined.
api/easyrtc_int.js: line 4541, col 17, 'webrtcUtils' is not defined.
api/easyrtc_int.js: line 4643, col 13, 'webrtcUtils' is not defined.
api/easyrtc_int.js: line 3558, col 27, 'easyrtc' is not defined.
api/easyrtc_int.js: line 3559, col 27, 'easyrtc' is not defined.
api/easyrtc_int.js: line 3565, col 27, 'easyrtc' is not defined.
api/easyrtc_int.js: line 3566, col 27, 'easyrtc' is not defined.
api/easyrtc_int.js: line 3572, col 56, 'easyrtc' is not defined.
api/easyrtc_int.js: line 3573, col 25, 'easyrtc' is not defined.

> 273 errors

**Comment by hthetiot** [comment]
@omochi I will merge on push 1.0.16 only once review in case of.

**Comment by hthetiot** [comment]
most of it was re-ordering and comments and style but will checkout for regression, should be fine.

**Comment by hthetiot** [comment]
Made QA on it and works as intended no regression, will make a separate push after first push for 0.0.16 merged.

**Comment by hthetiot** [comment]
e8fb3ff7ca65a54563f7a3bf4f06523f3124864d

**Comment by omochi** [comment]
I checked d974b0f.
I found one bug. Details are in line comment.

```
+        var FS_proto = FileSaver.prototype = saveAs;
```

**Comment by omochi** [comment]
I checked 88908ae. no problem.

**Comment by hthetiot** [comment]
Ok fixed your review and merged in #198
