### ISSUE TITLE
Problem with webrtc call initialization

### ISSUE THREAD

**Issue by MariasStory** [priologic/easyrtc#212]
Hi,

There should be a problem with webrtc call initialization. I see double webrtc connections indicated by "chrome://webrtc-internals/". The firs has empty parameters:
1) https://demo.easyrtc.com/demos/demo_multistream.html, { servers: [], iceTransportType: all, bundlePolicy: balanced, rtcpMuxPolicy: negotiate }, {advanced: [{}]}

This does not happen with another webrtc solutions.

 At this moment I do not have time to hunt for the reasons for this. Can someone explain (fix) the situation?

Greetings,
Tolik

**Comment by hthetiot** [comment]
Thanks for report @MariasStory I will investigate.
Could also be an issue in the demo.

**Comment by MariasStory** [comment]
Hi Harold. I would not bet on the demo problem. I am seeing it in my app for some time. :-)

**Comment by MariasStory** [comment]
OK. I think that I've got it.

The problem is in the function:
this.supportsPeerConnections = function() {
---------------------------------
        try {
            self.createRTCPeerConnection({"iceServers": []}, null); //-------------This is it!-----------
        } catch (oops) {
            return false;
        }
---------------------------------

The question is: What to do with it?

**Comment by hthetiot** [comment]
Let me know if that suit your for now.

**Comment by hthetiot** [comment]
I literally removed that test cause we expect adaper.js to expose RTCPeerConnection if possible only.

**Comment by MariasStory** [comment]
OK. This will do.
Thanks
