### ISSUE TITLE
Error messages Failed to get access to local media. Error code was PermissionDeniedError

### ISSUE THREAD

**Issue by sutrisna** [priologic/easyrtc#220]
Running using localhost:8080 its not problem but when i running using ip wifi like 192.168.0.xx:8080 not working.
error message : 
Error messages Failed to get access to local media. Error code was PermissionDeniedError

How to fix this ?
need help ?

**Comment by mvkarthikeyan** [comment]
chrome needs https  to use get user media . this may work on firefox 
i got this log 
"getUserMedia() no longer works on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details. "

**Comment by sutrisna** [comment]
Okay, thank you for this information.

On Wed, May 4, 2016 at 2:20 PM, M.V.Karthikeyan <notifications@github.com>
wrote:

> chrome needs https to use get user media . this may work on firefox
> i got this log
> "getUserMedia() no longer works on insecure origins. To use this feature,
> you should consider switching your application to a secure origin, such as
> HTTPS. See https://goo.gl/rStTGz for more details. "
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/priologic/easyrtc/issues/220#issuecomment-216764326>
>



-- 

Sutrisna | 089-6604-70957
Junior Programming
http://sutrisna.github.io/

**Comment by hthetiot** [comment]
Thx for Support @mvkarthikeyan

**Comment by sii1995** [comment]
How can I use https + easyRTC???

**Comment by EricDavies** [comment]
You have two options:
1) Make node serve ssl. See https://github.com/priologic/easyrtc/blob/master/docs/easyrtc_server_ssl.md for details. This approach is fine for development but a bit slow for production and on a unix box, you have to do some tricks to access a low numbered port (like run as root, or something more clever).
2) Have your node server on a high numbered port like 8080 as usual, and use haproxy (or nginx) to handle the encryption/decryption while forwarding stuff from your ssl port (typically 443) to port 8080.

**Comment by sii1995** [comment]
Thank You very so much, Your first option is worked. I generated self-signed certificate by openssl and use Code from option 1...

**Comment by ramgarden** [comment]
I'm serving on a windows machine so my options are limited.  I did get it working though by using greenlock-express library for my node.js express server to serve up over https.  Now it works!

**Comment by zanyarhasani** [comment]
hi thanks for information's 
i use greenlock-express.js and show https on my browser but this error: 
Failed to get access to local media. Error code was NotReadableError.
