### ISSUE TITLE
Add option for VP9.

### ISSUE THREAD

**Issue by MariasStory** [priologic/easyrtc#221]
Please add option for VP9 codec.

**Comment by hthetiot** [comment]
For reference:

- Google VP9 SDP info:
https://developers.google.com/web/updates/2016/01/vp9-webrtc?hl=en

- EasyRTC custom SDP:
https://github.com/priologic/easyrtc/blob/master/api/labs/easyrtc_rates.js

**Comment by MariasStory** [comment]
This is what is used by muaz-khan : 
https://github.com/muaz-khan/WebRTC-Experiment/blob/17d7f530cde5319b210f42a79b9bbeb665916980/Chrome-Extensions/desktopCapture-p2p/CodecsHandler.js

    function preferVP9(sdp) {
        if (sdp.indexOf('SAVPF 100 101') === -1 || sdp.indexOf('VP9/90000') === -1) {
            return sdp;
        }

        return sdp.replace('SAVPF 100 101', 'SAVPF 101 100');
    }

You can also check removeVPX function and another tricks in:
https://github.com/muaz-khan/WebRTC-Experiment/blob/17d7f530cde5319b210f42a79b9bbeb665916980/RTCMultiConnection/dev/CodecsHandler.js

More universal solution is in apprtc:
https://github.com/webrtc/apprtc/blob/be5b67b5ba43c1adb1d518bad8cec8a672cfef84/src/web_app/js/sdputils.js

functions maybePreferCodec and setDefaultCodec.

Maybe it makes sense to port this approach?

**Comment by hthetiot** [comment]
@MariasStory Thanks will look into that and keep you posted.

**Comment by MariasStory** [comment]
Ping 1

**Comment by EricDavies** [comment]
Good things come to those who wait, but not wait too long :-).

I've just implemented this in the api/labs/easyrtc_rates.js file in the beta branch.
I was able to verify it worked by changing the demos/js/demo_lowbandwidth.js connect function to:
function connect() {
    var localFilter = easyrtc.buildLocalSdpFilter( {
        audioRecvBitrate:20, videoRecvBitrate:30 **,videoRecvCodec:"vp9"**
    });
    var remoteFilter = easyrtc.buildRemoteSdpFilter({
        audioSendBitrate: 20, videoSendBitrate:30 **,videoSendCodec:"vp9"**
    });
    easyrtc.setSdpFilters(localFilter, remoteFilter);
    easyrtc.setRoomOccupantListener(convertListToButtons);
    easyrtc.easyApp("easyrtc.lowbandwidth", "selfVideo", ["callerVideo"], loginSuccess, loginFailure);
 }

Checking the offer and answer sdp's, I could see that the order changed from 100,101, to 101,100 and that webrtc-internals says that VP9 is being used.

**Comment by hthetiot** [comment]
a04a38430df70755460aa99fe0b5c399377372a0

**Comment by hthetiot** [comment]
@MariasStory closing for now.
I will test later, feel free to re-open.
