### ISSUE TITLE
Connections are not closed properly.

### ISSUE THREAD

**Issue by MariasStory** [priologic/easyrtc#225]
1) Open chrome://webrtc-internals/ = 0 connections
2) Open https://demo.easyrtc.com/demos/demo_audio_video_simple.html
3) Open in new tab https://demo.easyrtc.com/demos/demo_audio_video_simple.html
4) Connect one tab to another.
5) Check chrome://webrtc-internals/ = 4 connections (should be 2 - fixed)
6) Close one of the tabs.
7) Check chrome://webrtc-internals/ = 2 connections (should be 0)

You will have 2 more connection for every new connect/disconnect pair.

**Comment by hthetiot** [comment]
@MariasStory Did you experience that on the #beta branch also look duplicate to #212 for me.

**Comment by MariasStory** [comment]
@hthetiot I have seen it for some time now on different versions of Chrome.

The only relation to the issue #212 is in the number of connections. This why I wrote "fixed".

The situation that there is a remaining stream after remote connection is closed, is something new.

**Comment by hthetiot** [comment]
@MariasStory Will investigate later.

**Comment by hthetiot** [comment]
@MariasStory I think the issue was from the previous easyrtc.supportsStatistics that was creating a RTCPeerConnection but was not closing it.

See fix cd99ea8cc8178160c70d3e07af8aecdd5ece84ab
You can check the branch beta to test that issue for regression.

**Comment by MariasStory** [comment]
Hi @hthetiot sorry to inform, but the problem persists with beta version.

Basically, if a partner connection is closed, the webrtc connection remain in chrome://webrtc-internals/

Maybe, there should be some additional disconnection procedure initiated.

**Comment by EricDavies** [comment]
Try the same test with google's appspot.apprtc.com .
I think you'll see the same behavior.
We noticed this in the early days, that connection information hangs around until the tab itself is closed. I figured it was so they could get statistics still, after a call was over.

**Comment by MariasStory** [comment]
Hi Eric,

I could not try with apprtc so I went for https://rtcmulticonnection.herokuapp.com/demos/Audio+Video+TextChat+FileSharing.html

It works like this:
1) Open one tab and "Open Room"
2) Open a new tab and "Join Room" with the same ID
3) Open  chrome://webrtc-internals/ and see 2 connections
4) Reload one of the tabs and join the same room
5) Observe 2 connections in internals

I am on win8, so I just checked this with EasyRtc beta and got 3 connections shown.

Maybe "muaz-khan" does something different?

Thanks for you hard work,
Tolik

**Comment by EricDavies** [comment]
I just tried your steps. After step 4, I saw 3 connections with https://rtcmulticonnection.herokuapp.com/demos/Audio+Video+TextChat+FileSharing.html
identical to what I saw with easyrtc.
After repeating step 4 a bunch of times, I had a bunch of stale connections showing up in the chrome://webrtc-internals.
My guess is that you reloaded both tabs, not just one of them.

**Comment by MariasStory** [comment]
Thanks Eric,

Fair enough.

Maybe, I have done something wrong and it is a feature from Chrome.

Thanks for help,
Tolik
