### ISSUE TITLE
Multiple Stream not always connecting?

### ISSUE THREAD

**Issue by renebrain** [priologic/easyrtc#228]
Hey guys,

we successfully implemented easyRTC for peer to peer videoconferencing, by using the easyApp example. Conferencing from one client to the other client is not a problem but when we start extending this to more than 2 users it gets problematic. What we experienced is that when a new user joins the conference sometimes the calling goes wrong. Sometimes it fails to call one of the participating clients or lets one stream of one of the other clients freeze. There is also a similar behaviour in the mutlistream demo (https://demo.easyrtc.com/demos/demo_multistream.html). As soon a third client joins the room it gets messy. So my question is now, is it a wrong implementation from our clientside? (I posted a small piece of code) Is it a known issue of webRTC standard/easyRTC library? Or is it something, that needs to be changed on server side? Can anyone help me?

Thank you :)

```javascript 
var roomListener = function (roomName, otherPeers) {
                    //somecode to determine which peers need to be called
                    for (i = 0; i < newPeersLength; i++) {
                        var newPeer = newPeers[i];
                        if (self.peer && (newPeer != self.peer))
                                self.performCall(newPeer);
                    } 
                    //somecode to finish
            };
```

**Comment by renebrain** [comment]
I found the issue. The participants where trying to call each other at the same time, no i added some checks for that, and it runs smooth now.

**Comment by jahirbsetec** [comment]
Hi renebrain, I have the same issue like you mentioned, Please post the checks you have added to make it run smoothly. I really appreciate your help

**Comment by renebrain** [comment]
I need to check the code when i am back at work, the only thing i can say now, you might want to check, that the joining member is not trying to call himself. That might stop him to continue starting the calls to the others. But i am not quite sure right now. I will let you know, when i checked my code.

**Comment by hthetiot** [comment]
@renebrain 

> easyrtc.setRoomOccupantListener(function (roomName, newRoomUsers, newUser) {
...
  newRoomUsers.forEach(function (newRoomUser) {
.. 
if (newUser.roomJoinTime < newRoomUser.roomJoinTime) {
easyrtc.call(newRoomUser. easyrtcid, ...
}

**Comment by renebrain** [comment]
I took an aextract out of my code which works, so i am checking quite a few times which users i have already called and maintaing a list on my side for that. I hope it helps you. It looks kinda messy, but thats the best i can provide you. I haven't worked on it for quite a few weeks now :D

```javascript
            var roomListener = function (roomName, otherPeers) {
                var peers = [];
                var i;
                var j;
                for (i in otherPeers) {
                    if(otherPeers.hasOwnProperty(i))
                        peers.push(otherPeers[i].easyrtcid);
                }
                if (callback) { //internal checking mechnism, just see this thing as true for now)
                    if (!peers.length) {
                        self.closeStreamCall();
                    } else {
                        $("#establishing-connection, #calling").removeClass("nowVisible");
                    }
                    if(initializing){
                        var participants = self.participants;
                        var newPeers = utilitiesController.findNewElementsInArray(peers, participants);
                        var newPeersLength = newPeers.length;
                        var oldPeers = utilitiesController.findNewElementsInArray(participants, peers);
                        for (i = 0; i < newPeersLength; i++) {
                            var newPeer = newPeers[i];
                            if (self.peer && (newPeer != self.peer))
                                self.performCall(newPeer);
                        }
                        participants = utilitiesController.addElementsToArray(participants, newPeers);
                        self.participants = utilitiesController.removeElementsFromArray(participants, oldPeers);
                        initializing=false;
                    }
//some other stuff which is not related to this problem
```

**Comment by hthetiot** [comment]
@renebrain For now I never had this issue. I will check a the demo code later.
Still adding some delay and making the right call mesh is still required.
Finally not to mention ICE exchange and TURN/STUN.

**Comment by cristianocca** [comment]
When using the long way (manual calls and connect rather than easyApp), I faced similar issues, since clients were trying to call each other all the time, so I basically maintain two dictionaries, one for already connected and another one for pending connects, plus an additional flag similar to the "isNewcomer" so the first time the room listener is fired it doesn't call anyone but instead the other members call him. The dictionaries are checked before calling and updated on the call callbacks. With these it seems that multi party videos never fail, probably they could still fail if they join at the exact same time and some race condition happens but I think this quite good.

**Comment by hthetiot** [comment]
In order to call incoming user in the room in the case of more that I recommend doing this, hope that help.

var enableAutoCall = true,
    isRoomMostRecentUser = user.roomJoinTime > localUser.roomJoinTime;

```
// If user is owner and has media then call new user
if (
    // Auto call new user
    enableAutoCall &&
    // Was there before new user
    isRoomMostRecentUser && 
    // Is sharing media
    (
        supportsGetUserMedia && (
            isSharingCamera ||
                isSharingAudio ||
                    isSharingScreen
        )
    )
) {

    easyrtc.call(peerEasyrtcId, ...);
}
```
