### ISSUE TITLE
Easy RTC video call  not working in some specific networks.

### ISSUE THREAD

**Issue by ShadananaK** [priologic/easyrtc#229]
Dear Team,

I have been using Easyrtc since one and half year. The video call mechanism its woks fine within LAN and also works fine in the geographically two different place in two different network, **depending on network  used.**

But some time it wont work when particular network used like internet dongle or some thing else like 4G wifi devices(in specific networks).

Demo hosted in Easyrtc official sights works fine.But when i use the one hosted in my own server in cloud,it wont work.

I have set all stun and turn configurations properly.

Please help me to debug this issue,its very urgent.

Thank you in advance.

Regards,
Shadanana

**Comment by EricDavies** [comment]
I've just written a short  document on debugging easyrtc issues. You can find it at https://github.com/priologic/easyrtc/blob/beta/docs/easyrtc_debugging.md

If that doesn't solve your problems, re-open this issue.

**Comment by ShadananaK** [comment]
Thank you for the replay.I will check and revert back.

**Comment by ShadananaK** [comment]
Thank you  **EricDavies**  for your valuable  advice. It solved my issue.Thank you very much.
