### ISSUE TITLE
Use of Deprecated API !

### ISSUE THREAD

**Issue by indrajitsinh** [priologic/easyrtc#230]
Node Version:  4.4.5
EasyRTC Server:  v1.0.15
Browser: Firefox 47.0.1 
OS : OS X EI Capitan 10.11.4

navigator.mozGetUserMedia has been replaced by navigator.mediaDevices.getUserMedia

17:52:02.926 WebRTC interfaces with the "moz" prefix (mozRTCPeerConnection, mozRTCSessionDescription, mozRTCIceCandidate) have been deprecated.1 easyrtc.js:907:19

17:52:02.932 RTCIceServer.url is deprecated! Use urls instead.1 (unknown)

17:52:02.935 onaddstream is deprecated! Use peerConnection.ontrack instead.1 (unknown)

17:52:03.068 Mandatory/optional in createOffer options no longer works! Use {"offerToReceiveAudio":true,"offerToReceiveVideo":true} instead (note the case difference)!1 (unknown)

does this project is actively maintained ? last commit was 8 months ago !

**Comment by EricDavies** [comment]
Try the beta branch. Its been updated more recently by community members. We need to merge it into the master branch very soon.
