### ISSUE TITLE
DOMException: The play() request was interrupted by a new load request.

### ISSUE THREAD

**Issue by ShadananaK** [priologic/easyrtc#231]
Hi team,

When i use  Easyrtc in video call application.I am encountering following error in google chrome Version 51.0.2704.103 m.

> easyrtc.js:1851 Uncaught (in promise) DOMException: The play() request was interrupted by a new load request.
> Easyrtc.clearMediaStream @ easyrtc.js:1851
> Easyrtc.setVideoObjectSrc @ easyrtc.js:1876
> tryToGetSize @ easyrtc.js:2104

The webcam will switch on but i wont get capturing video in the web browser.

The issue repeats in Mozilla Firefox also.

Please help me to solve this issue.

Regards,
Shadanana

**Comment by EricDavies** [comment]
You need to tell us how to reproduce this problem.

**Comment by fbernhard** [comment]
Maybe this fixes it? It pauses an existing stream before clearing it.

``` javascript
    this.clearMediaStream = function(element) {
    	var clear = function() {
    		if (typeof element.src !== 'undefined') {
	            // noinspection JSUndefinedPropertyAssignment
	            element.src = "";
	        } else if (typeof element.srcObject !== 'undefined') {
	            element.srcObject = "";
	        } else if (typeof element.mozSrcObject !== 'undefined') {
	            element.mozSrcObject = null;
	        }
    	}
    	if (element && element.pause) {
    		element.pause();
    		clear();
    	}
    	else {
    		clear();
    	}
    };
```

**Comment by maximemeri** [comment]
I am getting the same issue.
I perform a call to another user with an accept checker, and cancel the call with a hangup before this other user accept the call. Then when i call him again and this time accept the call on the other side, I get no video and this error displayed in the console. Changing the clearMediaStream above doesn't fix the issue.

Am I doing the call cancel wrong ?

**Comment by hthetiot** [comment]
@maximemeri @fbeauchamp @ShadananaK 

Check that branch and let me know then I merge.
- https://github.com/hthetiot/easyrtc/tree/issue-231
