### ISSUE TITLE
Publish beta v1.0.16 on master

### ISSUE THREAD

**Issue by hthetiot** [priologic/easyrtc#233]
Publish beta v1.0.16 on master.
@EricDavies Can you merge beta on master, I think it is pretty stable.
Once you did that I would merge #224 on beta.

**Comment by EricDavies** [comment]
I've merged beta into master. 
It went in as version 1.0.17 (because I didn't clue in on time that you'd updated the version number already).

**Comment by hthetiot** [comment]
@EricDavies ok I renamed 1.0.16 to 1.0.17 milestones.
I will now merge 1.0.17 push request.
