### ISSUE TITLE
Grunt support and new beta build

### ISSUE THREAD

**Issue by hthetiot** [priologic/easyrtc#235]
I just merged my push request on beta has 1.0.18-beta.

Detailed features:
- UMD support for easyrtc
- build via gunt+ requirejs (uglify later)
- lint (css/html/js) via grunt+csslint+jshint htmlhint
- basic unit test env for api via grunt+karma+jasmine
- generated doc via grunt+jsdoc
- deprecated message on previous build scripts

@EricDavies Can you test the new beta branch on your side to start to see if there is issue or breaking changes.

**Comment by EricDavies** [comment]
@hthetiot, I will test.

**Comment by hthetiot** [comment]
@EricDavies Closing because I think we used it both of us.
Let re-open only of regression append.
