### ISSUE TITLE
adapter.js uses deprecated API for getUserMedia

### ISSUE THREAD

**Issue by EricDavies** [priologic/easyrtc#237]
If you run any of the audio/video demos on Firefox, you'll get the message:
navigator.mozGetUserMedia has been replaced by navigator.mediaDevices.getUserMedia

**Comment by hthetiot** [comment]
Has a warning or error ?
If it's a warning we could just invite it and wait for adapter to update I believe.
I will investigate ASAP.

**Comment by EricDavies** [comment]
It's just a warning at this point.

**Comment by hthetiot** [comment]
I believe they webrtc adapter keepto use mozGetUserMedia when available on adapter making FF do the warning.
- https://github.com/webrtc/adapter/blob/master/src/js/firefox/getusermedia.js#L89

**Comment by EricDavies** [comment]
Not exactly sure what you are saying below.

**Comment by hthetiot** [comment]
I have updated my comment, I'm keeping an eye on the webrtc-adapter repo and will update regularly.
I think this is a good thing they still use moz prefix for now. There is probably some old Firefox that still rely on the prefixed version.

**Comment by EricDavies** [comment]
Firefox automatically updates itself like Chrome right? Ever-green. It 
would have to be a firefox that predated evergreen.

**Comment by hthetiot** [comment]
I think we are good on that we use 'navigator.getUserMedia' if the adapter.js has warning that could  be simply the way they implemented the polyfill on the given platform.
