### ISSUE TITLE
Create multiple instances under one single easyrtc server

### ISSUE THREAD

**Issue by nagarjunbn** [priologic/easyrtc#239]
Hi,
I just need a confirmation on the below question . 
The below chat is two years old .. 
https://groups.google.com/forum/#!topic/easyrtc/YDFswvRDAok

Is this functionality implemented in the latest available Master code ..?

Thanks ,

**Comment by nagarjunbn8** [comment]
@dryswabbie  Answer Please ..

**Comment by rzvavram** [comment]
Anything new?

**Comment by EricDavies** [comment]
Not on our (Rod,Eric,Priologic) side. It's not an interest/priority for us.
You might ask Harold if his companies C++ implementation of the EasyRTC server supports this.
