### ISSUE TITLE
try/catch block should be divided

### ISSUE THREAD

**Issue by ptinker56** [priologic/easyrtc#240]
When using easyrtc.senddatap2p, the function dataChannelMessageHandler is eventually called. Around line 3888 is this code block:
                      } else {
try {
var chunkedMsg = JSON.parse(pendingTransfer.chunks.join(''));
self.receivePeerDistribute(otherUser, chunkedMsg, null);
} catch (err) {
console.log('Developer error, unable to parse message');
}
                      }

As I learned the hard way, the error message could result either from a JSON.parse error (for which the error message is correct) or from something in the user callback.  It’s probably better to use two try blocks there to disambiguate the two causes of error.

**Comment by hthetiot** [comment]
@ptinker56 I will push a fix on branch beta.
Thanks for report and inputs.

**Comment by hthetiot** [comment]
@ptinker56 Review pls.

**Comment by hthetiot** [comment]
@ptinker56 I merged the pull request.
Re-open if regression or not satisfied.
