### ISSUE TITLE
peer scalability question

### ISSUE THREAD

**Issue by perfectwebtech** [priologic/easyrtc#242]
hello

it could be work like client to server ?  i have server 1gbps line 

as my local pc have 4mbps speed  and send stream to 1gbps cloud server and i did try webrtc and it's few users are ok but if few more try connect then getting slow and some users getting blank screen 

so here i can share my local pc to server and server share stream to other users as screen sharing features could be possible with 100 users ?

**Comment by hthetiot** [comment]
@perfectwebtech please write issue properly or go to the forum.
I changed the title that was meaning nothing.
