### ISSUE TITLE
Unable to start server sample via doc instructions in ubuntu 14.04

### ISSUE THREAD

**Issue by juanjosv** [priologic/easyrtc#249]
I followed the instructions from:
https://github.com/priologic/easyrtc/blob/master/docs/easyrtc_server_install.md

But when i try to start the server with node server.js, this error appears:

module.js:457
    throw err;
    ^

Error: Cannot find module '../'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/nodes/server_example/server.js:6:15)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)

How can i solve it?

**Comment by juanjosv** [comment]
Found this, but still not solved:
https://easyrtc.com/forums/viewthread/271/

**Comment by EricDavies** [comment]
git clone the easyrtc distribution
do a "npm install" in the top level directory of the distribution.
cd into "server_example"
do a "npm install" in that directory.
do a "node server.js" in that directory.

The install documentation probably needs to be updated since some changes Harold applied.

**Comment by juanjosv** [comment]
Thanks Eric, works perfect!

**Comment by hthetiot** [comment]
@ericdavies we always had to do the "npm install" in server directory. Doc need update surely.

**Comment by EricDavies** [comment]
The docs definitely need update.

My phrasing is less accurate than I would desire. 
It used to be that you could do a single npm install in the server example directory and it would install everything (including easyrtc) beneath it. You now need to do two npm installs, but it makes use of the easyrtc distribution in the parent directory. For what it's worth, I think the new way you've got going is superior to the old way, particularly once we update the install doc :-).

**Comment by hthetiot** [comment]
@juanjosv @EricDavies Can you validate #250 push.
Feel free to suggest better instruction.
