### ISSUE TITLE
Check for Chrome browser incorrect

### ISSUE THREAD

**Issue by alangibson** [priologic/easyrtc#252]
The check for Chrome browser

`} else if (navigator.webkitGetUserMedia && window.webkitRTCPeerConnection && ! window.RTCPeerConnection) {`

in api/easyrtc.js is not correct, at least for version 'Version 52.0.2743.116 (64-bit).'

The workaround is to change this condition to 

`} else if (navigator.webkitGetUserMedia && window.webkitRTCPeerConnection) {`

I can submit a pull request if you'd like.

**Comment by hthetiot** [comment]
That like they on purpose to avoid getting webkitRTCPeerconnection that are already Polyfilled does it create an issue ?

**Comment by hthetiot** [comment]
@alangibson the beta branch is using adapter.js from branch and this change if still required is now on webrtc-adapter.js bower dep.
Easyrtc.js = adapter.js + easyrtc_int.js

**Comment by hthetiot** [comment]
@alangibson try beta branch and let me know pls
