### ISSUE TITLE
Firefox doesn't receive video from peer when it is the caller

### ISSUE THREAD

**Issue by cristianocca** [priologic/easyrtc#255]
Hello, I'm wondering if the following behaviour is a bug from firefox, easyRTC or myself.

If firefox calls with only audio enabled (no video media/stream requested) to a peer that is sharing video, firefox won't receive the peer's video data, only audio.
However, if it is the remote peer that starts the call, firefox correctly answers with audio only but is still able to receive video.

The issue doesn't seem to happen on chrome, regardless of who starts the call, chrome will always get video if one of the peers is sharing.

**Comment by cristianocca** [comment]
Not an issue on 1.0.17, seems like an issue only on the npm version.

**Comment by hthetiot** [comment]
@cristianocca yes npm version is not yet mapping this repo or beta branch.
