### ISSUE TITLE
Allow to get and set audiooutput

### ISSUE THREAD

**Issue by cristianocca** [priologic/easyrtc#256]
Looks like the method to get sources from webRTC also allows you to get audio output. Can this be added to the easyrtc api? Or is it not possible to set the actual audio output device?

**Comment by hthetiot** [comment]
@cristianocca can you provide API example url or reference.

**Comment by cristianocca** [comment]
@hthetiot 

Initially, it would be great to extend the api from the client easyrtc with an additional method just like getAudioSourceList and getVideoSourceList, something like:

`this.getAudioOutputSourceList = function(callback){
       getSourceList(callback, "audiooutput");
 };`

This would yield the output devices list, at least for chrome (doesn't return anything on firefox).

Then in order to allow using this output device, I believe again, only on chrome, it is possible to use this api on the video element: https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/setSinkId

I have managed to play sound with the selected output device with the above setSinkId method, sadly only on chrome.

Perhaps the easyrtc.setVideoObjectSrc method could be extended to include the output deviceId in order allow using different playback devices, in a way that will only work if the setSinkId function is defined on the html element object, and otherwise just ignore it, and eventually add this to browsers that support it.

**Comment by EricDavies** [comment]
I've just added this to the beta branch.
I've also modified the demo_audio_video demo so that it uses it. Once you connect to the server, 
it should populate some buttons underneath the videos so you can switch the audio sink of the callerVideo.

When I tried it, I got three labelled buttons 
     Default
     Built-in Audio Digital Stereo(HDMI)
     Built-in Audio Analog Stereo

The second monitor on my laptop is HDMI but doesn't have speakers. Sending the audio there muted the sound, selecting the Built-in Audio Analog Stereo unmuted it, suggesting that something was happening.  If you have multiple speaker systems, I'd curious to hear how well it worked. 
/**
     * Sets the audio output device of a Video object.
     * That is to say, this controls what speakers get the sound.
     * In theory, this works on Chrome but probably doesn't work anywhere else yet.
     * This code was cribbed from https://webrtc.github.io/samples/src/content/devices/multi/.
     *  @param {Object} element an HTML5 video element
     *  @param {String} sinkId a deviceid from getAudioSinkList
     */
    this.setAudioOutput = function(element, sinkId) ...

    /**
     * Gets a list of the available audio sinks (ie, speakers)
     * @param {Function} callback receives list of {deviceId:String, groupId:String, label:String, kind:"audio"}
     * @example  easyrtc.getAudioSinkList( function(list) {
     *               var i;
     *               for( i = 0; i < list.length; i++ ) {
     *                   console.log("label=" + list[i].label + ", id= " + list[i].deviceId);
     *               }
     *          });
     */
    this.getAudioSinkList = function(callback)...

**Comment by cristianocca** [comment]
Hello, thanks for adding this!
The test on my notebook worked fine with it connected through HDMI to a television, selecting HDMI would play sound on the TV, while selecting the other would play on the speaker or headphones (I pretty much had 3 different audio devices plugged and all worked).
For some reason though, there's one more device displayed on the list that would play no audio at all, but that might be just me not having anything connected to some special output I don't really know (one that has some red light)

I had this tested by other people as well and it seems to work fine on chrome. Hopefully something similar is added to other browsers since it is very common to have multiple devices and having the sound go through the wrong one is terrible!
