### ISSUE TITLE
Disable camera when not used.

### ISSUE THREAD

**Issue by MariasStory** [priologic/easyrtc#262]
Hi,

Please, consider the cool feature that is present in "meet.jit.si": The web camera is disabled when not used. I mean, it is switched off. This cool feature will give more trust from users.

Seems like they are using tracks like "addTrack". I was having some problems with this solution previously although it seems to work for them.

PS: Also the indication of the sound strength is a neat feature.

Thanks.

**Comment by EricDavies** [comment]
It really depends on what you mean by "when not used". If you mean it's not being displayed by the user or by any media streams, you already have the ability to close the local media stream at the application level, which will shut off that light.
If you mean when the camera is disabled, you want the video track removed from the media stream, and then added back in when the camera is renabled, that might complicate things as I believe that would fire a renegotiation event which would generate a new offer which in turn would be interpreted as being the start of sending an additional mediastream (which shouldn't cause a problem). But if the video track of the local media stream is disabled, it should be the browser telling the os that the camera isn't in use. How about suggesting it on the webrtc-discuss group (where the google/firefox developers read)?

**Comment by Garmichael** [comment]
> you already have the ability to close the local media stream at the application level

How is this done? I tried easyrtc.disconnect() with setVideoObjectSrc(element, '') and the light stays on.

**Comment by Leaninsider** [comment]
The easyrtc.js client class already supports this feature. You can toggle of the camera using the following piece of code easyrtc.enableCamera(enable, streamName). In case of disabling the camera the enable variable would be set to false. Take note that there also exists a similar easyrtc.enableMicrophone function.
