### ISSUE TITLE
incorrect/bad server install instructions

### ISSUE THREAD

**Issue by hedgerh** [priologic/easyrtc#263]
A user previously opened an issue https://github.com/priologic/easyrtc/issues/236 where they were getting the error `Error: Cannot find module '../'` when trying to run the server.  I also ran into this, but realized what is going wrong.

The instructions:

```
2. Create an EasyRTC application folder.
  * Note: Node is defaulted to browse to %HOMEDRIVE%%HOMEPATH%
  * ex: C:\Users\USERNAME\nodes\easyrtc

3. Download files from the server_example folder into your EasyRTC application folder.
  * OR download and extract this .zip
```

So the instructions tell you to create a folder, ex. `myApp`, then copy `server.js` and `package.json` from `server_example` into the root of `myApp`.

The problem is that `server.js` requires `easyrtc` via `var easyrtc = require('../')`, as if `myApp` is nested within the `easyrtc` module like `server_example` is in the repo.

The solution is to `npm install easyrtc` within `myApp` and then change the require to `var easyrtc = require('easyrtc')`.

ALSO, the zip file that is linked in the instructions, https://easyrtc.com/files/easyrtc_server_example.zip, no longer exists.

Let me know if it's alright for me to put in a PR to fix the instructions.

**Comment by hthetiot** [comment]
Documentation should be already fixed in beta branch see step with nom install in server_example.

See: https://github.com/priologic/easyrtc/blob/beta/docs/easyrtc_server_install.md#easyrtc-server-installation-1

**Comment by hthetiot** [comment]
Can you confirm @hedgerh instruction are ok on beta ?
Close the issue if it is the case pls.

See:
- https://github.com/priologic/easyrtc/blob/beta/docs/easyrtc_server_install.md#easyrtc-server-installation-1
