### ISSUE TITLE
Android - iOS sdk

### ISSUE THREAD

**Issue by ubuntutest** [priologic/easyrtc#269]
Where can I download the SDK for Android and ios? the site says page not found.

This project is still supported?

**Comment by EricDavies** [comment]
EasyRTC for Android got scrubbed. There shouldn't be any references to it on the current webpage. The demand for an android client (when you can run a web app on android) didn't justfify the amount of effort it took to maintain and support, particularly given that there were severe issues in the underlyling webrtc library at the time (1M memory leaks per peer connection).

With regards to iOS, contact info@priologic.com .

**Comment by hthetiot** [comment]
EasyRTC support many WebRTC iOS and Android implementation.
For reference Sylaps.com Apps on Android, iOS and Desktop use EasyRTC.

**Comment by hthetiot** [comment]
I don't believe EasyRTC need or should ever provide the layer above the JavaScript Client and Server Signaling their is plenty of good non-free or open-source solutions in the market that cover the Native WebRTC layer bridge that is needed to use EasyRTC.

**Comment by ubuntutest** [comment]
Thanks for the answer, I would like to ask you something.
I tried many solutions but no open-source WebRTC convinced me, I have problems in developing sdk ios.

I have a  turn server and a signaling server.
But I have seen that it is not the best solution, I could not configure a  ICE server, could you tell me how to do, or you could give me a guide? thank you.

I'd use in producing a solution like easyRTC
I would understand if i can install on my VPS an ICE server

**Comment by EricDavies** [comment]
Questions that aren't about bugs or feature requests should go to the google groups forum we have recently moved back to 
    https://groups.google.com/forum/?fromgroups#!forum/easyrtc

There is a guide for configuring ice servers (which means "turn" and "stun"). You can find it at 
https://github.com/priologic/easyrtc/blob/master/docs/easyrtc_server_ice.md
Beyond that, a lot depends on what turn service you are using. Note that there is a useful program in the demos directory demos/demo_ice_filter.html that helps with testing turn while only using a single work station.

Everybody thinks they need to do a web app at the same time they are doing mobile apps. The truth is, mobile apps are painfully harder than web apps; they take an order of magnitude more time when you throw in webrtc. My suggestion would be get your web app to work first, and then if it's achieving your goals, then think about adding a mobile app. There is no sense in investing time/money in mobile app development if the basic concept doesn't pan out.

**Comment by GiacomoSilli** [comment]
Hello,
Thanks for the link about ICE server, It is still not clear to me, now I try to set it up.
I'm using Coturn as turn servers, and Collider as signaling server.

I always build before the web app to do all the necessary tests, and then try to switch to the mobile app.

Thanks for the info, I will use this forum :)

**Comment by ubuntutest** [comment]
Hello,
Thanks for the link about ICE server, It is still not clear to me, now I try to set it up.
I'm using Coturn as turn servers, and Collider as signaling server.

I always build before the web app to do all the necessary tests, and then try to switch to the mobile app.

Thanks for the info, I will use this forum :)
