### ISSUE TITLE
Error in method processAddedTrack

### ISSUE THREAD

**Issue by desnoexa** [priologic/easyrtc#278]
Hello,

Could you tell me why in the method processAddedTrack, you call processAddedStream with 3 parameters while the signature of the method only has 2 parameters.

I think, the first parameter peerConn shouldn't be.
Do you confirm ?

Thanks

Xavier

**Comment by EricDavies** [comment]
That would be one of the fixes Harold was working on that was too late to get included in this release of the master branch. You can find Harold's newer version in the beta branch (which still looks suspect to me but I'll check that out with Harold).

**Comment by hthetiot** [comment]
Sorry my bad @desnoexa

**Comment by desnoexa** [comment]
It is still suspect to me either beacuase I don't understand why I still get 3 attributes in the method in the processAddedTrack super method.

**Comment by EricDavies** [comment]
@desnoexa : it's a bug that didn't get fixed in time to get into the master branch. In the beta branch it looks like:
         peerConn.trackTimers[streamId] = setTimeout(processAddedStream.**bind**(**null**, otherUser, peerStream), 100); // Bind peerStream
   the processAddedStream will only see the later two arguments because the bind will eat the first.

Or am I completely missing something (which happens on a regular basis :-).

**Comment by desnoexa** [comment]
No that's ok. Just that it is odd to me to have access to processAddedStream this way in this case and with only 2 parameters the other times...
But no big deal :)
