### ISSUE TITLE
adding additional stream to an existing peer connection generates an error from setRemoteDescription.

### ISSUE THREAD

**Issue by EricDavies** [priologic/easyrtc#285]
Looks like the google code has changed it's behavior.
    Object {errorCode: "INTERNAL_ERR", errorText: "set-remote-description: OperationError: Failed to …offer sdp: Called in wrong state: STATE_SENTOFFER"}
        errorCode:"INTERNAL_ERR"
        errorText:"set-remote-description: OperationError: Failed to set remote offer sdp: Called in wrong state: STATE_SENTOFFER"
        __proto__:Object

Demonstrable using the multstream demo. Doesn't see to break anything, just generate a nasty error message.

**Comment by hthetiot** [comment]
related #272

**Comment by EricDavies** [comment]
Fixed it. It became a bit more obvious when I looked the messaging.
