### ISSUE TITLE
funtion setuser("username") not work 

### ISSUE THREAD

**Issue by alefink** [priologic/easyrtc#291]
easyrtc.setDataChannelOpenListener(_openListener);
        easyrtc.setDataChannelCloseListener(_closeListener);
        easyrtc.setPeerListener(_addToConversation);
        easyrtc.setRoomOccupantListener(_convertListToButtons)
        **//not work this no set username;**
        **if( !easyrtc.setUsername("JohnSmith") )**{
            console.error("bad user name);
        }
        easyrtc.connect("easyrtc.dataMessaging", _loginSuccess, _loginFailure);
    };
  what is my errorr?

**Comment by EricDavies** [comment]
You can only successfully call setUsername before you connect.
You can't change it the middle of a session.
If you need something you can change, use  setRoomApiField/getRoomApiField.
