### ISSUE TITLE
Recent updates and AngularJS 2

### ISSUE THREAD

**Issue by markm1992** [priologic/easyrtc#293]
Hey everyone, I was just wondering if others had this problem. I have an angularJS 2 implementation of easyrtc and with recent updates everything breaks and for me it's impossible to get the code up and running. I can't even rewrite a simple demo with the most recent changes (or maybe second to most recent). I'm not able to provide specific examples at the moment because I deleted all of the work and just restored back to the old version, but I was wondering if anyone has worked with the most recent updates  and angular 2?

Sorry I added it here, I know it's wrong since it doesn't specifically say it supports angularjs, but since the forums are very very inactive, I thought my best shot was here.

Thanks for any help anyone has to offer, if not feel free to close this issue :)

**Comment by EricDavies** [comment]
Actually, the forums have been quite active lately. But there was a period where we were burning the midnight oil on another project and too busy to answer.

First I would suggest trying the beta branch since it always has the most recent fixes.

I believe we have a repository with an angular2 example in it. I'll try it out on the weekend.

**Comment by markm1992** [comment]
That's great to hear, I haven't looked at them in a couple months and remember the dead period, I'm glad it's active again! And amazing, I haven't seen a repo with angular2 but I will look for it if it's out there!

**Comment by EricDavies** [comment]
See https://easyrtc.com/blog/2016-11-23-easyrtc-typescript-support/

**Comment by markm1992** [comment]
Ahhh great! Yes they are in the Beta branch, thank you so much! This is exactly what is needed!
