### ISSUE TITLE
Camera/Microphone in use

### ISSUE THREAD

**Issue by markm1992** [priologic/easyrtc#294]
I noticed there isn't a way to detect if the camera or microphone is not in use. This leads my code to basically connect the users and then they stare at themselves and black screens with no video of each other. I haven't found a way around this and I'm not able to implement any fail safe yet to prevent this from happening. 

Is there a way around this that I just never found in easyrtc? Do we have some pre-camera/mic detection or is there some type of error that will be thrown?

Thanks!

**Comment by EricDavies** [comment]
I think what you are asking can be rephrased as "how do I tell if a mediastream contains audio and video tracks". The answer is the media stream has methods called   getAudioTracks() and getVideoTracks() which return arrays of mediaStreamTracks. Check the length of the returned array to see if it is zero.

**Comment by markm1992** [comment]
That's perfect and exactly what I needed, thank you so much!
