### ISSUE TITLE
Server method to obtain easyrtcids with a given username

### ISSUE THREAD

**Issue by dryswabbie** [priologic/easyrtc#302]
A method to obtain connected users with a given username would aid in a number of circumstances including handoff situations.

Looking to add the functions to the application object as usernames may not be unique across applications.

**Comment by dryswabbie** [comment]
Looking to implement it with a syncronouse method called getConnectedEasyrtcidsWithUsernameSync() which returns an array of easyrtcid strings. Will also implement it as a syncronous function which accepts a callback function.

**Comment by hthetiot** [comment]
Need to be secure to avoid easyrtc server instances users scan

**Comment by hthetiot** [comment]
Need to be implemented via custom `onConnection` instead.

- https://github.com/priologic/easyrtc/blob/master/lib/easyrtc_default_event_listeners.js#L37
