### ISSUE TITLE
UWP Support?

### ISSUE THREAD

**Issue by Natrium83** [priologic/easyrtc#305]
Any chance to get support for UWP together with the TypeScript support for some total cross platform integration in ionic 2?

https://github.com/webrtc-uwp/webrtc-uwp-sdk

**Comment by EricDavies** [comment]
Its nothing we got planned. We do have a consulting/contracting arm if you need it and have money, but as it stands, using cordova means less fuss with native libraries and is feature-full enough for most applications.
