### ISSUE TITLE
easyrtc.setAudioSource not working

### ISSUE THREAD

**Issue by ShadananaK** [priologic/easyrtc#308]
Hi team,

I tried setting easyrtc.setAudioSource( mic_id);  before calling easyrtc.initMediaSource as mentioned in document, But it has no effect. Its taking only default mic and its not changing at all.

The Microphone id's I am getting using easyrtc.getAudioSourceList() function  and i am using latest version of easyrtc.js.

`easyrtc.setVideoSource(camera_id);` - works absolutely fine.

`easyrtc.setAudioSource( mic_id);` - is not working.

Please help.

Regards,
Shadanana

**Comment by MariasStory** [comment]
Are you on Windows?

**Comment by ShadananaK** [comment]
Yes. windows 8.1 OS and chrome browser v57 i am using.

**Comment by EricDavies** [comment]
now fixed in zombieland branch.
