### ISSUE TITLE
Cannot find module '../'

### ISSUE THREAD

**Issue by colin-liu** [priologic/easyrtc#314]
I'm newbie, please give me solution, Thanks.
Here is error log.
```
➜  easyrtc node server.js
module.js:472
    throw err;
    ^

Error: Cannot find module '../'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/appteam/nodes/easyrtc/server.js:6:15)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**Comment by EricDavies** [comment]
the server.js file assumes that server.js file is in the server_example directory of the easyrtc directory.
Your error message is typical of somebody moving it else where, causing relative paths not to point where they should. Move it back where it was or change the relative paths to be consistent with your directory structure.

**Comment by colin-liu** [comment]
I'm not clear your solution, but I try to copy the easyrtc-master folder's all-files to nodes folder.
It works.

**Comment by andy-ata** [comment]
@EricDavies I am having same problems here and following what @colin-liu did for his to work isn't helping me as well. I need urgent help, my project is due in a week!

**Comment by cargallo** [comment]
Hi there! Too late for the answer but recently I came with the same problem. Like @EricDavies said, the example wich comes with the source code references easyrtc module like var easyrtc = require("../"); so you hace to change that to this var easyrtc = require("easyrtc");  and open a console in the server-example folder and put npm install --save easyrtc so it is included as a module in the project. This way you can move de server example folder without moving nothing else. Hope my english has been understandable enough

**Comment by ksac1** [comment]
Hi.

When I use: 
var oauthserver = require('../../');   

It gives an error:  Error: Cannot find module '../../' .

Can I get some help , please?
