### ISSUE TITLE
easy-rtc video features

### ISSUE THREAD

**Issue by abhishek123tanna** [priologic/easyrtc#316]
how to add features in video like..zoom,play,pause...etc...in easyrtc..???

**Comment by Jerczu** [comment]
There's no such thing in the webRTC as play and pause  you can control your stream the same way you control html5 video. The options available to you in a stream as per WebRTC spec are stop and enable (true/false). Its a real time stream unless you have a system that actively record the stream I don't think you can pause/resume it. Zoom well there is a way to play video stream through HTML5 canvas that potentially can give you the option to do so.

**Comment by hthetiot** [comment]
We could provide a WebGL/Canvas demo if that help.
But it's not easyrtc role to do that.
