### ISSUE TITLE
iOS 11 Safari

### ISSUE THREAD

**Issue by LukeStephen** [priologic/easyrtc#320]
Why doesn't this work on iOS 11 Safari that now supports WebRTC. Google's APPrtc demo site works on iOS 11 Safari now.

Are there hard-coded checks against a Safari browsers?

**Comment by EricDavies** [comment]
Good news.
See https://groups.google.com/forum/?fromgroups#!topic/easyrtc/Sj8mAuiwtQY

**Comment by fillybrese** [comment]
This is not a proper closing of an issue. The answer references a post from another forum discussion which is not a step-wise solution either. The solution, if it exists, should have been posted here, and then applied to the production branch. Don't mean to be harsh, but correct me if I'm understanding something incorrectly here.
