### ISSUE TITLE
Angular 2 Demo transpiles -  errors

### ISSUE THREAD

**Issue by ShadananaK** [priologic/easyrtc#321]
hi team ,

I have downloaded the beta version of easyrtc and try to run command "tsc" in the easyrtc/typescript_support/demo  directory. I am getting following errors 

'F:\typescript_support\demo>tsc
C:/Users/shadanana/AppData/Roaming/npm/node_modules/typescript/lib/lib.es6.d.ts(
21044,6): error TS2300: Duplicate identifier 'RTCBundlePolicy'.
C:/Users/shadanana/AppData/Roaming/npm/node_modules/typescript/lib/lib.es6.d.ts(
21050,6): error TS2300: Duplicate identifier 'RTCIceConnectionState'.
C:/Users/shadanana/AppData/Roaming/npm/node_modules/typescript/lib/lib.es6.d.ts(
21053,6): error TS2300: Duplicate identifier 'RTCIceGatheringState'.
C:/Users/shadanana/AppData/Roaming/npm/node_modules/typescript/lib/lib.es6.d.ts(
21057,6): error TS2300: Duplicate identifier 'RTCIceTransportPolicy'.
C:/Users/shadanana/AppData/Roaming/npm/node_modules/typescript/lib/lib.es6.d.ts(
21059,6): error TS2300: Duplicate identifier 'RTCSdpType'.
C:/Users/shadanana/AppData/Roaming/npm/node_modules/typescript/lib/lib.es6.d.ts(
21060,6): error TS2300: Duplicate identifier 'RTCSignalingState'.
../d.ts.files/DefinitelyTyped/webrtc/RTCPeerConnection.d.ts(17,6): error TS2300:
 Duplicate identifier 'RTCIceTransportPolicy'.
../d.ts.files/DefinitelyTyped/webrtc/RTCPeerConnection.d.ts(20,6): error TS2300:
 Duplicate identifier 'RTCBundlePolicy'.
../d.ts.files/DefinitelyTyped/webrtc/RTCPeerConnection.d.ts(61,13): error TS2403
: Subsequent variable declarations must have the same type.  Variable 'webkitRTC
PeerConnection' must be of type '{ new (configuration: RTCConfiguration): webkit
RTCPeerConnection; prototype: webkitRTCPeerConnect...', but here has type '{ new
 (settings?: RTCConfiguration, constraints?: RTCMediaConstraints): webkitRTCPeer
Connection; ...'.
../d.ts.files/DefinitelyTyped/webrtc/RTCPeerConnection.d.ts(89,3): error TS2403:
 Subsequent variable declarations must have the same type.  Variable 'type' must
 be of type 'RTCSdpType', but here has type 'string'.
../d.ts.files/DefinitelyTyped/webrtc/RTCPeerConnection.d.ts(89,3): error TS2687:
 All declarations of 'type' must have identical modifiers.
../d.ts.files/DefinitelyTyped/webrtc/RTCPeerConnection.d.ts(90,3): error TS2687:
 All declarations of 'sdp' must have identical modifiers.
../d.ts.files/DefinitelyTyped/webrtc/RTCPeerConnection.d.ts(94,3): error TS2403:
 Subsequent variable declarations must have the same type.  Variable 'type' must
 be of type 'RTCSdpType', but here has type 'string'.
../d.ts.files/DefinitelyTyped/webrtc/RTCPeerConnection.d.ts(94,3): error TS2687:
 All declarations of 'type' must have identical modifiers.
../d.ts.files/DefinitelyTyped/webrtc/RTCPeerConnection.d.ts(95,3): error TS2687:
 All declarations of 'sdp' must have identical modifiers.
../d.ts.files/DefinitelyTyped/webrtc/RTCPeerConnection.d.ts(104,11): error TS243
0: Interface 'webkitRTCSessionDescription' incorrectly extends interface 'RTCSes
sionDescription'.
  Types of property 'type' are incompatible.
    Type 'string' is not assignable to type 'RTCSdpType'.
../d.ts.files/DefinitelyTyped/webrtc/RTCPeerConnection.d.ts(113,11): error TS243
0: Interface 'mozRTCSessionDescription' incorrectly extends interface 'RTCSessio
nDescription'.
  Types of property 'type' are incompatible.
    Type 'string' is not assignable to type 'RTCSdpType'.
../d.ts.files/DefinitelyTyped/webrtc/RTCPeerConnection.d.ts(134,14): error TS230
0: Duplicate identifier 'RTCSdpType'.
../d.ts.files/DefinitelyTyped/webrtc/RTCPeerConnection.d.ts(216,14): error TS230
0: Duplicate identifier 'RTCIceGatheringState'.
../d.ts.files/DefinitelyTyped/webrtc/RTCPeerConnection.d.ts(224,14): error TS230
0: Duplicate identifier 'RTCIceConnectionState'.
../d.ts.files/DefinitelyTyped/webrtc/RTCPeerConnection.d.ts(236,14): error TS230
0: Duplicate identifier 'RTCSignalingState'.
../d.ts.files/DefinitelyTyped/webrtc/RTCPeerConnection.d.ts(285,3): error TS2687
0: Interface 'webkitRTCSessionDescription' incorrectly extends interface 'RTCSes
sionDescription'.
  Types of property 'type' are incompatible.
    Type 'string' is not assignable to type 'RTCSdpType'.
../d.ts.files/DefinitelyTyped/webrtc/RTCPeerConnection.d.ts(113,11): error TS243
0: Interface 'mozRTCSessionDescription' incorrectly extends interface 'RTCSessio
nDescription'.
  Types of property 'type' are incompatible.
    Type 'string' is not assignable to type 'RTCSdpType'.
../d.ts.files/DefinitelyTyped/webrtc/RTCPeerConnection.d.ts(134,14): error TS230
0: Duplicate identifier 'RTCSdpType'.
../d.ts.files/DefinitelyTyped/webrtc/RTCPeerConnection.d.ts(216,14): error TS230
0: Duplicate identifier 'RTCIceGatheringState'.
../d.ts.files/DefinitelyTyped/webrtc/RTCPeerConnection.d.ts(224,14): error TS230
0: Duplicate identifier 'RTCIceConnectionState'.
../d.ts.files/DefinitelyTyped/webrtc/RTCPeerConnection.d.ts(236,14): error TS230
0: Duplicate identifier 'RTCSignalingState'.
../d.ts.files/DefinitelyTyped/webrtc/RTCPeerConnection.d.ts(285,3): error TS2687
: All declarations of 'localDescription' must have identical modifiers.
../d.ts.files/DefinitelyTyped/webrtc/RTCPeerConnection.d.ts(286,3): error TS2687
: All declarations of 'remoteDescription' must have identical modifiers.
../d.ts.files/DefinitelyTyped/webrtc/RTCPeerConnection.d.ts(287,3): error TS2403
: Subsequent variable declarations must have the same type.  Variable 'signaling
State' must be of type 'RTCSignalingState', but here has type 'string'.
../d.ts.files/DefinitelyTyped/webrtc/RTCPeerConnection.d.ts(287,3): error TS2687
: All declarations of 'signalingState' must have identical modifiers.
../d.ts.files/DefinitelyTyped/webrtc/RTCPeerConnection.d.ts(294,3): error TS2403
: Subsequent variable declarations must have the same type.  Variable 'iceGather
ingState' must be of type 'RTCIceGatheringState', but here has type 'string'.
../d.ts.files/DefinitelyTyped/webrtc/RTCPeerConnection.d.ts(294,3): error TS2687
: All declarations of 'iceGatheringState' must have identical modifiers.
../d.ts.files/DefinitelyTyped/webrtc/RTCPeerConnection.d.ts(295,3): error TS2403
: Subsequent variable declarations must have the same type.  Variable 'iceConnec
tionState' must be of type 'RTCIceConnectionState', but here has type 'string'.
../d.ts.files/DefinitelyTyped/webrtc/RTCPeerConnection.d.ts(295,3): error TS2687
: All declarations of 'iceConnectionState' must have identical modifiers.
../d.ts.files/DefinitelyTyped/webrtc/RTCPeerConnection.d.ts(304,3): error TS2403
: Subsequent variable declarations must have the same type.  Variable 'onnegotia
tionneeded' must be of type '(this: RTCPeerConnection, ev: Event) => any', but h
ere has type '(event: Event) => void'.
../d.ts.files/DefinitelyTyped/webrtc/RTCPeerConnection.d.ts(307,3): error TS2403
: Subsequent variable declarations must have the same type.  Variable 'onaddstre
am' must be of type '(this: RTCPeerConnection, ev: MediaStreamEvent) => any', bu
t here has type '(event: RTCMediaStreamEvent) => void'.
../d.ts.files/DefinitelyTyped/webrtc/RTCPeerConnection.d.ts(308,3): error TS2403
: Subsequent variable declarations must have the same type.  Variable 'onremoves
tream' must be of type '(this: RTCPeerConnection, ev: MediaStreamEvent) => any',
 but here has type '(event: RTCMediaStreamEvent) => void'.
../d.ts.files/DefinitelyTyped/webrtc/RTCPeerConnection.d.ts(310,3): error TS2403
: Subsequent variable declarations must have the same type.  Variable 'oniceconn
ectionstatechange' must be of type '(this: RTCPeerConnection, ev: Event) => any'
, but here has type '(event: Event) => void'.
../d.ts.files/DefinitelyTyped/webrtc/RTCPeerConnection.d.ts(311,3): error TS2403
: Subsequent variable declarations must have the same type.  Variable 'onicecand
idate' must be of type '(this: RTCPeerConnection, ev: RTCPeerConnectionIceEvent)
 => any', but here has type '(event: RTCIceCandidateEvent) => void'.
../d.ts.files/DefinitelyTyped/webrtc/RTCPeerConnection.d.ts(313,3): error TS2403
: Subsequent variable declarations must have the same type.  Variable 'onsignali
ngstatechange' must be of type '(this: RTCPeerConnection, ev: Event) => any', bu
t here has type '(event: Event) => void'.
../d.ts.files/DefinitelyTyped/webrtc/RTCPeerConnection.d.ts(319,13): error TS240
3: Subsequent variable declarations must have the same type.  Variable 'RTCPeerC
onnection' must be of type '{ new (configuration: RTCConfiguration): RTCPeerConn
ection; prototype: RTCPeerConnection; }', but here has type '{ new (configuratio
n: RTCConfiguration, constraints?: RTCMediaConstraints): RTCPeerConnection; pr..
.'.
../d.ts.files/DefinitelyTyped/webrtc/RTCPeerConnection.d.ts(327,3): error TS2687
: All declarations of 'sdpMid' must have identical modifiers.
../d.ts.files/DefinitelyTyped/webrtc/RTCPeerConnection.d.ts(328,3): error TS2687
: All declarations of 'sdpMLineIndex' must have identical modifiers.
../d.ts.files/DefinitelyTyped/webrtc/RTCPeerConnection.d.ts(330,13): error TS240
3: Subsequent variable declarations must have the same type.  Variable 'RTCIceCa
ndidate' must be of type '{ new (candidateInitDict?: RTCIceCandidateInit): RTCIc
eCandidate; prototype: RTCIceCandidate; }', but here has type '{ new (candidateI
nitDict?: RTCIceCandidate): RTCIceCandidate; prototype: RTCIceCandidate; }'.
../d.ts.files/DefinitelyTyped/webrtc/RTCPeerConnection.d.ts(356,3): error TS2687
: All declarations of 'candidate' must have identical modifiers.'

Other details -

F:\typescript_support\demo>tsc -v
Version 2.3.4

F:\typescript_support\demo>node -v
v6.9.2

F:\typescript_support\demo>npm -v
3.10.9

Please help

**Comment by hthetiot** [comment]
Definition might need to be updated from:
https://github.com/DefinitelyTyped/DefinitelyTyped

**Comment by hthetiot** [comment]
From here may be to be exact:
- https://github.com/DefinitelyTyped/DefinitelyTyped/tree/release-2.3/types/webrtc

**Comment by hthetiot** [comment]
Also it look like webrtc type is not on DefinitelyTyped master anymore.

**Comment by ShadananaK** [comment]
Thank you for the help. What is your suggestion, how to proceed now ?  Please help.

**Comment by ShadananaK** [comment]
Any suggestion or other way , so that i can directly use Easyrtc.js library in my Angular project( instead of complex  d.ts file).

**Comment by hthetiot** [comment]
@ShadananaK try compile by removing RTCPeerConnection.d.ts also in the readme it say that file has been patched you may simply need to fix the error. 

Otherwise​ TypeScript goes to JavaScript anyway may be doing good old "any" could work and you can bypass the easyrtc TS until fix.
```
declare var easyrtc:any;
```

**Comment by hthetiot** [comment]
@ShadananaK Check this:
- https://github.com/priologic/easyrtc/pull/322

I never did TypeScript before, only tried to fix compile and found PeerConnection is part of TypeScript lib dom now.

Try and let me know.

**Comment by ShadananaK** [comment]
@hthetiot Thank you for  your valuable suggestions. Its transpiling now, without any error.

I have done two thing -

1. Removing the RTCPeerConnection.d.ts.

2. Declaration of "declare type RTCPeerConnectionConfig = any;" in easyrtc.d.ts.

Now i am facing following run-time error -

"AppComponent_Host.html:1 ERROR ReferenceError: easyrtc is not defined
    at AppComponent.connect (app.component.ts"

Any idea why i am getting the above error.

**Comment by hthetiot** [comment]
@EricDavies would know I think

**Comment by ShadananaK** [comment]
@hthetiot I included the easyrtc.js and soket.io.js files in my index.js file, and now the error "easyrtc is not defined" is solved.

Thank you.

**Comment by hthetiot** [comment]
\o/
