### ISSUE TITLE
Failed to get access to local media. Error code was unknown

### ISSUE THREAD

**Issue by ShadananaK** [priologic/easyrtc#323]
Hi, 

I am getting  the error "Failed to get  access to local media.", when i try to use easyrtc in ionic 2 ( cordova ).

I have given permission to access the camera and microphone (100%). If i verify camera permission using 'Diagnostic' module its giving authorized  as true.

The same code works fine when try in chrome browser, but when i build the app (apk) and try it in android mobile , its not working and throwing error saying "Failed to get  access to local media. Error code was unknown " in console.

I am using the latest version of easyrtc.js file.

_The debug log in console is as follows :_

debug 2017-06-22T09:09:03.296Z : WebRTC signaling server URL set to https://192.168.1.188:8181 [    at VcPage.connect (file:///android_asset/www/build/main.js:61380:17)]
easyrtc.js:3596 debug 2017-06-22T09:09:03.328Z : about to request local media [    at Easyrtc.easyrtc.easyApp (file:///android_asset/www/assets/js/easyrtc.js:8871:21)]
main.js:61425 ionViewDidLoad VcPage
plugins/cordova-plugin-webrtc/dist/webrtc.js:267 addVideoTag
plugins/cordova-plugin-webrtc/dist/webrtc.js:294 Video tag added 1
plugins/cordova-plugin-webrtc/dist/webrtc.js:267 addVideoTag
plugins/cordova-plugin-webrtc/dist/webrtc.js:294 Video tag added 2
easyrtc.js:1040 Class not found
easyrtc.js:3596 debug 2017-06-22T09:09:03.373Z : Trying getUserMedia a second time [    at file:///android_asset/www/assets/js/easyrtc.js:1041:9]
main.js:61400 Autharized
easyrtc.js:3596 debug 2017-06-22T09:09:03.378Z : WebRTC signaling server URL set to https://192.168.1.188:8181 [    at VcPage.connect (file:///android_asset/www/build/main.js:61380:17)]
easyrtc.js:3596 debug 2017-06-22T09:09:03.390Z : about to request local media [    at Easyrtc.easyrtc.easyApp (file:///android_asset/www/assets/js/easyrtc.js:8871:21)]
easyrtc.js:1040 Class not found
easyrtc.js:3596 debug 2017-06-22T09:09:03.400Z : getusermedia failed [    at file:///android_asset/www/assets/js/easyrtc.js:1041:9]
easyrtc.js:3596 debug 2017-06-22T09:09:03.402Z : failed to get local media [    at file:///android_asset/www/assets/js/easyrtc.js:1041:9]
easyrtc.js:3596 debug 2017-06-22T09:09:03.404Z : invoking error callback [    at file:///android_asset/www/assets/js/easyrtc.js:1041:9]
easyrtc.js:3599 debug 2017-06-22T09:09:03.404Z :  Unknown
easyrtc.js:1040 Class not found
easyrtc.js:3596 debug 2017-06-22T09:09:03.410Z : Trying getUserMedia a second time [    at file:///android_asset/www/assets/js/easyrtc.js:1041:9]
easyrtc.js:1040 Class not found
easyrtc.js:3596 debug 2017-06-22T09:09:03.415Z : getusermedia failed [    at file:///android_asset/www/assets/js/easyrtc.js:1041:9]
easyrtc.js:3596 debug 2017-06-22T09:09:03.417Z : failed to get local media [    at file:///android_asset/www/assets/js/easyrtc.js:1041:9]
easyrtc.js:3596 debug 2017-06-22T09:09:03.418Z : invoking error callback [    at file:///android_asset/www/assets/js/easyrtc.js:1041:9]
easyrtc.js:3599 debug 2017-06-22T09:09:03.418Z :  Unknown

_The line number -1040 "Class not found" is coming for 4th line in below code  :_

 var getUserMedia_ = function(constraints, onSuccess, onError) {
    shimConstraints_(constraints, function(c) {
      navigator.webkitGetUserMedia(c, onSuccess, function(e) {
		console.log(e);
        onError(shimError_(e));
      });
    });
  };

Please help.

**Comment by ShadananaK** [comment]
Any updates on the above issue ...??

**Comment by ShadananaK** [comment]
When i try to get basic media access its working absolutely fine.

Example : when i use
 "navigator.mediaDevices
       .getUserMedia(mediaConstraints)
       .then(this.successCallback.bind(this), this.errorCallback.bind(this)); "

But when i make use of easyrtc function its giving error - **Class not found**

i.e  easyrtc.initMediaSource( this.lSuccess.bind(this), this.loginFailure.bind(this),"Default Camera");

Please help.

**Comment by ShadananaK** [comment]
Sorry for the in-convince.

Its not Easyrtc problem. I have added  "cordova-plugin-webrtc"  which was causing the problem, i removed the plug-in and its working now.

**Comment by anggaand123** [comment]
@ShadananaK would you share how you implemented in ionic ?
