### ISSUE TITLE
screen sharing using easyrtc

### ISSUE THREAD

**Issue by abhishek123tanna** [priologic/easyrtc#324]
Hi..I have implemented screen sharing using easyrtc....i have uploaded it to the server...when i run it on client's computer..it's not working..but when i use demo from easyrtc.com..it works properly...i also got screen name using console.log.that i have use to share...but cant get the screen...i have also installed google chrome screen share extension......please provide guidance..about it...

**Comment by hthetiot** [comment]
Hum can you share link of your usage?

**Comment by hthetiot** [comment]
@abhishek123tanna I confirm a regression on beta branch.
Will investigate.

**Comment by hthetiot** [comment]
Fixed in beta #35d64ab18403cd3f0e185323413d84d74404d60a
