### ISSUE TITLE
[Chrome for Android] Demo video didn't work when hosted to another computer

### ISSUE THREAD

**Issue by githubuser05** [priologic/easyrtc#326]
Hi,

I'm new to easyrtc. I'm testing video functionality on Chrome in Android. 

I just noticed that the pop that ask permission to use microphone and camera appears when accessing this website on Chrome for Android and everything is working perfectly:
https://demo.easyrtc.com/demos/demo_audio_video_simple.html

When I installed the EasyRTC (GitHub version) on a PC/VPS then access the URL (using IP_ADDRESS:8080) on Chrome for Android, it has the error below and the pop never shows up.
"Failed to get access to local media. Error code was NotAllowedError."

Is this a known issue? Or is this because I'm using HTTP and IPADDRESS instead of HTTPS and DOMAINNAME?

Please help.

Thanks

**Comment by hthetiot** [comment]
You need to use https
