### ISSUE TITLE
Implement method on Client's API to disable mirroring on self-video.

### ISSUE THREAD

**Issue by martinrios95** [priologic/easyrtc#327]
I'll explain this.

When I tested the camera for an internal videochat system, the other callers are in the original position of the camera they are recording. But, my self-video shows **like a mirror of my recording**... But it won't have to happen this on self-video section, so I want a method to disable mirroring.

**Comment by Jerczu** [comment]
can't you just flip the local video element?

**Comment by EricDavies** [comment]
the part that makes your self video mirroring is a class attribute in the video's html.
 <video autoplay="autoplay" **class="easyrtcMirror"** id="selfVideo" muted="muted" volume="0" ></video>
So, yes, you already have a method.
