### ISSUE TITLE
Q : How can we change camera settings  our easyrtc project

### ISSUE THREAD

**Issue by Yamada4** [priologic/easyrtc#328]
Hi , we are making one to one and one to many video + audio sharing - streaming 
we manage it well without add anyhting
but we want to change camera settings
ex : white balance 

ex ;  http://imgur.com/QD1WAej
then : http://imgur.com/oDqfiFr

same data diffrent filtering , how can we do it ?

**Comment by EricDavies** [comment]
I'm not aware of anything in the underlying webrtc api for changing the camera settings beyond framerate and resolution.

**Comment by EricDavies** [comment]
your best bet is use the video as an input to opengl texture and render the texture  onto the display using a shader that makes all the changes you want (ie, do it on the receiving end, not the sending end).
It looks like there is something you can do with css filters (see https://webrtc.github.io/samples/src/content/getusermedia/filter/ )

If you are feeling brave, on the sending side, you can render your local video into a canvas, applying some image processing, and then get a mediastream from the canvas which you send out. My experience is mediastreams from the canvas use a lot of resources.

**Comment by martinrios95** [comment]
#327

**Comment by martinrios95** [comment]
I've got the same problem with mirroring self-video: #327

**Comment by hthetiot** [comment]
@martinrios95 for mirroring video via css:

```
.easyrtcMirror {
    -webkit-transform: scaleX(-1);
    -moz-transform: scaleX(-1);
    -ms-transform: scaleX(-1);
    -o-transform: scaleX(-1);
    transform: scaleX(-1);
}
```
```
<video class="easyrtcMirror"></video>
```

source:
- https://github.com/priologic/easyrtc/blob/c639daa1085c46cca7d0ecbe3b0db40ed349de09/api/easyrtc.css#L52

**Comment by martinrios95** [comment]
I made that for mirroring my video on my EasyRTC project. The only issue after that is about the video controls: it rotates too.

**Comment by hthetiot** [comment]
Haha yes controls are rotate with that solution, you need to look at rendering video on canvas but you will loose controls, another one would be to have a css selection to re-mirror controls (LOL)
