### ISSUE TITLE
"Browser does not appear to be WebRTC-capable" on Chrome 60

### ISSUE THREAD

**Issue by martinrios95** [priologic/easyrtc#334]
Hi,

When I've updated EasyRTC to latest version and restarted the server, Chrome's console had the following error: `Browser does not appear to be WebRTC-capable`.

I've upgraded Node.js to 8.0, EasyRTC to latest version, upgraded Chrome and upgraded npm packages, including itself...

This problem didn't happen before, so I post this issue.

Best wishes,

Martin

**Comment by EricDavies** [comment]
try the zombieland branch. master branch hasn't be updated in ages.

**Comment by martinrios95** [comment]
OK, thanks! Now it's working in Node.js again... Zombieland is the only repo that's being updated?
