### ISSUE TITLE
iPhone ios 11.0 beta 7 - results - send video/audio from phone (5s), but no receive

### ISSUE THREAD

**Issue by marcusgilson** [priologic/easyrtc#335]
I just downloaded and installed the latest easyrtc beta branch on a test server to test easyrtc with Safari on the iPhone ios 11.0 beta 7. When testing the /demo/demo_audio_video.html page going from an iPhone 5s to a dell laptop, the video/audio from the iPhone shows up on the laptop fine, but iPhone does not play the video/audio from the laptop.  Below is a screenshot of what you see on the iPhone and no audio is heard.  Has anyone had success getting the new ios 11.0 beta to work both ways on easyrtc with the Safari browser?

The connection and call control works well.

![img_0422](https://user-images.githubusercontent.com/31317350/29898495-e61fe2ec-8d9a-11e7-9c62-b9f51dba3c7f.PNG)

By the way, it works fine on the new Safari Technology Preview Release 38 on the Mac.

**Comment by riddleling** [comment]
`<video>` tag add `playsinline` properties , iOS Safari is works.

ex:
```
<video autoplay="autoplay" playsinline="playsinline" id="callerVideo"></video>
```

**Comment by marcusgilson** [comment]
Hello,
Thank you! That fixed my code for iPhone.  It works fine now on the iPhone 5s running ios 11 on safari.

**Comment by alexcmptls** [comment]
Works now using beta branch

**Comment by fais3000** [comment]
FYI Same happens for safari 11 on mac.

**Comment by hthetiot** [comment]
See #355

**Comment by hthetiot** [comment]
See https://github.com/priologic/easyrtc/pull/355

**Comment by hthetiot** [comment]
#422
