### ISSUE TITLE
How do we connect to easyrtc server?

### ISSUE THREAD

**Issue by binarybehemoth** [priologic/easyrtc#337]
I have setup the TURN server and signaling server. How do I connect to the server from the client side? Don't I need to supply the IP address and port to a function to initialise easyrtc? I am confused. Please help.

**Comment by archasek** [comment]
AFAIK the client requests the same address as your app is visible. Your web server have to process the request and point to the easyrtc server (which can be also your webserver).
Additional settings: https://easyrtc.com/docs/easyrtc_with_other_servers.php

According to the TURN: 

See:
https://github.com/priologic/easyrtc/blob/master/docs/easyrtc_client_tutorial.md
https://github.com/priologic/easyrtc/tree/master/demos
https://easyrtc.com/docs/easyrtc_server_ice.php
https://github.com/xirsys/easyrtc/blob/master/server_example/server.js
https://groups.google.com/forum/#!msg/easyrtc/s5fuoJUuN0o/rZQCJodfBQAJ
