### ISSUE TITLE
EasyRTC still failing on Safari 11.0 (on beta branch)

### ISSUE THREAD

**Issue by vetaliyrh7** [priologic/easyrtc#341]
<img width="1278" alt="2017-10-09 19 48 30" src="https://user-images.githubusercontent.com/13556078/31349184-de1d7460-ad2a-11e7-825c-fba3c03297b0.png">

I tried to use beta branch of EasyRTC. Still get the same error as in master version

**Comment by hthetiot** [comment]
#335 also required

**Comment by alexcmptls** [comment]
Nice. Works now using beta branch :)

**Comment by vetaliyrh7** [comment]
Can confirm that. Thx

**Comment by LukeStephen** [comment]
I am using Xirsys for the TURN / signaling server, but I get "Error creating RTCPeerConnection", have you seen that issue?

**Comment by hthetiot** [comment]
Not exactly, you have Safari on both client ?
I have seen case where Safari refuse PeerConnection, if client does not share stream via GetUserMedia.
It look a protection to avoid using PeerConnection without the user knowing.

**Comment by LukeStephen** [comment]
thanks for your quick reply, it ended up being a setup issue with the xirsys code in server.js it's working perfectly now, thanks!

**Comment by hthetiot** [comment]
#422
