### ISSUE TITLE
 How to create a stream from client 'browser' to server (Not from client to client)?

### ISSUE THREAD

**Issue by younosAli** [priologic/easyrtc#346]
Hi, 
I want to make streaming (video stream) from client 'browser' to a server to enter this stream to another process running on a server, How do that?

**Comment by hthetiot** [comment]
Easyrtc does not provide such feature.
You need to look at uploading the recording via websocket or via peerConnection and use Media Source Extensions on client to decode the stream from the peer.

**Comment by hthetiot** [comment]
See `easyrtc.register3rdPartyLocalMediaStream(stream, streamName)` and `easyrtc.addStreamToCall(easyrtcId, streamName, receiptHandler)`

https://github.com/priologic/easyrtc/blob/master/api/easyrtc_int.js#L1835
