### ISSUE TITLE
Websocket error on video demo

### ISSUE THREAD

**Issue by SawnFx** [priologic/easyrtc#348]
`VM61:164 WebSocket connection to 'wss://srv2.sawnfx.com/socket.io/?EIO=3&transport=websocket&sid=JSHRjTRVLvPGupeSAAAB' failed: Error during WebSocket handshake: Unexpected response code: 400`
On Ubuntu 16.04
NodeJS 8.9.1
Latest version of easyrtc
Opera 49 W10 (also don't work with Chrome 66 W10 & Android 6)
Nginx Proxy

**Comment by hthetiot** [comment]
Hum, could be the nginx proxy, can you try without nginx and let me know.

**Comment by hthetiot** [comment]
@SawnFx See that https://github.com/socketio/socket.io/issues/1942#issuecomment-82352072
