### ISSUE TITLE
Angular 4 with java as backend

### ISSUE THREAD

**Issue by nishant-varshney** [priologic/easyrtc#361]
I want to use angular 4 with java as backend. What I need is a single war file.I dont want to run different server for front end and back end. I want that there will be single java war file so that I can deploy it on app server like tomcat or jboss.
Please suggest some approach. Your help is highly appreciated.

**Comment by hthetiot** [comment]
Serving https via Java tomcat not be an issue we solve for you:
- https://www.thegeekstuff.com/2011/09/ssl-for-tomcat-server/

For angular 4 or 2+ using TypeScript see:
- https://github.com/priologic/easyrtc/tree/v1.1.1-rc1/typescript_support

**Comment by hthetiot** [comment]
This also https://www.webjars.org/
<img width="816" alt="screen shot 2018-01-17 at 1 39 26 pm" src="https://user-images.githubusercontent.com/8635/35068429-e04ef7d6-fb8b-11e7-9e9c-80816e6ed69c.png">

**Comment by hthetiot** [comment]
<img width="906" alt="screen shot 2018-01-17 at 1 41 53 pm" src="https://user-images.githubusercontent.com/8635/35068572-497a9f62-fb8c-11e7-94d0-22c1012167f8.png">

**Comment by nishant-varshney** [comment]
` Hi.. Thank You... Please help me on this as well. 
I am having one JAVA Rest API project(dynamic web project) and another angular 4 project. Angular 4 is getting data from Java Rest api project. Now how I can move my angular 4 project in Java Rest api project so that i can deploy it on any app server like jboss or tomcat.

**Comment by hthetiot** [comment]
Did you try nashorn  ?
