### ISSUE TITLE
Multistream video chat. Firefox performs better than Chrome.

### ISSUE THREAD

**Issue by tangmeng09** [priologic/easyrtc#362]
Hello,
I have tested the multisteam video chat many times on different locations. 
If all chients use Chrome, some of the client will get blank video and the error message NOVIABLEICE. It's hard to get all peers to see each other. Occasionally all Chrome client works after a long connection time.
But if some of the clients use Firefox, no problems. 
Why this happens?

**Comment by hthetiot** [comment]
May be this can help:
- https://github.com/priologic/easyrtc/pull/391/files#diff-db5890b7b83a9a5ba3f9bc3c6d33976cR784

Reference:
- // http://www.acis.ufl.edu/~ptony82/jingle-html/classwebrtc_1_1MediaConstraintsInterface.html

Sorry we cannot help you more you need to check your ICE.
