### ISSUE TITLE
Video not shown in iOS11

### ISSUE THREAD

**Issue by diex78** [priologic/easyrtc#363]
I have an WebRTC app that uses EasyRTC and cordova with cordova-iosrtc plugin for iOS support.
All works fine on iOS9 and 10. But with iOS 11 I can hear audio between devices but can't see video on the device with iOS11 (neither local or remote). 

I have added the changes suggested in other issues (like playsinline in video tag) but with no luck.

In console I receive this error:

    [Error] Not allowed to load local resource: blob:blobinternal:///1e3f641c-d947-4cf4-8de3-a51ce8f64e42

Someone has seen this error before? Thanks

**Comment by hthetiot** [comment]
Do you have CSP headers on your page or http headers?

**Comment by hthetiot** [comment]
I have seen this with WebRTC safari plugin installed I think.

**Comment by Jagdeep-Sing** [comment]
Any solution? I faced same problem.

**Comment by hthetiot** [comment]
Pleas test on https://easyrtc.sylaps.net and reopen if fail.

**Comment by hthetiot** [comment]
#422
