### ISSUE TITLE
Unable to reconnect after phone wakeup

### ISSUE THREAD

**Issue by grosmar** [priologic/easyrtc#364]
I'm working on a cordova android/ios app with webRTC. 

When I try to reconnect after phone wake up from lock screen it connect, but immediately after disconnects with the following message:
`"Timed out trying to talk to the server"`

I guess it's because of the following happens:
- socket.io have it's automatic reconnect behavior that connects me, but right after the successful connection the `processToken` is called that calls the `stillAliveEmitter`. 
And because previously there was a timeout and nothing resets it's indicator `missedAliveResponses` it automatically disconnects.

The same happens when I receive this "timed out..." message and after try to manually reconnect to the server. 

Proposal:
Simply reset the counter when `self.webSocket.on("connect", ...)` happens.

What do you think?

**Comment by ne0x** [comment]
I had same problems, after some network problems when I tried to connect again, I had "Timed out trying to talk to the server". After this 8241e97 fix all works good for me

**Comment by hthetiot** [comment]
Merged  #336  in beta
