### ISSUE TITLE
FAQs (One to Many & Many to Many)

### ISSUE THREAD

**Issue by ArsalRaza** [priologic/easyrtc#365]
Hello everyone,
My name is ArsalImam. Right now I'm working on one of my client's project. I completely installed the EasyRTC framework on my server and also check the examples (which are wrote excellently).
I have few queries regarding EasyRTC and also required suggestions and answers from which methods I can use to overcome on these queries/issues. Following are my queries regarding EasyRTC:
1) How EasyRTC works in case of One to Many communications (such as webinars etc)? I mean, is EasyRTC configured to use media server, in a way that Peer -> Media Server -> Other Peers.
2) Can I configured EasyRTC to share any specific window or tab? Like, lets suppose, I only wants to allow MS-Paint window to be shared with other peers
3) Is there any time limit on recording a conference call?
4) How much peers it can support during a video session?
5) Can I allow approx 700 connections (in One to Many communication)?
6) What recommended physical assets(bandwidth, RAM etc) are required to support 700 connections in One to Many communication?
7) Can I configured EasyRTC to use one server for live streaming & a different server for media storage?

**Comment by hthetiot** [comment]
May be this can be answered in faq if not already:
- https://github.com/priologic/easyrtc/blob/master/docs/easyrtc_faq.md
