### ISSUE TITLE
Error [ERR_SERVER_ALREADY_LISTEN]: Listen method has been called more than once without closing.

### ISSUE THREAD

**Issue by kurodenjiro** [priologic/easyrtc#368]
i was setup project but i got some error
Error [ERR_SERVER_ALREADY_LISTEN]: Listen method has been called more than once without closing.
    at Server.listen (net.js:1432:11)
    at Object.<anonymous> (C:\Users\PC\Desktop\stream server\easyrtc\server_example\server.js:57:11)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
    at Function.Module.runMain (module.js:703:10)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:665:3
PS C:\Users\PC\Desktop\stream server\easyrtc\server_example> node server.js
info    - EasyRTC: Starting EasyRTC Server (v1.1.0) on Node (v9.6.1)
debug   - EasyRTC: Emitting event 'startup'
debug   - EasyRTC: Running func 'onStartup'
net.js:1432
    throw new errors.Error('ERR_SERVER_ALREADY_LISTEN');
    ^

**Comment by hthetiot** [comment]
Simply check that you don't call listen() twice in you code this is a typical error when you copy paste without understanding.

**Comment by hthetiot** [comment]
May be you have something on 8080 of used port already

**Comment by kurodenjiro** [comment]
No . on window it got error . i remoted end code listen port and it's runing . but on ubuntu it ok

**Comment by TheClonker** [comment]
The Problem is that the .listen Function is indeed called twice by accident.  See here:
https://github.com/priologic/easyrtc/blob/master/server_example/server.js#L16
https://github.com/priologic/easyrtc/blob/master/server_example/server.js#L57

Removing it from Line 16 fixes the error and keeps the console log that the Server started successfully

**Comment by kurodenjiro** [comment]
thank you

**Comment by hthetiot** [comment]
@kurodenjiro @TheClonker 
See #374 for fix in master and beta.
Sorry, I missed it, feel free to PR next time ;)
