### ISSUE TITLE
URL.createObjectURL(stream) has been deprecated

### ISSUE THREAD

**Issue by trippledave** [priologic/easyrtc#369]
The easyrtc.js uses this function, which will also be removed from Chrome soon and is deprecated in other browsers as well.

https://www.fxsitecompat.com/en-CA/docs/2017/url-createobjecturl-stream-has-been-deprecated/
the link also shows how to solve the problem.

**Comment by hthetiot** [comment]
This is already managed by `easyrtc.setVideoObjectSrc` that check for srcObject and fallback on `createObjectURL` otherwise.
- https://github.com/priologic/easyrtc/blob/e943fa8c4cdef2878bb07f0d95400fb91d374be1/api/easyrtc_int.js#L1936
