### ISSUE TITLE
How can I connect without having Webcam or Microphone and other people seeing me as I've connected normally?

### ISSUE THREAD

**Issue by martinrios95** [priologic/easyrtc#372]
Referencing #367 
Hello!

I'm using `connect()` function to put easyrtc connections online. So, when a member of the chat room hasn't got a webcam/microphone, his name or his username **doesn't appear on other members' list**.

So, is there a method or function I could use to make this right?
By the way, thank you!

**Comment by hthetiot** [comment]
```
// Create a Spectactor
easyrtc.setUsername("Spectactor");
easyrtc.updatePresence('xa', 404); // Example made up but 'xa' mean 

// Do not send media
easyrtc.enableAudio(false);
easyrtc.enableVideo(false);
// Receive them only
easyrtc.enableAudioReceive(true);
easyrtc.enableVideoReceive(true);
```

```
easyrtc.setRoomOccupantListener(function (roomName, users, user) {
//  `users` and `user` that connect to the room will have `presence.show` value reflected 
});
```

```
away -- The entity or resource is temporarily away.
chat -- The entity or resource is actively interested in chatting.
dnd -- The entity or resource is busy (dnd = "Do Not Disturb").
xa -- The entity or resource is away for an extended period (xa = "eXtended Away").
```
Source: https://xmpp.org/rfcs/rfc3921.html

**Comment by hthetiot** [comment]
Please, @martinrios95  re-open do not create a new issue if not ok.
That help for questions resolution.

**Comment by hthetiot** [comment]
Also https://github.com/priologic/easyrtc/issues/297

**Comment by martinrios95** [comment]
How can I ask if the user has a camera or not? And, when the user hasn't got a camera, how can I get into that code?

**Comment by hthetiot** [comment]
`getUserMedia({video: true})` will fail if no video.
