### ISSUE TITLE
Error message with multistream iframe

### ISSUE THREAD

**Issue by MatthieuHPP** [priologic/easyrtc#378]
Hello, 
I am using last beta version of Easyrtc, the demo 

> demo_multistream_iframe

.
Browser is Chrome, OS is Ubuntu 16.04, node version 6.13

Once screen sharing initiated, when one peer closes one of its local streams, the other receives the following error message, whereas it seems to works : 
> setLocalDescription: OperationError: Failed to set local answer sdp: Called in wrong state: kStable

What does that mean ?
Many thanks

Matthieu

**Comment by hthetiot** [comment]
Hum might be a regression, checking.

**Comment by hthetiot** [comment]
I do not reproduce.

```
git clone -b beta git@github.com:priologic/easyrtc.git 
cd easyrtc
npm i --production
cd server_example
npm i --production
node server
```

open 2 client and connect then call
- http://localhost:8080/demos/demo_multistream_iframe.html

**Comment by MatthieuHPP** [comment]
Many thanks for your reply.

That's annoying, I did exactly the manipulations that you have mentioned.
I am still having the error message.

One difference might be I am using Ubuntu.
I precise what I do once using the demo  :
-Each peer connects
-Each peer activates its own camera
-One peer calls the other
-One peer shares its screen

At this stage both caméra and one screen are shared, it is all working.
But when the peer sharing its screen stops it, the other receives an error message

Matthieu
