### ISSUE TITLE
New easyrtc does not work with electron.js

### ISSUE THREAD

**Issue by MariasStory** [priologic/easyrtc#379]
Hi there,
Please fix problems with electorn.js execution of the easyrtc api - client side.

The problem is that the condition:
> if (typeof module === 'object' && module.exports)

is triggered in electron rendering and the "require(" statements are causing the problems.
From comments I see that it was done for "//CommonJS build system". Please make sure that you properly identify the build system and do not trigger in electron.js

**Comment by hthetiot** [comment]
Election is crap and it work perfectly with https://nwjs.io/ and many old chrome version of chrome.
Create a more explicit packing error issue or change or fix  your JS packaging,
