### ISSUE TITLE
Enable/Disable video during call.

### ISSUE THREAD

**Issue by craidencool13** [priologic/easyrtc#384]
Hi.

Anyone tried setting enableVideo(false) & enableVideoReceive(false) after performing the call.

It only seems to work on the caller's end and not the callee.

Thanks!

**Comment by hthetiot** [comment]
This work as expected using following methods, streamName should be optional.
```
easyrtc.enableCamera(enabled, streamName);
easyrtc.enableMicrophone(enabled, streamName);
``

Note: works on sylaps.com
