### ISSUE TITLE
how can we modify the zooming of the video?

### ISSUE THREAD

**Issue by ynotrem7** [priologic/easyrtc#388]
We have integrated the easy-rtc in our ionic mobile android app. We've noticed that the video displays our face to near or almost liked zoomed in. How can we modify the display to make it look a little bit farther or zoom out? thanks

**Comment by hthetiot** [comment]
That not related to easyrtc, you receive a MediaStream you need to handle the aspect ratio of the video tag for example using css object-fit or max-with and max-height.

- https://css-tricks.com/almanac/properties/o/object-fit/
