### ISSUE TITLE
Ask Webrtc

### ISSUE THREAD

**Issue by anggaand123** [priologic/easyrtc#392]
Hi,
i want to ask about
What is WebRTC ?
What is PhoneRTC ?
What is easyRTC ?

i want to develop video call streaming using ionic 3. is that related ?

**Comment by hthetiot** [comment]
This is not the right place for that.
Use Google or visit the following website http://easyrtc.com/, http://webrtc.org/

> i want to develop video call streaming using ionic 3. is that related ?
Yes you could use Easyrtc TypeScript in ionic to enable real-time commucation

See:
 - https://github.com/priologic/easyrtc/tree/beta/typescript_support
- https://github.com/priologic/easyrtc/issues/331

**Comment by anggaand123** [comment]
please help in this forum sir 
https://easyrtc.com/forum/?place=msg%2Feasyrtc%2F_QXxgurNUD0%2Fyb-JIkXuAgAJ

**Comment by hthetiot** [comment]
@anggaand123 I replied privately to you there.
