### ISSUE TITLE
Cannot get Camera source

### ISSUE THREAD

**Issue by anggaand123** [priologic/easyrtc#394]
https://ibb.co/dgW3TT

i cant choose camera source. it only show **src_0** and **src_1**

**Comment by hthetiot** [comment]
Can you test here:
- https://easyrtc.sylaps.net/demos/

**Comment by hthetiot** [comment]
Also this your screen is from typescript?
Can you test: https://easyrtc.sylaps.net/demos/demo_multistream_iframe.html

**Comment by hthetiot** [comment]
![screenshot_20180604-110403_chrome](https://user-images.githubusercontent.com/8635/40933723-3762c0a8-67e7-11e8-9dd3-43902c8d7d25.jpg)

**Comment by hthetiot** [comment]
I will had guideline to post issue.
Reopen if you awnser my questions above.

**Comment by anggaand123** [comment]
yes im using typescript

**Comment by hthetiot** [comment]
If you have issue once and not another time could be related to your camera, or we may do not handle and event state properly under certain timing.

Feel free to reopen if you find something.
Sry I cannot help more.

**Comment by hthetiot** [comment]
Tell me is more about the device the issue is your device and chrome version look for above 68 if your device is ARM based and use USB camera. May depend device alao.
