### ISSUE TITLE
Camera Front and Rear Toogle

### ISSUE THREAD

**Issue by craidencool13** [priologic/easyrtc#395]
Hi.

Have you guys tried to switch from front camera to rear and vise versa? I am utilizing ionic in developing this project.

Hope someone can help me with this. Thanks!

**Comment by hthetiot** [comment]
See demo code:
- https://github.com/priologic/easyrtc/blob/master/demos/js/demo_multistream.js

Live demo:
-  https://easyrtc.sylaps.net/demos/demo_multistream.html
