### ISSUE TITLE
EasyRTC Many to Many Video Calling causing issues?

### ISSUE THREAD

**Issue by smanask** [priologic/easyrtc#397]
0
down vote
favorite
I have been working on a Group Video Calling app using EasyRTC where I can do group calling between n number of participants in which each and every participant can watch and listen to other participants too.

I tried a working example by Eric Davies here : https://gist.github.com/EricDavies/9818205.

The above example code works fine for 3 participants (1 caller [P1] + 2 receivers [P2, P3]), all of them get in a group call perfectly, but as I add one more participant i.e. [P4], the caller [P1] and [P4] can watch and listen to each other but no call is initiated to [P2] and [P3].

What I need is to be able to connect all participants to each other as they join in as given in the attache d. Can anyone help me out in the same. TIA. :)
![easyrtc](https://user-images.githubusercontent.com/11233113/41034756-400f2184-69a8-11e8-9eec-ad3a908316f8.png)

**Comment by hthetiot** [comment]
You should not try to control that way, instead doe a simple rules like the user that was first in the room, call new partcitant on room join or the reverse new user in the room will call user that was there first.

Here is the demo code:
- https://github.com/priologic/easyrtc/blob/master/demos/js/demo_multiparty.js#L528
