### ISSUE TITLE
URL.createObjectURL stream is depreceated.

### ISSUE THREAD

**Issue by vk1003** [priologic/easyrtc#402]
easyrtc.js:4152 [Deprecation] URL.createObjectURL with media streams is deprecated and will be removed in M68, around July 2018. Please use HTMLMediaElement.srcObject instead. See https://www.chromestatus.com/features/5618491470118912 for more details.

If you can let us know where to look for this file and how to change?

**Comment by hthetiot** [comment]
Should be fixed in beta branch.
Reopen otherwise pls

> npm I easyrtc#priologic/easyrtc#beta

**Comment by federicofreiberger** [comment]
Thanks to Devashish Chauhan who answered me on the mail, I'm posting this just for reference.

From his answer:

The correct way is to -

Change   
`element.src = self.createObjectURL(stream);
`
To
`element.srcObject = stream;
`

You will have to do this in the easyrtc.js file. wherever you see -  element.src = self.createObjectURL(stream); just replace it with element.srcObject = stream;
