### ISSUE TITLE
Add a path parameter to the setSocketUrl methods

### ISSUE THREAD

**Issue by AMontagu** [priologic/easyrtc#403]
### Problem

When using nginx as a reverse proxy only a direct redirection work. 

I mean this work:
```
location / {
                proxy_pass http://127.0.0.1:8080/;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_cache_bypass $http_upgrade;
        }
```

this will not work (for signaling server, accessing to the files work):
```
location /something/ {
                proxy_pass http://127.0.0.1:8080/;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_cache_bypass $http_upgrade;
        }
```

### Error in the console:

`CONNECT_ERR Unable to reach the easyRTC signalling server`

### How I use setSocketUrl:

```
this.$easyrtc.setSocketUrl(':443/something'); // not work
this.$easyrtc.setSocketUrl(':443/something/'); // not work
this.$easyrtc.setSocketUrl('/something'); // not work
this.$easyrtc.setSocketUrl('/something/'); // not work
this.$easyrtc.setSocketUrl(':9080'); // work
```

### Why I want to do that:

- This allow to pass different service to the 443 port on the same server
- This allow me to do that on my html file without hosting the files on my web server:

```
<script src="/something/socket.io/socket.io.js"></script>
<script src="/something/easyrtc/easyrtc.js"></script>
```

### PeerJs worked with it

I was using PeerJs before and for the connection I used something like that:
```
this.peer = new Peer({host: \<host\>, port: '', path: 'something'});
```

Let me know if it possible somehow or if you can consider doing that in the future.

Thank you for your time.

**Comment by hthetiot** [comment]
Le me check I had this working in the past.

**Comment by hthetiot** [comment]
This is the way, like that we don't have to maintain socket.io basic if you need custom provide your own socket io client instead.
See : https://github.com/priologic/easyrtc/pull/67
