### ISSUE TITLE
P2P Server handshake only

### ISSUE THREAD

**Issue by wini3d** [priologic/easyrtc#405]
thanks, examples looks simple and easy! I would to know how I can only use p2p with the server just doing the handshake? Is this possible?

**Comment by hthetiot** [comment]
There is example of iceFilter in the demo code
- https://github.com/priologic/easyrtc/blob/master/demos/js/demo_ice_filter.js

See demo here:
- https://easyrtc.sylaps.net/demos/demo_ice_filter.html
