### ISSUE TITLE
Videocall doesn't work in Firefox

### ISSUE THREAD

**Issue by d97arkslayer** [priologic/easyrtc#407]
The video call works perfectly in chrome but in firefox it does not work at all

**Comment by hthetiot** [comment]
Hum, do you use STUN or TURN?
Can you reproduce here @d97arkslayer 
- 
https://easyrtc.sylaps.net/demos/demo_audio_video_simple.html

**Comment by d97arkslayer** [comment]
Yes i can reproduce in this url, what is the server code?
Where can I find the repository of this code? or is it the same as the
github?


I am not using anything that is not outside the easyrtc that is in the
github.
Thank you very much

**Comment by MariasStory** [comment]
Hi @d97arkslayer, the "sylaps" example works for me. FF on linux. Make sure to allow access to webcam ;-)

**Comment by d97arkslayer** [comment]
Hi @MariasStory and @hthetiot  thanks,I have a problem, if I want to upload it to a server on the network, what should I do to make it work?
I'm trying to upload it to a debian server that I have for some tests and it does not work
![imagen](https://user-images.githubusercontent.com/30955600/45793883-8e481500-bc59-11e8-8f8f-c7813a2bd160.png)
If you have any solution, or any idea of what happens, please tell me thank you very much

**Comment by hthetiot** [comment]
Here look like your port 8080 is already use @d97arkslayer

**Comment by hthetiot** [comment]
> Yes i can reproduce in this url, what is the server code? Where can I find the repository of this code? or is it the same as the github?
This is master see server_example Dockerfile

Via docker hub:
- https://hub.docker.com/r/sylaps/easyrtc-server/

**Comment by hthetiot** [comment]
Close cause not same issue as title and work on FF
Thx @MariasStory
