### ISSUE TITLE
Implement replaceTrack.

### ISSUE THREAD

**Issue by MariasStory** [priologic/easyrtc#408]
https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpSender/replaceTrack

**Comment by hthetiot** [comment]
https://dontcallmedom.github.io/webrtc-impl-tracker/?webrtc

**Comment by hthetiot** [comment]
See `easyrtc.register3rdPartyLocalMediaStream(stream, streamName)` and `easyrtc.addStreamToCall(easyrtcId, streamName, receiptHandler)`
