### ISSUE TITLE
Problem in the deployment in an online server

### ISSUE THREAD

**Issue by d97arkslayer** [priologic/easyrtc#410]
I have a problem, if I want to upload it to a server on the network, what should I do to make it work?
I'm trying to upload it to a debian server that I have for some tests and it does not work
![imagen](https://user-images.githubusercontent.com/30955600/45794421-3f4faf00-bc5c-11e8-9b78-e6ee606e6c91.png)
If you have any solution, or any idea of what happens, please tell me thank you very much

**Comment by hthetiot** [comment]
Your port 8080 is already in use aka "EADDRINUSE"
- https://stackoverflow.com/questions/4075287/node-express-eaddrinuse-address-already-in-use-kill-server/4086015

**Comment by hthetiot** [comment]
@d97arkslayer check you use master or beta branch your issue look a regression of this https://github.com/priologic/easyrtc/pull/374 this issue is on npm version

**Comment by hthetiot** [comment]
To be clear you may have this issue with easyrtc from npm.
To use last version you can:
> npm i priologic/easyrtc#master

Will leave open until npm released

**Comment by d97arkslayer** [comment]
The problem was solved, with the latest version, thank you very much.
I have a problem when making the video call online, that is, when I'm no
longer in a local network

**Comment by hthetiot** [comment]
> I have a problem when making the video call online, that is, when I'm no
longer in a local network

@d97arkslayer you need to watch that video to understand why your call fail.
(Most certainly you need STUN/TURN server in your ICE)

https://www.youtube.com/watch?v=_OE-4woHv2E

**Comment by d97arkslayer** [comment]
Thanks Harold, what could be a quick and free solution. I am a student and I do not have resources.

**Comment by d97arkslayer** [comment]
Thanks Harold, what could be a quick and free solution. I am a student and I do not have resources.

**Comment by hthetiot** [comment]
- https://hub.docker.com/r/zolochevska/turn-server/
