### ISSUE TITLE
How to add Ice Configuration

### ISSUE THREAD

**Issue by d97arkslayer** [priologic/easyrtc#412]
How to add the configuration of stun and turn servers

**Comment by hthetiot** [comment]
RTMF :)
- https://github.com/priologic/easyrtc/blob/master/docs/easyrtc_server_ice.md#easyrtc-server-ice-configuration

**Comment by d97arkslayer** [comment]
Hello Harold, I already made that configuration and it tells me that
easyrtc.setOption is not an easyrtc option

**Comment by d97arkslayer** [comment]
How it can be implemented in an online server, in the local area it works perfect but streaming video does not work in online server, and chat does work !!!.
How i can I get stun or turn servers, I need this for a personal project online.
I need an urgent solution.
Thank you very much.

**Comment by d97arkslayer** [comment]
Can you give me your email please to communicate more quickly.
Thank you very much.
Or write to me
esteban.herrera.1126@gmail.com.

It's very urgent.

**Comment by hthetiot** [comment]
@d97arkslayer https://sylaps.com/room/easyrtc

**Comment by hthetiot** [comment]
@d97arkslayer -> https://gist.github.com/yetithefoot/7592580
Otherwise you need to install you own:
- https://www.webrtc-experiment.com/docs/TURN-server-installation-guide.html

**Comment by hthetiot** [comment]
@d97arkslayer Here is the change I made during the call.

```
diff --git i/server_example/server.js w/server_example/server.js
index dc50eda..23b137d 100644
--- i/server_example/server.js
+++ w/server_example/server.js
@@ -3,7 +3,7 @@ var http    = require("http");              // http server core module
 var express = require("express");           // web framework external module
 var serveStatic = require('serve-static');  // serve static files
 var socketIo = require("socket.io");        // web socket external module
-var easyrtc = require("../");               // EasyRTC external module
+var easyrtc = require("easyrtc");               // EasyRTC external module^M
 
 // Set process name
 process.title = "node-easyrtc";
@@ -20,6 +20,22 @@ var socketServer = socketIo.listen(webServer, {"log level":1});
 
 easyrtc.setOption("logLevel", "debug");
 
+var myIceServers = [^M
+  {"urls":"stun:[ADDRESS]:[PORT]"},^M
+  {^M
+    "urls":"turn:[ADDRESS]:[PORT]",^M
+    "username":"[USERNAME]",^M
+    "credential":"[CREDENTIAL]"^M
+  },^M
+  {^M
+    "urls":"turn:[ADDRESS]:[PORT][?transport=tcp]",^M
+    "username":"[USERNAME]",^M
+    "credential":"[CREDENTIAL]"^M
+  }^M
+];^M
+^M
+easyrtc.setOption("appIceServers", myIceServers);^M
+^M
 // Overriding the default easyrtcAuth listener, only so we can directly access its callback
 easyrtc.events.on("easyrtcAuth", function(socket, easyrtcid, msg, socketCallback, callback) {
     easyrtc.events.defaultListeners.easyrtcAuth(socket, easyrtcid, msg, socketCallback, function(err, connectionObj){
```

**Comment by d97arkslayer** [comment]
I'm using the server_ssl.js works the same as this one?

**Comment by hthetiot** [comment]
Yes it does.
But over time you will need a valid SSL certificate otherwise you will have many issue.
- example of free cert: https://letsencrypt.org/
