### ISSUE TITLE
Chrome 69 audio problems 

### ISSUE THREAD

**Issue by AliBahramiEhsan** [priologic/easyrtc#414]
Suddenly, today the chrome browser updates itself to the newest version, 69, and the webrtc connection is lost. 
There were no errors on version 67, but after update, I see this error: 
**Failed to get access to local media. Error code was NotFoundError.**
I was thinking the problem maybe refers to easyrtc, not webrtc in generic form, but when I tested with test.webrtc.org I saw that the microphone is not on the list of devices it wants to allow permissions to use, and even the tests about the camera has been failed.

What should we do now?

**Comment by hthetiot** [comment]
> I was thinking the problem maybe refers to easyrtc, not webrtc in generic form, but when I tested with test.webrtc.org I saw that the microphone is not on the list of devices it wants to allow permissions to use, and even the tests about the camera has been failed.

Use links above one use easyrtc tha other (the test page does not), we may be able to see if the issue depend local env or remote env

**Comment by Archer-Thane** [comment]
Thanks for the links.
I run the tests you provide in these conditions:
Changing the internet provider was not affected the results. ( I just checked to ensure that)
In chrome 69, most of the tests failed. although the mic and camera are available.
In firefox 63.0.3 most of the tests passed. 
chrome result can be seen [here](https://postimg.cc/QVDnXZjT), and firefox result [here](https://postimg.cc/t1P2j2fk).

I just do the same test on my phone (android 4.4 and latest chrome stable version) and results are as same as firefox.
Why google chrome behaves like this?

**Comment by AliBahramiEhsan** [comment]
Thanks for the links.
I run the tests you provide in these conditions:
Changing the internet provider was not affected the results. ( I just checked to ensure that)
In chrome 69, most of the tests failed. although the mic and camera are available.
In firefox 63.0.3 most of the tests passed.
chrome result can be seen here, and firefox result here.

I just do the same test on my phone (android 4.4 and latest chrome stable version) and results are as same as firefox.
Why google chrome behaves like this?

**Comment by hthetiot** [comment]
@AliBahramiEhsan could be chrome WebRTC issue that now amhave been fixed, can you try Chrome 70?

**Comment by hthetiot** [comment]
see #415 for beta for adapter 6.4.0 and #433 for PR with latest adapter 7.2.1.
