### ISSUE TITLE
Firefox 62 Video problems

### ISSUE THREAD

**Issue by syedMSohaib** [priologic/easyrtc#416]
I have used all  branches for webRTC including the latest beta and mater branch on Firefox 62.0.3 and its not working. it is working fine on chrome but not on Firefox. Even no errors are appearing in the console.
Please need a fix for this issue soon.
Can anybody tell me what to do.

Pardon for my grammar,

**Comment by MariasStory** [comment]
This version works for me:
https://easyrtc.sylaps.net/demos/demo_audio_video_simple.html

For the messages, in my solution I get:
1) For old version: navigator.getUserMedia has been replaced by navigator.mediaDevices.getUserMedia
2) For new version:
a) onaddstream is deprecated! Use peerConnection.ontrack instead.
b) RTCPeerConnection.getLocalStreams/getRemoteStreams are deprecated. Use RTCPeerConnection.getSenders/getReceivers instead.

And my solution does not work in FF, both ways :-(. Need to fix.

**Comment by hthetiot** [comment]
I will investigate, keep you posted

**Comment by hthetiot** [comment]
@syedMSohaib what do you mean by video problems ? The video is black or you are not able to get local video, or the remote stream is not received ?

**Comment by syedMSohaib** [comment]
@hthetiot Hey buddy so sorry for late response.
Well i am not able to get local video stream on firefox to firefox. but in case of chrome to firefox i do get a black video stream. Didn't know why it showed different behaviour
And One more request can you update the demo on the website. i guess its bit outdated wrt to the collaboration you guys are doing.

**Comment by hthetiot** [comment]
You have TURN/STUN issue most likely.
I will update easyrtc.sylaps.com to master soon.

You should try to check your TURN and STUN server and avoid to have to much of them cause firefox does not like it.

**Comment by hthetiot** [comment]
Can you provide firefox and chrome version used please @syedMSohaib

**Comment by syedMSohaib** [comment]
Sir Actually i am testing it as local and i guess i don't need stun and turn  at my localhost 
btw the chrome version i am using is 69 and firefox is 62 both are latest updates.

**Comment by hthetiot** [comment]
Thx @syedMSohaid I will test and let you know.

**Comment by hthetiot** [comment]
Still cannot reproduce on last test pass on master

**Comment by hthetiot** [comment]
see #415 for beta for adapter 6.4.0 and #433 for PR with latest adapter 7.2.1.

see beta or 6.4.0 test result vs master

#422 (comment)
