### ISSUE TITLE
iOS: send audio only and receive video+audio question.

### ISSUE THREAD

**Issue by lazyfish** [priologic/easyrtc#419]
Hello. 
I'm trying to connect 2 callers, where one can send only audio but receive audio+video. This works fine with Firefox or Chrome clients, but I'm having trouble with iOS.

The setup is as follows:
Peer 1 (Chrome/Firefox/iOS). Should send video and audio, and receive audio only.
easyrtc.enableAudio(true)
easyrtc.enableVideo(true)

Peer 2 (iOS). Should send audio only, and receive video and audio.
easyrtc.enableAudio(true)
easyrtc.enableVideo(false)

Until I set easyrtc.enableVideo(true) on Peer 2' iOS side, nothing appears in the video tag. But this client should not transmit any video itself.
Is it a bug, or any additional parameters need to be set? Thanks.

**Comment by hthetiot** [comment]
Hum I dont have issue with iOS and audio only. Let me check and come back to you.

**Comment by hthetiot** [comment]
@lazyfish can you try beta branch it does have last webrtc adapter 6.4, where master still waiting to be merged via #415 on master.

> npm i priologic/easyrtc#beta

**Comment by hthetiot** [comment]
@lazyfish you say it work on chrome and firefox, that mean #416 and #414 are  invalid I think
Can you confirm and tell me you get master working on chrome and ff and give us version.

**Comment by lazyfish** [comment]
Sorry, forgot to mention, I'm using beta. I'll check latest browsers a bit later.

**Comment by lazyfish** [comment]
Well, the demo_audio_video_simple works fine on Windows Firefox 63.0 (64bit), Windows Chrome 70.0.3538.67 (Official Build) (64-bit), iOS 11.4.1, Android Firefox and Chrome, Ubuntu Firefox 62.03, Ubuntu Chrome 70.0.3538.67 for me on both master and beta.

Sometimes Firefox on Windows indeed has "Error getting local media stream: {0}", but for an old Logitech cam. Sometimes it works, sometimes it does not.

Also I cannot reproduce the original issue on the mentioned test page. Tested with a copy of the original page, but with modified js, so it runs with enableVideo(false). Unfortunately, in my project the issue remains. Will look further into it. 

Thanks for your time.

**Comment by lazyfish** [comment]
I was able to reproduce the issue on the demo_audio_video_simple page with easyrtc beta on the following setup:
Caller 1: Firefox 63.0
enableAudio(true)
enableVideo(true)

Caller 2: Chrome 70.0.3538.67 or iOS 11.4.1
demo_audio_video_simple2.html with modified js:
enableAudio(true)
enableVideo(false)

Caller 1 calls Caller 2: works as expected.
Caller 2 receives video and audio.
Caller 1 receives audio.

Caller 2 calls Caller 1: 
Caller 2 receives audio only.
Caller 1 receives audio.

When Caller 2 runs Firefox, everything works as expected in both cases.

**Comment by hthetiot** [comment]
I will also try to fix the issue your reproduced using chrome and Firefox.
Thx. 

Keep you posted.

**Comment by hthetiot** [comment]
Can you make sure you call the method below with rights argument and enable or disable Audio/Video before making or accepting the call.

Disabling during call should return innmute for audio or black screen for video.


> easyrtc.enableVideoReceive(false);
> easyrtc.enableAudioReceive(false);

**Comment by hthetiot** [comment]
Closing for inactive reporter
