### ISSUE TITLE
Still Broken on iOS Safari

### ISSUE THREAD

**Issue by fillybrese** [priologic/easyrtc#422]
This issue should not have been closed, because it still exists and there was not a solution applied at the time of closing the issue:

_Originally posted by @fillybrese in https://github.com/priologic/easyrtc/issue_comments#issuecomment-437271087_

**Comment by MariasStory** [comment]
Hi, demos do not work for me.
This reference solution works perfectly: https://meet.tokbox.com/
Please, look over and get some ideas.

**Comment by MariasStory** [comment]
Another working example: https://rtcmulticonnection.herokuapp.com/demos/Video-Conferencing.html
It looks like everyone can do safari on ios, but not easyrtc?

**Comment by hthetiot** [comment]
@fillybrese "This issue should not have been closed".

Not the right way to start a new issue. If you could have referenced the issue in particular cause there not only one that got closed.

We are not paid here so make sure to stay respectful.

Many user use EasyRTC on iOS Safari, if you have issue it does not mean it's global.
Can you tell me if you tried master and beta branch demo under SSL with proper TURN? 
If so then we can confirm their is an issue.

I have exposed the beta branch here for testing:
- https://easyrtc.sylaps.com/demos/demo_audio_video.html

**Comment by hthetiot** [comment]
"This issue should not have been closed". IT DOES.

No comment, since all test works, instead provide proper version of browser vendor your fail with and test to reproduce.

**Comment by hthetiot** [comment]
@fillybrese I have referenced all the iOS closed issue I have not found the comment you refer to.
This also show you I don't close for no reason if you look at this issues.

@MariasStory can you test and provide more info on device and browsers version used.
See test link on EasyRTC.sylaps.com above.

**Comment by hthetiot** [comment]
Note: I think I will had user agent to demo page for easy reporting.
I have updated browser grid with Edge and Safari macOS and iOS on master and last docker build already.

- https://hub.docker.com/r/hthetiot/easyrtc/
- https://easyrtc.sylaps.com/demos/

If anyone want to try I will leave docker image and demo running above.

**Comment by alvaroPardo** [comment]
Hi, I was trying the example (easyrtc.sylaps.com - Simple Video+Audio) in ionic v1 but it does not works. If I run the project with "ionic serve" it works cause it opens on Safari, but when I run on a device the camera does not shows anything. By the way, I get an id as if I were connected properly. I'm testing it on iOS 12.1.2.

Does anybody knows if this library could works on ionic 1? 
I appreciate some help.

**Comment by hthetiot** [comment]
@alvaroPardo yes we have successfully used EasyRTC in ionic 3+ and Cordova 7+ you need to use plugin to support WebRTC on ios and requests permissions on Android and iOS for camera and microphone.

**Comment by neilyoung** [comment]
iOS audio/video demo not working on Safari 12. It must be a problem with an invalid "getUserMedia" call, since there is no approval dialog for the camera, just an "Error getUserMedia notAllowed". This is astonishing, since WebRTC generally works fine in Safari 12. Refer to dragonfly-demo.accuware.com in your Safari and hit start.

**Comment by MorenoAlex** [comment]
@neilyoung 
Hello, I had a few problems too with iOS and Safari 12.
It turned out that [adapter.js](https://github.com/webrtchacks/adapter) is included in easyrtc.js, but it's outdated. By removing it from the easyrtc source code and including the latest version manualy to my project, it fixed all getUserMedia errors I used to encounter.

**Comment by neilyoung** [comment]
@MorenoAlex Thanks

**Comment by hthetiot** [comment]
see #415 for beta for adapter 6.4.0 (working for me already compare to master) and #433 for PR with latest adapter 7.2.1.

see beta or 6.4.0 test result vs master
- https://github.com/priologic/easyrtc/issues/422#issuecomment-441474729
