### ISSUE TITLE
300 ms delay problem

### ISSUE THREAD

**Issue by MariasStory** [priologic/easyrtc#423]
Hi,

I have a very odd problem with version "1.1.1-beta".

It seems to be a strange timing problem. I can not connect to the partner with easyrtc.call within/till some time after the page is loaded.

I needed to add another 300 ms before calling easyrtc.call for it to work.

My page is loaded in ~300 ms.

This does not happen with version "1.1.0" and the same code.

I also initialize camera and data channel. The data channel is initialized properly, but no video connection.

Maybe someone has an idea why would i happen?

Thanks,
Tolik

**Comment by hthetiot** [comment]
@MariasStory Can you compare master vs beta ad confirm if so the issue will be related to #415

**Comment by hthetiot** [comment]
@MariasStory Can you try the last docker image from master ?
> docker run -it --name myeasyrtc --rm -p 8443:8443 hthetiot/easyrtc:latest run server_ssl

This will start easyrtc on https://localhost:8443 with self signed certs.
- https://github.com/priologic/easyrtc/tree/master/server_example#manualy-build-and-run-container

**Comment by hthetiot** [comment]
unable to reproduce, reopen with full sample, if still an issue.
