### ISSUE TITLE
enableAudio enableVideo strange behaviour on Chrome

### ISSUE THREAD

**Issue by korangu** [priologic/easyrtc#426]
easyrtc.enableAudio(false);
     easyrtc.enableVideo(false);
     easyrtc.enableCamera(false);
    easyrtc.enableMicrophone(false);
    easyrtc.enableDataChannels(false);
    easyrtc.enableAudioReceive(true);
    easyrtc.enableVideoReceive(true);

with all these set i am trying to call  without sending my video and audio  a participant in a room who is currently streaming with both audio and video 

call is auto accepted but its not calling the easyrtc.setStreamAcceptor function which gets the stream of the person who is on call. 

it works on FF latest version but does not on Chrome latest version 

but if i change 
     easyrtc.enableVideo(false);
     easyrtc.enableCamera(false); to true 

then its working but i dont want the other person on call receive the caller audio/vedio stream. 

please help me . am i missing something?

**Comment by gino8080** [comment]
I ha ve same problem into Electron  ( so its CHROME ) only on WINDOWS

setStreamAcceptor never get called

**Comment by hthetiot** [comment]
We don't support Electron pls provide Chromium version used by electron.

I do use NodeWebkit aka nwjs.io and it work for me from Chromium 34 to 72 (nwjs 0.36.2)

**Comment by hthetiot** [comment]
unable to reproduce, reopen with full sample, if still an issue.
