### ISSUE TITLE
video chat demo not working on chrome

### ISSUE THREAD

**Issue by syonip** [priologic/easyrtc#427]
On this page: https://demo.easyrtc.com/demos/demo_audio_video_simple.html, getting this error:
```
Uncaught TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.
    at Easyrtc.createObjectURL (easyrtc.js:4152)
    at Easyrtc.setVideoObjectSrc (easyrtc.js:4633)
    at onUserMediaSuccess (easyrtc.js:4887)
```
I think it's because chrome has deprecated createObjectURL.
Happy to PR

**Comment by hthetiot** [comment]
This as been fixed on master and beta

**Comment by hthetiot** [comment]
For updated demos you can try https://easyrtc.sylaps.com/

Or the same demo:
- https://easyrtc.sylaps.com/demos/demo_audio_video_simple.html

**Comment by Simerjit-developer** [comment]
@hthetiot The updated demo links that you provided are not available. Would you please tell me the link for the updated demo's or sample code that is working?
