### ISSUE TITLE
Problem on Connecting Users in Audio-Video Chat

### ISSUE THREAD

**Issue by MoawazAyub** [priologic/easyrtc#428]
Hi All

In the Audio-video demo if two users are already connected then the third users, when he gets on-line he can see the other two users but cannot connect to them because they are already connected
For Example: Say user A, B and C are on-line and then user A connects with user B. but Still the user C can see A and B in connected users List but cannot connect to either of them. So is their a way for C to know that A and B are already talking to each other or C is able to see only those users that are not busy taking to other users.

Any help will be appreciated.

**Comment by hthetiot** [comment]
Can you reproduce using this demo:
- https://easyrtc.sylaps.com/demos/demo_audio_video.html

**Comment by MoawazAyub** [comment]
Thanks hthetiot for the solution.
