### ISSUE TITLE
easyrtc + kurento 

### ISSUE THREAD

**Issue by korangu** [priologic/easyrtc#429]
is it possible to use easyrtc with kurento?

**Comment by hthetiot** [comment]
Kotento support WebRTC so there is no reason it could not interoperate with EasyRTC, you will have to intercept SDP on easyRTC server and alternate the PeerConnection answer with Kurento.

- https://doc-kurento.readthedocs.io/en/6.9.0/tutorials/js/tutorial-helloworld.html

**Comment by korangu** [comment]
can you give me more information like example code how to intercept SDP?

**Comment by korangu** [comment]
sir please help

**Comment by korangu** [comment]
can it be used for one to many broadcast without lacking the broadcasting peer internet connection speed?

**Comment by hthetiot** [comment]
See `easyrtc.buildLocalSdpFilter` and `easyrtc.buildRemoteSdpFilter `

https://github.com/priologic/easyrtc/blob/master/api/labs/easyrtc_rates.js#L329
