### ISSUE TITLE
Looking for new maintainers

### ISSUE THREAD

**Issue by hthetiot** [priologic/easyrtc#441]
It is obvious that priologic, official maintainers of the easyrtc, no longer contribute to this project. I no longer use it professionally, we have other projects to maintain and the lack of time makes it impossible for us to participate in this project anymore.

So we are looking for new maintainers for easyRTC.

**Comment by rtarta** [comment]
@hthetiot  Hi if possible i can contribute to project ?

**Comment by hthetiot** [comment]
@rtarta sure, make PR with target beta and I will review and merge.
See exiting PR for examples.

**Comment by manh-vv** [comment]
It is good new that author is still alive on this project.

I have a small project using this and found out that your works is great.

**Comment by brentfriedman** [comment]
Are you still looking for a maintainer?

**Comment by viveksharmaui** [comment]
Are you still looking for a maintainer i'm interested .

**Comment by hthetiot** [comment]
@viveksharmaui the project as been forked here, cause the original owner will not help anymore.
- https://github.com/open-easyrtc/open-easyrtc

**Comment by viveksharmaui** [comment]
I'm very interested to contribute because i have used easyrtc in one of my project .

**Comment by ajay-psd** [comment]
Hi All

I tried all audio and video demo here https://demo.easyrtc.com/demos/   two weeks back. it was working absolutely fine.
Also I downloaded from GitHub and setup in my local, It was working and now also it is working in my local.

Today, I tried all audio and video demo, It is not working.  Looks not able to get Local media stream. I doubled checked Permissions are given to access media.
I have tried in Chrome, Safari and Adroid chrome. It did not worked all browser.

for this page  https://demo.easyrtc.com/demos/demo_video_only.html and all other pages. 
It connects to signalling server and list the user connected, 
1. It does not load the local media.
2. when we make call to other party, Call accept prompt will appear at other party window but while accepting the calls  nothing happens.

Its showing below error in console.log  

easyrtc.js:4152 Uncaught TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.
    at Easyrtc.createObjectURL (easyrtc.js:4152)
    at Easyrtc.setVideoObjectSrc (easyrtc.js:4633)
    at onUserMediaSuccess (easyrtc.js:4887)

Error points at this place , screen attached

`    /** @private
     * @param mediaStream */
    //
    // easyrtc.createObjectURL builds a URL from a media stream.
    // Arguments:
    //     mediaStream - a media stream object.
    // The video object in Chrome expects a URL.
    //
    this.createObjectURL = function(mediaStream) {
        var errMessage;
        if (window.URL && window.URL.createObjectURL) {
            **return window.URL.createObjectURL(mediaStream);**
        }
        else if (window.webkitURL && window.webkitURL.createObjectURL) {
            return window.webkit.createObjectURL(mediaStream);
        }
        else {
            errMessage = "Your browsers does not support URL.createObjectURL.";
            logDebug("saw exception " + errMessage);
            throw errMessage;
        }
    };
`
![image](https://user-images.githubusercontent.com/10988867/70324028-69d35b00-1854-11ea-8aeb-2ef21f78a85a.png)

**Comment by hthetiot** [comment]
The project OpenEasyRTC is getting good support from volunteer. 
I do recoamand to migrate as soon as possible if you use easyRTC because of major securities and bugs fixes.
