### ISSUE TITLE
Is It Possible to provide service video chat one to one using API in Mobile

### ISSUE THREAD

**Issue by adesurya** [priologic/easyrtc#445]
Dear Team,

Any try to implement easeRTC from mobile and access private room using API?
Private room is one to one video call, so i only access specific room id from mobile

If any one proven the wat please let me know,

Regards

**Comment by rtarta** [comment]
@adesurya you can join room 

`
//Join room 
easyrtc.joinRoom(roomid, null, function (a, b, c) {
        ////console.log("join room ", a, b, c)

    }, function (a, b, c) {
        //console.log("Join room Error", a, b, c)
    });
//Watch room accupants
easyrtc.setRoomOccupantListener(watchRoom);`

thats all

**Comment by hthetiot** [comment]
Thank you @rtarta
