### ISSUE TITLE
[question] How to add user metadata to connection?

### ISSUE THREAD

**Issue by szepczynski** [priologic/easyrtc#446]
Hi!

I have question - is it possible to add some meta data when user connect to the server? I need to add support for user type. How I can add extra fields for each connection?

**Comment by chrisdepas** [comment]
Assuming you need this immediately on connection, I would add a new field to the client's credential object.
 
Before you initiate a connection to the server, you can set the client's credential to any JSONable object.

```js
easyrtc.setCredential({ key, timestamp, type, whateverElseYouNeed });
```

You can then read this in your signalling server's authenticate event:
```js
easyrtc.events.on("authenticate", (socket, id, appName, username, credential, authMsg, next) => {
    if (!credential) {
        next(new easyrtc.util.ConnectionError("Credentials must be provided"));
    }
    if (!("type" in credential))
        next(new easyrtc.util.ConnectionError("Missing user type"));
        return;
    }
    // ... actual password validation must be implemented, as everyone gets in by default
});
```
See [here](https://github.com/priologic/easyrtc/blob/master/docs/easyrtc_authentication.md) for more info

**Comment by szepczynski** [comment]
Thanks!
