### ISSUE TITLE
Multiparty chatroom for only text chat

### ISSUE THREAD

**Issue by syedMSohaib** [priologic/easyrtc#447]
Can you guys guide me on how to achieve group chat via multiparty chatroom but without video calling as i look into easyApp
`    easyrtc.easyApp("easyrtc.multiparty", "box0", ["box1", "box2", "box3"], loginSuccess);
`
it recieves my video id with recipient ids. and what if the group consist of more than 3 members lets say 50 do i need to manually set those paramters.

**Comment by hthetiot** [comment]
See demos https://github.com/priologic/easyrtc/blob/master/demos/js/demo_instant_messaging.js
