### ISSUE TITLE
enableAudioReceive, enableVideoReceive issues on Chromium 69 with plan-b

### ISSUE THREAD

**Issue by chrisdepas** [priologic/easyrtc#449]
`offerToReceiveAudio` and `offerToReceiveVideo` no longer function for me correctly.
The client I make a call from will not receive video streams at all unless they are sending a video stream.
This is similar to this other issue:
https://github.com/priologic/easyrtc/issues/138

My chromium version string (from chrome://version) is 
```
69.0.3497.100 (Official Build) built on Ubuntu bionic/18.04, running on Ubuntu bionic/18.04 (64-bit)
```

I am forcing `plan-b` to be used (as it [doesn't seem like](https://github.com/priologic/easyrtc/issues/406) easyrtc fully supports `unified-plan`) by changing the `RTCPeerConnection` constructor:
```
RTCPeerConnection({iceServers: [], sdpSemantics:'plan-b'});
```

The issue seems to be caused by the following, where `receivedMediaConstraints` is structured with a `mandatory` field

[At line 5985 in easyrtc.js](https://github.com/priologic/easyrtc/blob/5ea69776f319fab15a784f94db91a2c1f5154ef5/api/easyrtc.js#L5985)
```
this.enableAudioReceive = function(value) {
        if (
            adapter && adapter.browserDetails &&
             (adapter.browserDetails.browser === "firefox" || adapter.browserDetails.browser === "edge")
        ) {
            receivedMediaConstraints.offerToReceiveAudio = value;
        }
        else {
            receivedMediaConstraints.mandatory = receivedMediaConstraints.mandatory || {};
            receivedMediaConstraints.mandatory.OfferToReceiveAudio = value;
        }
    };

    /**
     * Control whether the client requests video from a peer during a call.
     * Must be called before the call to have an effect.
     * @param value - true to receive video, false otherwise. The default is true.
     */
    this.enableVideoReceive = function(value) {
        if (
            adapter && adapter.browserDetails &&
             (adapter.browserDetails.browser === "firefox" || adapter.browserDetails.browser === "edge")
        ) {
           receivedMediaConstraints.offerToReceiveVideo = value;
        }
        else {
            receivedMediaConstraints.mandatory = receivedMediaConstraints.mandatory || {};
            receivedMediaConstraints.mandatory.OfferToReceiveVideo = value;
        }
    };
}
```

Later, in [initiateSendOffer()](https://github.com/priologic/easyrtc/blob/5ea69776f319fab15a784f94db91a2c1f5154ef5/api/easyrtc.js#L9659), at [line 9695](https://github.com/priologic/easyrtc/blob/5ea69776f319fab15a784f94db91a2c1f5154ef5/api/easyrtc.js#L9695), SDP without recvonly for video/audio (no video/audio is included in sdp at all) is created. 

```
pc.createOffer(receivedMediaConstraints)
                 .then(setLocalAndSendMessage0)
                 .catch(
                   function(errorObj) {
                     peerConnObj.callFailureCB(self.errCodes.CALL_ERR, 
                        JSON.stringify(errorObj));
                   }
                  );
```

As my application
- Requires a video/audio stream to be received always
- Only needs to support chrome and chromium
- Forces the client to use `plan-b`

I can work around this for now by changing `initiateSendOffer()` to the following:

```
const constraints = {
                offerToReceiveAudio: true,
                offerToReceiveVideo: true, 
                mandatory: {
                         offerToReceiveAudio: true,
                         offerToReceiveVideo: true, 
                },
            }
            pc.createOffer(constraints)
                 .then(setLocalAndSendMessage0)
                 .catch(
                   function(errorObj) {
                     peerConnObj.callFailureCB(self.errCodes.CALL_ERR, 
                        JSON.stringify(errorObj));
                   }
                  );
```

(Note to anyone debugging a similar issue in the future: Using both `offerTo...` fields in both root of object and `mandatory` is probably a bad idea, I'm just using it because new chromium seems to ignore it, but older chromium may require it)

**Comment by hthetiot** [comment]
You taking about 2 different issue, `plan-b` and the change of peer constraints `receivedMediaConstraints.mandatory. (offerToReceiveAudio|offerToReceiveVideo)`. 

To set `plan-b` or `'unified-plan` manually you can use following.
```
 var pcConfig = easyrtc.getServerIce();
pcConfig.sdpSemantics = 'unified-plan';
//pcConfig.sdpSemantics = 'plan-b';
easyrtc.setIceUsedInCalls(pcConfig);
``` 

On the `receivedMediaConstraints.mandatory.(OfferToReceiveAudio|OfferToReceiveVideo)` vs  receivedMediaConstraints.(offerToReceiveAudio|offerToReceiveVideo) I pushed the following fix for you 9d36d748e286e3e3abfd1e47de3c90b681c19a69, see details of the new function below.
```
/**
     * Control whether the client requests audio from a peer during a call.
     * Must be called before the call to have an effect.
     * @param value - true to receive audio, false otherwise. The default is true.
     */
    this.enableAudioReceive = function(value) {
        if (
             adapter && adapter.browserDetails &&
                 (adapter.browserDetails.browser === "chrome" && adapter.browserDetails.version < 65)
         ) {
            receivedMediaConstraints.mandatory = receivedMediaConstraints.mandatory || {};
            receivedMediaConstraints.mandatory.OfferToReceiveAudio = value;
        } else {
            receivedMediaConstraints.offerToReceiveAudio = value;
        }
    };

    /**
     * Control whether the client requests video from a peer during a call.
     * Must be called before the call to have an effect.
     * @param value - true to receive video, false otherwise. The default is true.
     */
    this.enableVideoReceive = function(value) {
        if (
             adapter && adapter.browserDetails &&
                 (adapter.browserDetails.browser === "chrome" && adapter.browserDetails.version < 65)
         ) {
            receivedMediaConstraints.mandatory = receivedMediaConstraints.mandatory || {};
            receivedMediaConstraints.mandatory.OfferToReceiveVideo = value;
        } else {
           receivedMediaConstraints.offerToReceiveVideo = value;
        }
    };
```

**Comment by hthetiot** [comment]
This should also work better with Cordova-plugin-iosrtc:
- https://github.com/BasqueVoIPMafia/cordova-plugin-iosrtc/blob/master/src/PluginRTCPeerConnectionConstraints.swift#L16

**Comment by hthetiot** [comment]
@chrisdepas I merged some other fixes on beta, can you try if that works properly for you on beta (no regression).

**Comment by chrisdepas** [comment]
@hthetiot Thanks so much for fixing this for me, and for the letting me know how to change sdpSemantics properly! 

I've tried the beta branch out, and I can confirm that the SDP is generated correctly for all permutations of a client with a single webcam/mic, this seems to have fixed the issue completely.

| Webcam  | Mic  | Resulting SDP Video | Resulting SDP Audio |
| :-----------: | :----: | :--------------------------: | :--------------------------: |
| ✘ | ✘ | recvonly | recvonly |
| ✘ | ✓|  recvonly | sendrecv |
| ✓ | ✓|  sendrecv | sendrecv |
| ✓ | ✘|  sendrecv | recvonly |

**Comment by hthetiot** [comment]
Thank you @chrisdepas for testing \0/ see you on open-easyrtc
