### ISSUE TITLE
EasyRTC sdk for react native

### ISSUE THREAD

**Issue by syedMSohaib** [priologic/easyrtc#453]
@hthetiot buddy how soon can we expect easyrtc sdk for react native.

**Comment by hthetiot** [comment]
Fucking stupid React people that dont understand JavaScript or TypeScript.

**Comment by syedMSohaib** [comment]
I know you are an asshole but dont need to show everyone. Just a little guidance won’t hurt your fucking pride jackass.

**Comment by hthetiot** [comment]
@syedMSohaib man, you asking for React support, do you even understand JavaScript or TypeScript ? if so https://github.com/priologic/easyrtc/tree/master/typescript_support

> I know you are an asshole
Only with people that write issues comments that are a waste of time :)

**Comment by hthetiot** [comment]
so fare on the hundred of packages I maintain all the "react native" issue have been from people that dont undertand that React = TypeScript = JavaScript and that all modules written in UMD (Universal Module Definition) will work on any enviroment (require.js, yarn, npm, webpack). 

Simply you need to learn JavaScript and stop creating issue "he I need React native support", no you dont. Just learn JavaScript and you can do anything you want in TypeScript and/or React Shit.

Note: The word "Native" in "React Native" does not mean shit, it's not Native anyway.
You want Native learn Swift or JAVA or C.

**Comment by syedMSohaib** [comment]
I know your are sick and tired of facing same issue again and again , and somewhat your are right but still i think there is a better way to convey your thought, as your are a core contributor of so many packages, such language does not suit you. As you represent open source community. you should act like one since this is not facebook or that shit. 

Sorry if i offended you.

**Comment by hthetiot** [comment]
@syedMSohaib you did not offended me. Only me could have offended you and that was not my goal, sorry if i did.

You are right in what you say, but that the way I am :) I can be really nice if the comment or issues is pertinent.

The only advice i can give you after 20 years of Javascript is "don't use React".

**Comment by syedMSohaib** [comment]
Its k :) , 20 Years of JS, thats great, i have just started my career so much to learn. Will follow your advise too.
