### ISSUE TITLE
Demos are not working properly

### ISSUE THREAD

**Issue by ajay-psd** [priologic/easyrtc#457]
Hi All

I tried all audio and video demo here https://demo.easyrtc.com/demos/   two weeks back. it was working absolutely fine. Also I downloaded from GitHub 2 week back and setup in my dev, It was working and now also it is working in my dev.

Today, I tried checking online all audio and video demo, It is not working properly now. 
 Looks not able to get Local media stream. I doubled checked Permissions are given to access media. I have tried in Chrome, Safari and Android chrome. It did not worked all browser.

for this page  https://demo.easyrtc.com/demos/demo_video_only.html and all other pages. 
It connects to signalling server and list the user connected, 
1. It does not load the local media.
2. when we make call to other party, Call accept prompt will appear at other party window but while accepting the calls  nothing happens.

Is any one also facing this issue in latest demo,  Can any one suggest how to fix this ??

Its showing below error in console.log  
easyrtc.js:4152 Uncaught TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.
    at Easyrtc.createObjectURL (easyrtc.js:4152)
    at Easyrtc.setVideoObjectSrc (easyrtc.js:4633)
    at onUserMediaSuccess (easyrtc.js:4887)

Error points at this place , screen attached
    if (window.URL && window.URL.createObjectURL) {
            **return window.URL.createObjectURL(mediaStream);**
        }
![image](https://user-images.githubusercontent.com/10988867/70325027-04cd3480-1857-11ea-813c-606e82b22f56.png)

**Comment by hthetiot** [comment]
This project is non longet supported and should not be used in production du major security issues.
- https://github.com/priologic/easyrtc/issues/451

Instead you can use OpenEasyRTC that is maintain by volunteer of the community:
- https://github.com/open-easyrtc/open-easyrtc/issues/6

**Comment by hthetiot** [comment]
mediaStream is not a valid MediaStream in your case or you do not use srcObject

**Comment by ajay-psd** [comment]
Thanks 
I will check with open-easyrtc
