### ISSUE TITLE
Not getting remote stream on different networks, different wifi

### ISSUE THREAD

**Issue by hafizImran** [priologic/easyrtc#460]
I've tried different networks on android mobile to utilize easyrtc but its work fine for same wifi but not working in
different wifi
3g/4g to wifi
wifi to 3g/4g

**Comment by rtarta** [comment]
@hafizImran need to use turn and stun service to make stable connection

**Comment by hthetiot** [comment]
Thank you @rtarta 

@hafizImran see this doc:

https://github.com/open-easyrtc/open-easyrtc/blob/master/docs/easyrtc_server_ice.md


Note: this project is not maintain anymore we recommend to use Open-easyrtc instead. https://github.com/open-easyrtc/open-easyrtc
