### ISSUE TITLE
Better WebRTC detection to cover for old versions of Opera.

### ISSUE THREAD

**Issue by dryswabbie** [priologic/easyrtc#50]
As noted in the following forum post, older versions of Opera are not properly caught by the browser checker as being unable to handle WebRTC. Errors result.

 - https://groups.google.com/forum/#!topic/easyrtc/ijvO2R3J-o8

The browser checking algorithm should be updated to cover Opera, or made to be more generic.

**Comment by hthetiot** [comment]
@dryswabbie Related I think to #194 cause It works for me even in Asia Opera that got WebRTC early.

**Comment by hthetiot** [comment]
let leave that to the Adapter from WebRTC.org for now.
