### ISSUE TITLE
initMediaSource should assume the camera or the microphone might not be present

### ISSUE THREAD

**Issue by EricDavies** [priologic/easyrtc#83]
getUserMedia will now fail on chrome if you don't have a microphone and you've requested audio.  initMediaSource should ask initially ask for what the app requested, but if that fails, try asking for a subset of it (no audio or no video), emitting a warning message in that case so the user knows why they aren't getting audio or video.

**Comment by hthetiot** [comment]
It is still a thing ?

**Comment by EricDavies** [comment]
I'm not sure. Hopefully not, given it's age :-).
