### ISSUE TITLE
WebRTC Version Detecting Fails When Simulating iPad In Chrome Dev Tools

### ISSUE THREAD

**Issue by petermetz** [priologic/easyrtc#90]
Newer versions of Google Chrome come with the possibility to simulate tablets and mobile phones very easily. However, when I do this, easyrtc crashes in case of simulating an iPad.

You could argue if it's a bug in easyrtc or not, since it only comes out at development time, and only when simulating an iPad, but it would be nice to have it fixed to be more future proof. Up to the developers, I just wanted to report it so it won't go unnoticed.

For the exact configuration to reproduce, please see the attached screenshot.
The version of easyrtc I'm on is: 1.0.11
![screen shot 2014-08-23 at 13 07 09](https://cloud.githubusercontent.com/assets/1583231/4020531/04800178-2abf-11e4-9bf5-ad242593d550.png)

**Comment by hthetiot** [comment]
duplicate #177
