### ISSUE TITLE
Expose roomObj.emitRoomDataFieldUpdate

### ISSUE THREAD

**Issue by dryswabbie** [priologic/easyrtc#97]
Currently roomObj.emitRoomDataFieldUpdate is marked as incomplete. It should be completed so room fields may properly be used.

Discussed in [this forum thread](https://groups.google.com/forum/#!topic/easyrtc/sT5VihLX5EA).

**Comment by hthetiot** [comment]
78db17f9b9566c57bfdd7ed8237fe8e971af4fba
